import '@awesome.me/webawesome/dist/styles/webawesome.css';
import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/dialog/dialog.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import './style.css';

import { delegate, mount, signal } from 'kerfjs';

import { Api, type FullTicket, type RepositoryStatus, type TicketRow as WireTicketRow } from './api';
import { AppShell } from './components/app-shell';
import { PageHeader } from './components/page-header';
import { ProjectSidebar } from './components/project-sidebar';
import { QuickTicketComposer } from './components/quick-ticket-composer';
import type { TicketStatus } from './components/status-badge';
import { TicketBoard } from './components/ticket-board';
import { type InspectorTab,TicketInspector } from './components/ticket-inspector';
import { TicketList } from './components/ticket-list';
import type { TicketPriority, TicketRowProps } from './components/ticket-row';
import { WorkspaceControls, WorkspaceIdentity, type WorkspaceSort, type WorkspaceViewMode } from './components/workspace-header';

type Control = HTMLElement & { value:string; show?():void; hide?():void };
interface Project { id:string; root:string; name:string; stores:string[]; apiPath:string }
const data = (target: Element) => (target as HTMLElement).dataset;

const projects = signal<Project[]>([]), selectedProjectId = signal(''), tickets = signal<WireTicketRow[]>([]), selectedTicket = signal<FullTicket|null>(null), repository = signal<RepositoryStatus|null>(null);
const loading = signal(false), error = signal(''), viewMode = signal<WorkspaceViewMode>('list'), selectedView = signal('all'), searchOpen = signal(false), searchQuery = signal(''), sort = signal<WorkspaceSort>('updated');
const composerExpanded = signal(false), composerTitle = signal(''), composerCategory = signal('task'), inspectorTab = signal<InspectorTab>('info'), sidebarVisible = signal(true), inspectorVisible = signal(true);
const project = () => projects.value.find(item => item.id === selectedProjectId.value);
const api = () => new Api(project()?.apiPath ?? '');
const isClosed = (ticket:WireTicketRow) => ['completed','verified','moved'].includes(ticket.status ?? '');
const status = (value?:string):TicketStatus => ['not_started','started','completed','verified','backlog'].includes(value ?? '') ? value as TicketStatus : 'not_started';
const priority = (value?:string):TicketPriority => ['low','default','high','urgent'].includes(value ?? '') ? value as TicketPriority : 'default';
const ago = (value?:string) => { if (!value) return 'Recently'; const seconds=Math.max(0,(Date.now()-Date.parse(value))/1000); if(seconds<60)return 'Now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`; };
const row = (ticket:WireTicketRow):TicketRowProps => ({slug:ticket.slug,title:ticket.title,status:status(ticket.status),priority:priority(ticket.priority),category:ticket.category??'issue',tags:ticket.tags,upNext:ticket.up_next,blocked:ticket.blocked_by.length>0,selected:selectedTicket.value?.id===ticket.id,busy:ticket.claim_count>0,agentName:ticket.worker_label||ticket.claimed_by||'AI',updatedLabel:ago(ticket.updated_at)});

function visibleTickets(){let result=tickets.value.filter(ticket=>selectedView.value==='archive'?isClosed(ticket):selectedView.value==='backlog'?ticket.status==='backlog':!isClosed(ticket));const query=searchQuery.value.trim().toLowerCase();if(query)result=result.filter(ticket=>`${ticket.slug} ${ticket.title} ${ticket.tags.join(' ')}`.toLowerCase().includes(query));return result.slice().sort((a,b)=>sort.value==='title'?a.title.localeCompare(b.title):sort.value==='priority'?['urgent','high','default','low'].indexOf(a.priority??'default')-['urgent','high','default','low'].indexOf(b.priority??'default'):sort.value==='status'?(a.status??'').localeCompare(b.status??''):(b.updated_at??'').localeCompare(a.updated_at??''));}

async function refreshProject(){const current=project();if(!current)return;loading.value=true;try{const client=api();const [nextTickets,nextRepository]=await Promise.all([client.checkoutTickets(current.id),client.repositoryStatus(current.id).catch(()=>null)]);tickets.value=nextTickets;repository.value=nextRepository;error.value='';if(selectedTicket.value){const matching=nextTickets.find(item=>item.id===selectedTicket.value?.id);selectedTicket.value=matching?(await client.checkoutTicket(current.id,matching.id)).ticket:null;}}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
async function updateSelected(patch:Record<string,unknown>){if(!project()||!selectedTicket.value)return;try{selectedTicket.value=(await api().updateCheckoutTicket(project()!.id,selectedTicket.value.id,patch)).ticket;await refreshProject();}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}}
async function openProject(root:string,ticketStore?:string,remember=true){loading.value=true;try{const response=await fetch('/__hotsheet/projects/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({root,ticketStore})});const value=await response.json() as Project&{error?:string};if(!response.ok)throw new Error(value.error||'Could not open project.');projects.value=[...projects.value.filter(item=>item.id!==value.id),value];selectedProjectId.value=value.id;if(remember)localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));(document.querySelector<Control>('[data-project-dialog]'))?.hide?.();await refreshProject();}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
function timeline(ticket:FullTicket){return ticket.notes.filter(note=>note.kind==='activity'||note.kind==='status').map(note=>{const [title,...rest]=note.text.split('\n');return{id:note.id,time:ago(note.created_at),title:title||'Ticket updated',subtitle:rest.join('\n').trim()||undefined,emphasized:note.kind==='status'};});}
function notes(ticket:FullTicket){return ticket.notes.filter(note=>note.kind!=='activity').map(note=>({id:note.id,kind:note.kind==='feedback_draft'?'regular':note.kind,author:'Hot Sheet',time:ago(note.created_at),body:note.text} as const));}

function ProjectDialog(){return <wa-dialog data-project-dialog label="Open project"><form class="project-dialog" data-action="open-project-form"><p>Select a code checkout. Hot Sheet automatically uses a valid sibling <code>&lt;project&gt;.hs2</code> ticket store. Override it when the project uses another store.</p><wa-input name="project-root" label="Project folder" value="/Users/westphal/Documents/hotsheet2" required></wa-input><wa-input name="ticket-store" label="Ticket store (optional)" placeholder="Automatically discover &lt;project&gt;.hs2"></wa-input><p class="project-dialog__error" role="alert">{error.value}</p><footer><wa-button appearance="plain" type="button" data-action="cancel-open-project">Cancel</wa-button><wa-button appearance="accent" type="submit">Open project</wa-button></footer></form></wa-dialog>;}
function EmptyState(){return <section class="app-empty"><h1>Open a Hot Sheet project</h1><p>Choose a code checkout to discover its ticket sources and start working.</p><wa-button appearance="accent" data-action="add-project">Open project</wa-button></section>;}
function Sidebar(){const open=tickets.value.filter(ticket=>!isClosed(ticket)),repo=repository.value;return <ProjectSidebar completedToday={tickets.value.filter(ticket=>ticket.completed_at?.startsWith(new Date().toISOString().slice(0,10))).length} inProgress={tickets.value.filter(ticket=>ticket.status==='started').length} completionTrend={[0,0,0,0,0,0,0]} branch={repo?.branch??'No git branch'} unpushed={repo?.ahead??0} uncommitted={(repo?.staged??0)+(repo?.unstaged??0)+(repo?.untracked??0)} views={[{id:'all',label:'All Tickets',count:open.length,icon:'all'},{id:'backlog',label:'Backlog',count:tickets.value.filter(ticket=>ticket.status==='backlog').length,icon:'backlog'},{id:'archive',label:'Archive',count:tickets.value.filter(isClosed).length,icon:'archive'}]} selectedViewId={selectedView.value} commandGroupLabel="Project commands" commands={[]} commandGroupExpanded={false} driveRunning={false} driveTool="Codex" collapseControl/>;}
function Inspector(){const ticket=selectedTicket.value;if(!ticket)return null;return <TicketInspector slug={ticket.slug} title={ticket.title} status={status(ticket.status)} priority={priority(ticket.priority)} category={ticket.category??'issue'} tags={ticket.tags} details={ticket.details} notes={notes(ticket)} blockedReason={ticket.blocked_reason} providerName="Hot Sheet git" updatedLabel={`Updated ${ago(ticket.updated_at)}`} activeTab={inspectorTab.value} upNext={ticket.up_next} timelineEntries={timeline(ticket)} attachments={ticket.attachments.map(item=>({id:item.id,name:item.filename,size:'',kind:'file'}))}/>;}
function Workspace(){const shown=visibleTickets();if(viewMode.value==='settings')return <section class="project-settings"><h2>Ticket sources</h2><p>This checkout uses {project()?.stores.length??0} git ticket source{project()?.stores.length===1?'':'s'}.</p>{project()?.stores.map(store=><div class="project-settings__source"><strong>Hot Sheet git</strong><code>{store}</code></div>)}<p>External provider connections live in the ticket store’s <code>providers.json</code>. Shared and local preferences remain in <code>hotsheet-settings.json</code> and <code>hotsheet-settings.local.json</code>; they are not the provider registry.</p></section>;if(viewMode.value==='board')return <TicketBoard columns={[{id:'backlog',title:'Backlog',tickets:shown.filter(ticket=>ticket.status==='backlog').map(row)},{id:'started',title:'In progress',tickets:shown.filter(ticket=>ticket.status==='started').map(row)},{id:'ready',title:'Ready',tickets:shown.filter(ticket=>!['backlog','started'].includes(ticket.status??'')).map(row)}]} label="Project board"/>;return <TicketList tickets={shown.map(row)} label="Project tickets"/>;}

mount(document.querySelector('#app')!,()=> <>{project()?<AppShell tabs={projects.value.map(item=>({id:item.id,name:item.name,location:'local',selected:item.id===selectedProjectId.value}))} sidebar={<Sidebar/>} sidebarVisible={sidebarVisible.value} header={<WorkspaceIdentity projectName={project()!.name}/>} headerActions={<WorkspaceControls mode={viewMode.value} searchOpen={searchOpen.value} searchQuery={searchQuery.value} sort={sort.value}/>} pageHeader={<PageHeader title={selectedView.value==='archive'?'Archive':selectedView.value==='backlog'?'Backlog':'All Tickets'}/>} composer={viewMode.value!=='settings'?<QuickTicketComposer expanded={composerExpanded.value} title={composerTitle.value} category={composerCategory.value} providerName="Hot Sheet git"/>:undefined} workspace={<Workspace/>} workspacePresentation={viewMode.value==='board'?'edge-to-edge':'inset'} inspector={<Inspector/>} inspectorVisible={inspectorVisible.value&&viewMode.value!=='settings'}/>:<EmptyState/>}<ProjectDialog/>{loading.value&&<div class="app-loading" role="status">Loading…</div>}{error.value&&project()&&<div class="app-error" role="alert">{error.value}</div>}</>);

delegate(document.body,'click','[data-action="add-project"]',()=>{error.value='';(document.querySelector('[data-project-dialog]') as Control).show?.()});
delegate(document.body,'click','[data-action="cancel-open-project"]',()=>{(document.querySelector('[data-project-dialog]') as Control).hide?.()});
delegate(document.body,'submit','[data-action="open-project-form"]',(event,target)=>{event.preventDefault();const root=(target.querySelector('[name="project-root"]') as Control).value,store=(target.querySelector('[name="ticket-store"]') as Control).value;void openProject(root,store||undefined)});
delegate(document.body,'click','[data-action="select-project-tab"]',(_event,target)=>{selectedProjectId.value=data(target).projectId!;selectedTicket.value=null;void refreshProject()});
delegate(document.body,'click','[data-action="close-project-tab"]',(_event,target)=>{projects.value=projects.value.filter(item=>item.id!==data(target).projectId);selectedProjectId.value=projects.value[0]?.id??'';localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));void refreshProject()});
delegate(document.body,'click','[data-action="select-ticket-row"]',(_event,target)=>{const ticket=tickets.value.find(item=>item.slug===data(target).ticketSlug);if(ticket&&project())void api().checkoutTicket(project()!.id,ticket.id).then(result=>{selectedTicket.value=result.ticket;inspectorVisible.value=true;error.value=''}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})});
delegate(document.body,'click','[data-action="select-view"]',(_event,target)=>{selectedView.value=data(target).itemId??'all'});
delegate(document.body,'click','[data-action="set-view-mode"]',(_event,target)=>{viewMode.value=data(target).viewMode as WorkspaceViewMode});
delegate(document.body,'click','[data-action="open-workspace-search"]',()=>{searchOpen.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="workspace-search"]')?.focus())});
delegate(document.body,'input','[name="workspace-search"]',(_event,target)=>{searchQuery.value=(target as Control).value});
delegate(document.body,'focusout','[name="workspace-search"]',(_event,target)=>{if(!(target as Control).value){searchOpen.value=false;searchQuery.value=''}});
delegate(document.body,'click','[data-sort]',(_event,target)=>{sort.value=data(target).sort as WorkspaceSort});
delegate(document.body,'click','[data-action="expand-ticket-composer"]',()=>{composerExpanded.value=true});
delegate(document.body,'click','[data-action="cancel-ticket-composer"]',()=>{composerExpanded.value=false;composerTitle.value=''});
delegate(document.body,'input','[name="new-ticket-title"]',(_event,target)=>{composerTitle.value=(target as Control).value});
delegate(document.body,'change','[name="new-ticket-category"]',(_event,target)=>{composerCategory.value=(target as Control).value});
delegate(document.body,'submit','[data-action="create-ticket-form"]',(event)=>{event.preventDefault();if(!project()||!composerTitle.value.trim())return;void api().createCheckoutTicket(project()!.id,{title:composerTitle.value.trim(),category:composerCategory.value}).then(()=>{composerExpanded.value=false;composerTitle.value='';return refreshProject()}).catch(reason=>{error.value=String(reason)})});
delegate(document.body,'click','[data-action="toggle-row-up-next"]',(event,target)=>{event.stopPropagation();const article=target.closest('[data-ticket-slug]') as HTMLElement,ticket=tickets.value.find(item=>item.slug===article.dataset.ticketSlug);if(ticket&&project())void api().updateCheckoutTicket(project()!.id,ticket.id,{up_next:!ticket.up_next}).then(refreshProject)});
delegate(document.body,'click','[data-action="toggle-inspector-up-next"]',()=>{if(project()&&selectedTicket.value)void api().updateCheckoutTicket(project()!.id,selectedTicket.value.id,{up_next:!selectedTicket.value.up_next}).then(refreshProject)});
delegate(document.body,'change','[name="inspector-category"]',(_event,target)=>{void updateSelected({category:(target as Control).value})});
delegate(document.body,'change','[name="inspector-priority"]',(_event,target)=>{void updateSelected({priority:(target as Control).value})});
delegate(document.body,'click','[data-inspector-status]',(_event,target)=>{void updateSelected({status:data(target).inspectorStatus})});
delegate(document.body,'click','[data-action="set-inspector-tab"]',(_event,target)=>{inspectorTab.value=data(target).inspectorTab as InspectorTab});
delegate(document.body,'click','[data-action="close-ticket-inspector"]',()=>{inspectorVisible.value=false});
delegate(document.body,'click','[data-action="open-ticket-inspector"]',()=>{inspectorVisible.value=true});
delegate(document.body,'click','[data-action="toggle-project-sidebar"]',()=>{sidebarVisible.value=!sidebarVisible.value});
for(const root of JSON.parse(localStorage.getItem('hotsheet.open-projects')||'[]') as string[])void openProject(root,undefined,false);
