import '@awesome.me/webawesome/dist/styles/webawesome.css';
import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/dialog/dialog.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import './theme.css';
import './style.css';

import { delegate, mount, signal } from 'kerfjs';
import { PanelRightClose } from 'lucide';

import { Api, type Capabilities, type CorruptTicket, type FullTicket, type RepositoryStatus, type TicketRow as WireTicketRow } from './api';
import { describeUnreadableAttachments, screenAttachmentFiles } from './attachment-files';
import { AppShell } from './components/app-shell';
import { ConnectionStateBanner, type ConnectionState } from './components/connection-state-banner';
import { LucideIcon } from './components/lucide-icon';
import type { MarkdownEditorMode } from './components/markdown-editor';
import { NotificationCenter } from './components/notification-center';
import { NotWorkingDialog } from './components/not-working-dialog';
import { PageHeader } from './components/page-header';
import { PermissionRequestPopup } from './components/permission-request-card';
import { ProjectSidebar } from './components/project-sidebar';
import { focusQuickTicketComposerTitle,QuickTicketComposer } from './components/quick-ticket-composer';
import type { TicketStatus } from './components/status-badge';
import { TicketBoard } from './components/ticket-board';
import { type InspectorTab,TicketInspector } from './components/ticket-inspector';
import { TicketList } from './components/ticket-list';
import { TicketReader } from './components/ticket-reader';
import type { TicketPriority, TicketRowProps } from './components/ticket-row';
import { TicketRowContextMenu } from './components/ticket-row-context-menu';
import { adjacentTicketSlug, selectAllTickets, updateTicketSelection } from './components/ticket-selection';
import { addTicketTag, removeTicketTag } from './components/ticket-tag-editor';
import { Toolbar } from './components/toolbar';
import { ToolbarControlGroup } from './components/toolbar-control-group';
import { applyWorkspaceSortDirection, defaultWorkspaceSortDirection, nextWorkspaceSort, WorkspaceControls, WorkspaceIdentity, type WorkspaceSort, type WorkspaceSortDirection, type WorkspaceViewMode } from './components/workspace-header';
import { createDebouncedAutosave } from './debounced-autosave';
import { priorityFromWire } from './priority-wire';
import { isFeedbackNeeded } from './feedback-needed';
import { startProjectChangePoll } from './project-change-poll';
import { loadProjectTicketRefresh } from './project-ticket-refresh';
import { createRenderMetrics } from './render-metrics';
import { submitNotWorkingReport } from './not-working-workflow';
import { DEFAULT_PERMISSION_AUTOMATION,formatPermissionCountdown,parsePermissionAutomation,parsePermissionHistory,PermissionInbox,PERMISSION_DELAYS,type PermissionAutomation,type PermissionDecision,type PermissionItem,type PermissionScope,VisiblePermissionTimer } from './permission-notifications';
import { ticketBoardGroups } from './ticket-board-layout';
import { type ClipboardTicket, deduplicateTitle, TicketHistory, type TicketPatch, type TicketSnapshot } from './ticket-operations';
import { projectTicketPatch, reportMutationTiming, ticketRowFromFull } from './ticket-mutation';
import { isArchivedTicket, isQueuedTicket, ticketsForView, type TicketView } from './ticket-views';
import { ticketTimelineEntries } from './ticket-timeline-data';
import type { CompatibilityAssessment } from './compatibility';

if(import.meta.env.DEV){const dev=await import('kerfjs/dev');dev.enableWarnings({valueOnlyRerender:true,listRebind:true,invariants:'throw'})}

type Control = HTMLElement & { value:string; open?:boolean; show?():void; hide?():void };
interface Project { id:string; root:string; name:string; stores:string[]; apiPath:string; compatibility:CompatibilityAssessment }
const data = (target: Element) => (target as HTMLElement).dataset;

const projects = signal<Project[]>([]), selectedProjectId = signal(''), tickets = signal<WireTicketRow[]>([]), corruptTickets = signal<CorruptTicket[]>([]), selectedTicket = signal<FullTicket|null>(null), repository = signal<RepositoryStatus|null>(null);
const selectedTicketSlugs = signal<string[]>([]);
const ticketContextMenu=signal<{x:number;y:number;ticketSlug:string}|undefined>(undefined);
interface NotWorkingTarget { projectId:string; apiPath:string; ticketId:string; slug:string; connectionId:string }
interface PendingEvidence { id:string; name:string; file:File }
const CLOSED_NOT_WORKING_TARGET:NotWorkingTarget={projectId:'',apiPath:'',ticketId:'',slug:'',connectionId:''};
const notWorkingTarget=signal<NotWorkingTarget>(CLOSED_NOT_WORKING_TARGET),notWorkingNote=signal(''),notWorkingFiles=signal<PendingEvidence[]>([]),notWorkingSubmitting=signal(false),notWorkingError=signal('');
let ticketSelectionAnchor: string | undefined;
const histories = new Map<string, TicketHistory>();
const mutationGenerations = new Map<string, number>();
let clipboard: { tickets: ClipboardTicket[]; cut: boolean; source: Project } | undefined;
let draggedTicketSlugs: string[] = [];
const projectChangePolls = new Map<string, () => void>();
const loading = signal(false), error = signal(''), viewMode = signal<WorkspaceViewMode>('list'), selectedView = signal<TicketView>('all'), searchOpen = signal(false), searchQuery = signal(''), searchMatchKeys = signal<Set<string>|undefined>(undefined), sort = signal<WorkspaceSort>('updated'), sortDirection = signal<WorkspaceSortDirection>(defaultWorkspaceSortDirection(sort.value));
const composerExpanded = signal(false), composerTitle = signal(''), composerCategory = signal('task'), inspectorTab = signal<InspectorTab>('info'), sidebarVisible = signal(true), inspectorVisible = signal(true);
const detailsMode = signal<MarkdownEditorMode>('preview'), detailsDraft = signal('');
const readerOpen = signal(false), readerEditing = signal(false);
const attachmentMessage = signal('');
const editingNoteId = signal<string|undefined>(undefined), noteDraft = signal('');
const composingNote = signal(false), newNoteDraft = signal('');
const blockedReasonEditing = signal(false), blockedReasonDraft = signal('');
const titleEditing = signal(false), titleDraft = signal('');
const providerCapabilities = signal<Record<string, Capabilities>>({});
const hideVerifiedByProject = signal<Record<string, boolean>>({});
function loadPermissionHistory(){try{return parsePermissionHistory(JSON.parse(localStorage.getItem('hotsheet.permission-history')||'[]'))}catch{return []}}
function loadPermissionAutomation(projectId:string){try{return parsePermissionAutomation(JSON.parse(localStorage.getItem(`hotsheet.project.${projectId}.permission-automation`)||'null'))}catch{return DEFAULT_PERMISSION_AUTOMATION}}
const storedPermissionHistory=loadPermissionHistory();
const permissionRevision=signal(0),permissionRemainingMs=signal<number|undefined>(undefined),permissionInbox=new PermissionInbox(storedPermissionHistory),permissionTimer=new VisiblePermissionTimer();
const permissionAutomationByProject=signal<Record<string,PermissionAutomation>>({});
let permissionPolling=false,permissionTimerInterval:number|undefined,autoResolvingKey:string|undefined;
const project = () => projects.value.find(item => item.id === selectedProjectId.value);
const hideVerifiedColumn = () => hideVerifiedByProject.value[selectedProjectId.value] ?? false;
const canUpdateSelected = () => selectedTicket.value ? (providerCapabilities.value[selectedTicket.value.connection_id]?.update ?? true) : false;
const noteCapabilities = () => selectedTicket.value ? providerCapabilities.value[selectedTicket.value.connection_id] : undefined;
const canAddNotes = () => noteCapabilities()?.notes ?? true;
const canEditNotes = () => noteCapabilities()?.note_edit ?? canUpdateSelected();
const canDeleteNotes = () => noteCapabilities()?.note_delete ?? canUpdateSelected();
const canUseAttachments = () => selectedTicket.value ? (providerCapabilities.value[selectedTicket.value.connection_id]?.attachments ?? true) : false;
const capabilitiesFor = (connectionId:string) => providerCapabilities.value[connectionId];
const tagSuggestions = () => [...new Set(tickets.value.flatMap(ticket => ticket.tags))];
const pendingPermissions=()=>{void permissionRevision.value;return permissionInbox.pending()};
const permissionHistory=()=>{void permissionRevision.value;return permissionInbox.history()};
const visiblePermission=()=>{void permissionRevision.value;return permissionInbox.visible()};
const permissionCount=(projectId?:string)=>pendingPermissions().filter(item=>!projectId||item.projectId===projectId).length;
const permissionAutomation=(projectId:string)=>permissionAutomationByProject.value[projectId]??DEFAULT_PERMISSION_AUTOMATION;
const persistPermissionHistory=()=>{localStorage.setItem('hotsheet.permission-history',JSON.stringify(permissionInbox.history()))};
const api = () => new Api(project()?.apiPath ?? '');
const status = (value?:string):TicketStatus => ['not_started','started','completed','verified','backlog','archive'].includes(value ?? '') ? value as TicketStatus : 'not_started';
const priority = (value?:string):TicketPriority => priorityFromWire(value);
const ticketSnapshot = (slug:string) => tickets.value.find(item=>item.slug===slug) as TicketSnapshot|undefined;
const ticketSearchKey = (ticket:WireTicketRow) => `${ticket.connection_id}:${ticket.native_id}`;
const ago = (value?:string) => { if (!value) return 'Recently'; const seconds=Math.max(0,(Date.now()-Date.parse(value))/1000); if(seconds<60)return 'Now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`; };
const row = (ticket:WireTicketRow):TicketRowProps => ({slug:ticket.slug,title:ticket.title,status:status(ticket.status),priority:priority(ticket.priority),category:ticket.category??'issue',tags:ticket.tags,upNext:ticket.up_next,upNextEligible:ticket.status==='not_started'||ticket.status==='started',feedbackNeeded:ticket.feedback_needed,blocked:ticket.blocked_by.length>0,selected:selectedTicketSlugs.value.includes(ticket.slug),cutPending:Boolean(clipboard?.cut&&clipboard.source.id===project()?.id&&clipboard.tickets.some(item=>item.slug===ticket.slug)),busy:ticket.claim_count>0,agentName:ticket.worker_label||ticket.claimed_by||'AI',updatedLabel:ago(ticket.updated_at)});

function visibleTickets(){let result=ticketsForView(tickets.value,selectedView.value);if(searchQuery.value.trim()){const matches=searchMatchKeys.value;result=matches?result.filter(ticket=>matches.has(ticketSearchKey(ticket))):[]}return result.slice().sort((a,b)=>applyWorkspaceSortDirection(sort.value==='title'?a.title.localeCompare(b.title):sort.value==='priority'?['urgent','high','default','low'].indexOf(a.priority??'default')-['urgent','high','default','low'].indexOf(b.priority??'default'):sort.value==='status'?(a.status??'').localeCompare(b.status??''):(a.updated_at??'').localeCompare(b.updated_at??''),sortDirection.value));}

let searchTimer:number|undefined,searchGeneration=0;
async function refreshTicketSearch(){const current=project(),query=searchQuery.value.trim(),generation=++searchGeneration;if(searchTimer!==undefined){window.clearTimeout(searchTimer);searchTimer=undefined}if(!current||!query){searchMatchKeys.value=undefined;return}try{const rows=await new Api(current.apiPath).checkoutTickets(current.id,query);if(generation!==searchGeneration||project()?.id!==current.id||searchQuery.value.trim()!==query)return;searchMatchKeys.value=new Set(rows.map(ticketSearchKey))}catch(reason){if(generation===searchGeneration){searchMatchKeys.value=new Set();error.value=reason instanceof Error?reason.message:String(reason)}}}
function updateTicketSearch(value:string){searchQuery.value=value;searchGeneration+=1;if(searchTimer!==undefined)window.clearTimeout(searchTimer);if(!value.trim()){searchTimer=undefined;searchMatchKeys.value=undefined;return}searchMatchKeys.value=undefined;searchTimer=window.setTimeout(()=>{searchTimer=undefined;void refreshTicketSearch()},150)}

async function refreshProject({showLoading=true}:{showLoading?:boolean}={}){const current=project();if(!current)return;if(showLoading)loading.value=true;try{const client=new Api(current.apiPath);const [index,nextRepository]=await Promise.all([loadProjectTicketRefresh(client,current.id),client.repositoryStatus(current.id).catch(()=>null)]);if(project()?.id!==current.id)return;if(index.tickets){tickets.value=index.tickets;const live=new Set(index.tickets.map(ticket=>ticket.slug)),selected=selectedTicketSlugs.value.filter(slug=>live.has(slug));if(selected.length!==selectedTicketSlugs.value.length){selectedTicketSlugs.value=selected;if(ticketSelectionAnchor&&!live.has(ticketSelectionAnchor))ticketSelectionAnchor=undefined;if(selected.length!==1)selectedTicket.value=null}}corruptTickets.value=index.corruptTickets??[];repository.value=nextRepository;error.value=[index.ticketsError,index.corruptTicketsError].filter(Boolean).join(' · ');if(selectedTicket.value&&index.tickets){const matching=index.tickets.find(item=>item.id===selectedTicket.value?.id);if(!matching){selectedTicket.value=null;return}const refreshed=(await client.checkoutTicket(current.id,matching.id)).ticket;if(project()?.id===current.id&&selectedTicketSlugs.value.includes(refreshed.slug))selectedTicket.value=refreshed}if(searchQuery.value.trim())void refreshTicketSearch()}catch(reason){if(project()?.id===current.id)error.value=reason instanceof Error?reason.message:String(reason)}finally{if(showLoading&&project()?.id===current.id)loading.value=false}}
async function preserveOpenSelects(task:()=>Promise<void>){const open=[...document.querySelectorAll<Control>('wa-select')].filter(node=>node.open).map(node=>({node,name:node.getAttribute('name')}));await task();await Promise.resolve();open.forEach(({node,name})=>{const current=node.isConnected?node:name?document.querySelector<Control>(`wa-select[name="${CSS.escape(name)}"]`):undefined;if(current&&!current.open)current.show?.()})}
function syncProjectChangePolls(){const live=new Set(projects.value.map(item=>item.id));for(const[id,stop]of projectChangePolls)if(!live.has(id)){stop();projectChangePolls.delete(id)}for(const current of projects.value)if(!projectChangePolls.has(current.id)){const stop=startProjectChangePoll({client:new Api(current.apiPath),refresh:async()=>{if(project()?.id===current.id)await preserveOpenSelects(()=>refreshProject({showLoading:false}))},onEvents:async response=>{if(response.events.some(event=>event.kind==='permission_asked'))await refreshPermissions()}});projectChangePolls.set(current.id,stop)}}
async function refreshPermissions(){if(permissionPolling)return;permissionPolling=true;try{let changed=false;await Promise.all(projects.value.map(async current=>{const client=new Api(current.apiPath);const [requests,connections]=await Promise.all([client.permissions(),client.activeToolConnections().catch(()=>[])]),owned=requests.filter(request=>{const connection=connections.find(item=>item.id===request.connection);if(!connection)return true;const owner=projects.value.find(item=>item.id===connection.project||item.root===connection.project);return !owner||owner.id===current.id});if(!autoResolvingKey?.startsWith(`${current.id}:`))changed=permissionInbox.reconcile(current,owned,connections)||changed}));if(changed){permissionRevision.value+=1;persistPermissionHistory()}}catch{/* individual server disconnects remain represented by their last known requests */}finally{permissionPolling=false}}
function startPermissionUpdates(){if(permissionTimerInterval===undefined)permissionTimerInterval=window.setInterval(updatePermissionTimer,250);void refreshPermissions()}
async function resolvePermission(item:PermissionItem,decision:PermissionDecision,scope:PermissionScope,automatic=false){if(autoResolvingKey===item.key)return;autoResolvingKey=item.key;try{const owning=projects.value.find(value=>value.id===item.projectId);if(!owning)return;await new Api(owning.apiPath).resolvePermission(item.id,decision,scope);permissionInbox.resolve(item.key,decision,scope,automatic);persistPermissionHistory();permissionTimer.remove(item.key);permissionRevision.value+=1}catch(reason){if(reason instanceof Error&&reason.message.includes('404')){await refreshPermissions()}else error.value=reason instanceof Error?reason.message:String(reason)}finally{autoResolvingKey=undefined}}
function updatePermissionTimer(){const item=visiblePermission();if(!item){permissionTimer.hide();permissionRemainingMs.value=undefined;return}const setting=permissionAutomation(item.projectId);if(setting.action==='off'){permissionTimer.hide();permissionRemainingMs.value=undefined;return}const remaining=permissionTimer.tick(item.key,setting.delayMs);permissionRemainingMs.value=remaining;if(remaining===0)void resolvePermission(item,setting.action,'once',true)}
async function applyTicketPatch(slug:string,patch:TicketPatch){const current=project(),ticket=tickets.value.find(item=>item.slug===slug);if(!current||!ticket)return false;const selectedBefore=selectedTicket.value?.slug===slug?selectedTicket.value:null,started=performance.now(),generation=(mutationGenerations.get(slug)??0)+1;mutationGenerations.set(slug,generation);tickets.value=tickets.value.map(item=>item.slug===slug?projectTicketPatch(item,patch):item);if(selectedBefore)selectedTicket.value=projectTicketPatch(selectedBefore,patch);const optimistic=performance.now()-started;try{const updated=(await api().updateCheckoutTicket(current.id,ticket.id,patch)).ticket;if(mutationGenerations.get(slug)!==generation){reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'stale'});return true}tickets.value=tickets.value.map(item=>item.slug===slug?ticketRowFromFull(item,updated):item);if(selectedTicket.value?.slug===slug)selectedTicket.value=updated;error.value='';reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'committed'});return true}catch(reason){if(mutationGenerations.get(slug)===generation){tickets.value=tickets.value.map(item=>item.slug===slug?ticket:item);if(selectedBefore&&selectedTicket.value?.slug===slug)selectedTicket.value=selectedBefore;error.value=reason instanceof Error?reason.message:String(reason);reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'rolled_back'})}return false}}
async function updateSelected(patch:Record<string,unknown>){return selectedTicket.value?applyTicketPatch(selectedTicket.value.slug,patch):false}
function history(){const id=project()?.id??'';let value=histories.get(id);if(!value){value=new TicketHistory(ticketSnapshot,applyTicketPatch);histories.set(id,value)}return value}
async function updateSelectedTracked(patch:TicketPatch){return selectedTicket.value ? history().execute(selectedTicket.value.slug,patch) : false}
const detailsAutosave=createDebouncedAutosave((value:string)=>updateSelectedTracked({details:value}));
const noteAutosave=createDebouncedAutosave(({id,value}:{id:string;value:string})=>updateSelected({note_id:id,note:value}));
const blockedReasonAutosave=createDebouncedAutosave((value:string)=>updateSelected({blocked_reason:value.trim()||null}));
const titleAutosave=createDebouncedAutosave((value:string)=>updateSelectedTracked({title:value.trim()}));
const tagsAutosave=createDebouncedAutosave((value:string[])=>updateSelectedTracked({tags:value}));
function selectedRows(){const selected=new Set(selectedTicketSlugs.value);return tickets.value.filter(ticket=>selected.has(ticket.slug))}
function clipboardTicket(ticket:FullTicket|WireTicketRow,loaded?:FullTicket):ClipboardTicket {const full='details' in ticket?ticket:loaded;return{id:ticket.id,slug:ticket.slug,connection_id:ticket.connection_id,native_id:ticket.native_id,title:ticket.title,details:full?.details??'',category:ticket.category??'issue',priority:ticket.priority,status:ticket.status,up_next:ticket.up_next,tags:ticket.tags,notes:full?.notes.map(note=>({kind:note.kind,text:note.text}))??[],attachments:full?.attachments.map(item=>({id:item.id,filename:item.filename}))??[]}}
function copySelection(cut:boolean){const current=project(),rows=selectedRows();if(!current||!rows.length)return;const snapshot={tickets:rows.map(ticket=>clipboardTicket(ticket,selectedTicket.value?.id===ticket.id?selectedTicket.value:undefined)),cut,source:current};clipboard=snapshot;selectedTicketSlugs.value=[...selectedTicketSlugs.value];void Promise.all(rows.map(ticket=>api().checkoutTicket(current.id,ticket.id).then(value=>value.ticket))).then(full=>{if(clipboard!==snapshot)return;snapshot.tickets=full.map(ticket=>clipboardTicket(ticket));const text=full.map(ticket=>[`${ticket.slug}: ${ticket.title}`,ticket.details,...ticket.notes.map(note=>`- ${note.text}`)].filter(Boolean).join('\n\n')).join('\n\n');void navigator.clipboard?.writeText(text).catch(()=>undefined)}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})}
async function patchTransferTickets(client:Api,checkout:string,changes:Array<{id:string;status:string}>){for(const change of changes)await client.updateCheckoutTicket(checkout,change.id,{status:change.status});return true}
async function pasteSelection(){const current=project(),snapshot=clipboard;if(!current||!snapshot?.tickets.length)return;const destinationApi=api(),sourceApi=new Api(snapshot.source.apiPath),titles=tickets.value.map(ticket=>ticket.title),created:Array<{id:string;slug:string;status:string}>=[];try{for(const source of snapshot.tickets){const title=deduplicateTitle(source.title,titles);titles.push(title);let ticket=await destinationApi.createCheckoutTicket(current.id,{title,details:source.details,category:source.category,priority:source.priority,status:source.status==='deleted'?'not_started':source.status,up_next:source.up_next,tags:source.tags});created.push({id:ticket.id,slug:ticket.slug,status:ticket.status??'not_started'});for(const note of source.notes)ticket=(await destinationApi.updateCheckoutTicket(current.id,ticket.id,{note:note.text,note_kind:note.kind})).ticket;for(const attachment of source.attachments)ticket=await destinationApi.copyAttachment({connection_id:source.connection_id,native_id:source.native_id,attachment_id:attachment.id},{connection_id:ticket.connection_id,native_id:ticket.native_id})}if(snapshot.cut){for(const source of snapshot.tickets)await sourceApi.updateCheckoutTicket(snapshot.source.id,source.id,{status:'deleted'});clipboard=undefined}const originals=snapshot.tickets.map(ticket=>({id:ticket.id,status:ticket.status??'not_started'}));history().recordExternal(async()=>{await patchTransferTickets(destinationApi,current.id,created.map(ticket=>({id:ticket.id,status:'deleted'})));if(snapshot.cut)await patchTransferTickets(sourceApi,snapshot.source.id,originals);await refreshProject();return true},async()=>{await patchTransferTickets(destinationApi,current.id,created.map(ticket=>({id:ticket.id,status:ticket.status})));if(snapshot.cut)await patchTransferTickets(sourceApi,snapshot.source.id,originals.map(ticket=>({id:ticket.id,status:'deleted'})));await refreshProject();return true});await refreshProject();selectedTicketSlugs.value=created.map(ticket=>ticket.slug);ticketSelectionAnchor=created[0]?.slug}catch(reason){for(const ticket of created)await destinationApi.updateCheckoutTicket(current.id,ticket.id,{status:'deleted'}).catch(()=>undefined);error.value=reason instanceof Error?reason.message:String(reason);await refreshProject()}}
function isEditableTarget(target:EventTarget|null){return target instanceof HTMLElement&&(target.matches('input, textarea, select, [contenteditable="true"]')||Boolean(target.closest('wa-dialog[open]')))}
async function openProject(root:string,ticketStore?:string,remember=true){loading.value=true;try{const response=await fetch('/__hotsheet/projects/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({root,ticketStore})});const value=await response.json() as Project&{error?:string};if(!response.ok)throw new Error(value.error||'Could not open project.');projects.value=[...projects.value.filter(item=>item.id!==value.id),value];hideVerifiedByProject.value={...hideVerifiedByProject.value,[value.id]:localStorage.getItem(`hotsheet.project.${value.id}.hide-verified-column`)==='true'};permissionAutomationByProject.value={...permissionAutomationByProject.value,[value.id]:loadPermissionAutomation(value.id)};selectedProjectId.value=value.id;if(remember)localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));(document.querySelector<Control>('[data-project-dialog]'))?.hide?.();const descriptors=await new Api(value.apiPath).providers().catch(()=>[]);providerCapabilities.value={...providerCapabilities.value,...Object.fromEntries(descriptors.map(item=>[item.connection_id,item.capabilities]))};startPermissionUpdates();syncProjectChangePolls();await refreshProject();}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
function timeline(ticket:FullTicket){return ticketTimelineEntries(ticket).map(entry=>({...entry,time:ago(entry.timestamp)}));}
function notes(ticket:FullTicket){return ticket.notes.filter(note=>note.kind!=='activity').map(note=>({id:note.id,kind:note.kind,author:'Hot Sheet',time:ago(note.created_at),body:note.text} as const));}
async function addAttachments(slug:string,files:FileList|File[]){const current=project(),ticket=tickets.value.find(item=>item.slug===slug);if(!current||!ticket||files.length===0||!canUseAttachments())return;loading.value=true;attachmentMessage.value=`Adding ${files.length} attachment${files.length===1?'':'s'}…`;try{const screened=await screenAttachmentFiles(Array.from(files));let updated:FullTicket|undefined;for(const file of screened.readable)updated=(await api().addCheckoutAttachment(current.id,ticket.id,file)).ticket;if(updated&&selectedTicket.value?.id===ticket.id)selectedTicket.value=updated;if(screened.readable.length)await refreshProject();const warning=describeUnreadableAttachments(screened.unreadable);attachmentMessage.value=warning||`${screened.readable.length} attachment${screened.readable.length===1?'':'s'} added.`;error.value=warning}catch(reason){const message=reason instanceof Error?reason.message:String(reason);attachmentMessage.value=`Attachment failed: ${message}`;error.value=message}finally{loading.value=false}}
function selectionOrder(target:Element){const column=target.closest('[data-component="ticket-board-column"]');return column?[...column.querySelectorAll<HTMLElement>('[data-action="select-ticket-row"]')].map(item=>data(item).ticketSlug!):visibleTickets().map(ticket=>ticket.slug)}
function presentTicket(ticket:FullTicket){selectedTicket.value=ticket;detailsMode.value='preview';detailsDraft.value=ticket.details;titleEditing.value=false;titleDraft.value=ticket.title;blockedReasonEditing.value=false;blockedReasonDraft.value=ticket.blocked_reason??'';inspectorVisible.value=true;error.value=''}
function cancelTicketDrafts(){detailsAutosave.cancel();noteAutosave.cancel();blockedReasonAutosave.cancel();titleAutosave.cancel();tagsAutosave.cancel()}
function selectTickets(slug:string,intent:{range?:boolean;toggle?:boolean}={},ordered=visibleTickets().map(ticket=>ticket.slug)){const next=updateTicketSelection(ordered,{anchor:ticketSelectionAnchor,selected:new Set(selectedTicketSlugs.value)},slug,intent),selected=[...next.selected];ticketSelectionAnchor=next.anchor;selectedTicketSlugs.value=selected;cancelTicketDrafts();if(selected.length!==1){selectedTicket.value=null;return Promise.resolve(undefined)}const ticket=tickets.value.find(item=>item.slug===selected[0]),current=project();if(ticket&&current)return api().checkoutTicket(current.id,ticket.id).then(result=>{if(project()?.id===current.id&&selectedTicketSlugs.value.length===1&&selectedTicketSlugs.value[0]===result.ticket.slug)presentTicket(result.ticket);return result.ticket}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason);return undefined});return Promise.resolve(undefined)}
async function openTicketReader(slug:string,ordered?:string[]){const ticket=await selectTickets(slug,{},ordered);if(!ticket)return;inspectorTab.value='info';readerEditing.value=detailsMode.value==='write';readerOpen.value=true}
function closeNotWorking(){notWorkingTarget.value=CLOSED_NOT_WORKING_TARGET;notWorkingNote.value='';notWorkingFiles.value=[];notWorkingSubmitting.value=false;notWorkingError.value=''}
function openNotWorking(ticket:WireTicketRow){const current=project();if(!current)return;notWorkingTarget.value={projectId:current.id,apiPath:current.apiPath,ticketId:ticket.id,slug:ticket.slug,connectionId:ticket.connection_id};notWorkingNote.value='';notWorkingFiles.value=[];notWorkingSubmitting.value=false;notWorkingError.value='';queueMicrotask(()=>document.querySelector<HTMLTextAreaElement>('[name="not-working-note"]')?.focus())}
async function addNotWorkingFiles(files:FileList|File[]){const target=notWorkingTarget.value;if(!target||!(capabilitiesFor(target.connectionId)?.attachments??true))return;const screened=await screenAttachmentFiles(Array.from(files));notWorkingFiles.value=[...notWorkingFiles.value,...screened.readable.map(file=>({id:crypto.randomUUID(),name:file.name,file}))];notWorkingError.value=describeUnreadableAttachments(screened.unreadable)}
async function submitNotWorking(){const target=notWorkingTarget.value;if(!target||notWorkingSubmitting.value)return;const owning=projects.value.find(item=>item.id===target.projectId);if(!owning){notWorkingError.value='The project is no longer open.';return}const client=new Api(target.apiPath),capabilities=capabilitiesFor(target.connectionId),note=(capabilities?.notes??true)?notWorkingNote.value:'';notWorkingSubmitting.value=true;notWorkingError.value='';try{let full=(await client.checkoutTicket(target.projectId,target.ticketId)).ticket;const known=new Set(full.attachments.map(item=>item.id));await submitNotWorkingReport({note,files:notWorkingFiles.value.map(item=>item.file)},{upload:async file=>{const result=await client.addCheckoutAttachment(target.projectId,target.ticketId,file);full=result.ticket;const added=full.attachments.find(item=>!known.has(item.id));if(!added)throw new Error(`The server did not identify the uploaded attachment ${file.name}.`);known.add(added.id);return added.id},removeAttachment:async id=>{full=(await client.deleteCheckoutAttachment(target.projectId,target.ticketId,id)).ticket},reopen:async text=>{full=(await client.updateCheckoutTicket(target.projectId,target.ticketId,{status:'not_started',up_next:true,...(text?{note:`Not working: ${text}`,note_kind:'regular'}:{})})).ticket}});if(project()?.id===owning.id){await refreshProject();selectedTicketSlugs.value=[target.slug];ticketSelectionAnchor=target.slug;presentTicket(full)}closeNotWorking()}catch(reason){notWorkingError.value=reason instanceof Error?reason.message:String(reason);notWorkingSubmitting.value=false}}

function ProjectDialog(){return <wa-dialog data-project-dialog label="Open project"><form class="project-dialog" data-action="open-project-form"><p>Select a code checkout. Hot Sheet automatically uses a valid sibling <code>&lt;project&gt;.hs2</code> ticket store. Override it when the project uses another store.</p><wa-input name="project-root" label="Project folder" value="/Users/westphal/Documents/hotsheet2" required></wa-input><wa-input name="ticket-store" label="Ticket store (optional)" placeholder="Automatically discover &lt;project&gt;.hs2"></wa-input><p class="project-dialog__error" role="alert">{error.value}</p><footer><wa-button appearance="plain" type="button" data-action="cancel-open-project">Cancel</wa-button><wa-button appearance="accent" type="submit">Open project</wa-button></footer></form></wa-dialog>;}
function EmptyState(){return <section class="app-empty"><h1>Open a Hot Sheet project</h1><p>Choose a code checkout to discover its ticket sources and start working.</p><wa-button appearance="accent" data-action="add-project">Open project</wa-button></section>;}
function Sidebar(){const queued=tickets.value.filter(isQueuedTicket),repo=repository.value;return <ProjectSidebar completedToday={tickets.value.filter(ticket=>ticket.completed_at?.startsWith(new Date().toISOString().slice(0,10))).length} inProgress={tickets.value.filter(ticket=>ticket.status==='started').length} completionTrend={[0,0,0,0,0,0,0]} branch={repo?.branch??'No git branch'} unpushed={repo?.ahead??0} uncommitted={(repo?.staged??0)+(repo?.unstaged??0)+(repo?.untracked??0)} views={[{id:'all',label:'Queue',count:queued.length,icon:'all'},{id:'backlog',label:'Backlog',count:tickets.value.filter(ticket=>ticket.status==='backlog').length,icon:'backlog'},{id:'archive',label:'Archive',count:tickets.value.filter(isArchivedTicket).length,icon:'archive'}]} selectedViewId={selectedView.value} commandGroupLabel="Project commands" commands={[]} commandGroupExpanded={false} driveRunning={false} driveTool="Codex" collapseControl/>;}
function NotificationInspector(){return <aside class="notification-inspector-empty" aria-label="Notification inspector"><Toolbar trailing={<ToolbarControlGroup appearance="borderless" single><button type="button" data-action="close-ticket-inspector" aria-label="Hide notification inspector" title="Hide notification inspector"><LucideIcon icon={PanelRightClose} name="panel-right-close"/></button></ToolbarControlGroup>}/></aside>}
function NotWorkingSurface({target,note,files,submitting,submissionError}:{target:NotWorkingTarget;note:string;files:PendingEvidence[];submitting:boolean;submissionError:string}){const capabilities=target.slug?capabilitiesFor(target.connectionId):undefined;return <NotWorkingDialog slug={target.slug||'ticket'} open={Boolean(target.slug)} note={note} attachments={files} notesEnabled={capabilities?.notes??true} attachmentsEnabled={capabilities?.attachments??true} submitting={submitting} error={submissionError}/>}
function InspectorPlaceholder(){const count=selectedTicketSlugs.value.length;return <aside class="ticket-inspector-placeholder" aria-label="Ticket inspector"><Toolbar trailing={<ToolbarControlGroup appearance="borderless" single><button type="button" data-action="close-ticket-inspector" aria-label="Hide ticket inspector" title="Hide ticket inspector"><LucideIcon icon={PanelRightClose} name="panel-right-close"/></button></ToolbarControlGroup>}/><p>{count===0?'Select a ticket to see and edit its details':`${count} items selected — use batch actions to edit them together`}</p></aside>}
function Inspector(){const ticket=selectedTicket.value;if(!ticket)return null;return <TicketInspector slug={ticket.slug} title={ticket.title} titleEditing={titleEditing.value} titleDraft={titleDraft.value} canUpdate={canUpdateSelected()} canAddNotes={canAddNotes()} canEditNotes={canEditNotes()} canDeleteNotes={canDeleteNotes()} composingNote={composingNote.value} composerDraft={newNoteDraft.value} status={status(ticket.status)} priority={priority(ticket.priority)} category={ticket.category??'issue'} tags={ticket.tags} tagSuggestions={tagSuggestions()} details={detailsMode.value==='write'?detailsDraft.value:ticket.details} detailsMode={detailsMode.value} detailsDirty={detailsDraft.value!==ticket.details} notes={notes(ticket)} editingNoteId={editingNoteId.value} noteDraft={noteDraft.value} blockedReason={ticket.blocked_reason} blockedReasonEditing={blockedReasonEditing.value} blockedReasonDraft={blockedReasonDraft.value} providerName="Hot Sheet git" updatedLabel={`Updated ${ago(ticket.updated_at)}`} activeTab={inspectorTab.value} upNext={ticket.up_next} upNextEligible={ticket.status==='not_started'||ticket.status==='started'} feedbackNeeded={isFeedbackNeeded(ticket.notes)} timelineEntries={timeline(ticket)} attachments={ticket.attachments.map(item=>({id:item.id,name:item.filename,size:'',kind:'file'}))} attachmentsEnabled={canUseAttachments()} attachmentMessage={attachmentMessage.value}/>;}
function Reader(){const ticket=selectedTicket.value;if(!ticket)return null;return <TicketReader slug={ticket.slug} title={ticket.title} titleEditing={titleEditing.value} titleDraft={titleDraft.value} canUpdate={canUpdateSelected()} canAddNotes={canAddNotes()} canEditNotes={canEditNotes()} canDeleteNotes={canDeleteNotes()} composingNote={composingNote.value} composerDraft={newNoteDraft.value} status={status(ticket.status)} priority={priority(ticket.priority)} category={ticket.category??'issue'} tags={ticket.tags} tagSuggestions={tagSuggestions()} details={detailsMode.value==='write'?detailsDraft.value:ticket.details} detailsMode={detailsMode.value} detailsDirty={detailsDraft.value!==ticket.details} notes={notes(ticket)} editingNoteId={editingNoteId.value} noteDraft={noteDraft.value} blockedReason={ticket.blocked_reason} blockedReasonEditing={blockedReasonEditing.value} blockedReasonDraft={blockedReasonDraft.value} providerName="Hot Sheet git" updatedLabel={`Updated ${ago(ticket.updated_at)}`} activeTab={inspectorTab.value} upNext={ticket.up_next} upNextEligible={ticket.status==='not_started'||ticket.status==='started'} feedbackNeeded={isFeedbackNeeded(ticket.notes)} timelineEntries={timeline(ticket)} attachments={ticket.attachments.map(item=>({id:item.id,name:item.filename,size:'',kind:'file'}))} attachmentsEnabled={canUseAttachments()} attachmentMessage={attachmentMessage.value} readerEditing={readerEditing.value}/>;}
function Workspace(){const shown=visibleTickets(),current=project();if(viewMode.value==='notifications')return <NotificationCenter pending={pendingPermissions()} history={permissionHistory()}/>;if(viewMode.value==='settings')return <section class="project-settings" aria-label="Project settings"><h2>Ticket sources</h2><p>This checkout uses {current?.stores.length??0} git ticket source{current?.stores.length===1?'':'s'}.</p>{current?.stores.map(store=><div class="project-settings__source"><strong>Hot Sheet git</strong><code>{store}</code></div>)}<p>External provider connections live in the ticket store’s <code>providers.json</code>. Shared and local preferences remain in <code>hotsheet-settings.json</code> and <code>hotsheet-settings.local.json</code>; they are not the provider registry.</p><h2>Permissions</h2><div class="project-settings__permission-grid"><wa-select name="permission-automation-action" label="Automatic decision" value={permissionAutomation(current!.id).action}><wa-option value="off">Off</wa-option><wa-option value="allow">Auto-allow</wa-option><wa-option value="deny">Auto-deny</wa-option></wa-select><wa-select name="permission-automation-delay" label="After visible for" value={String(permissionAutomation(current!.id).delayMs)} disabled={permissionAutomation(current!.id).action==='off'}>{PERMISSION_DELAYS.map(value=><wa-option value={String(value)}>{value<60_000?'15 seconds':`${value/60_000} minute${value===60_000?'':'s'}`}</wa-option>)}</wa-select><p>Runs only while this project's floating permission popup is visible. Ignore pauses the timer; Cancel disables it for that request.</p></div><h2>Column view</h2><label class="project-settings__option"><input type="checkbox" data-action="toggle-verified-column" checked={hideVerifiedColumn()}/> Hide Verified column <span>Verified tickets appear in Completed.</span></label></section>;if(viewMode.value==='board')return <>{corruptTickets.value.length>0&&<TicketList tickets={[]} corruptTickets={corruptTickets.value} label="Unreadable tickets"/>}<TicketBoard columns={ticketBoardGroups(shown,selectedView.value,hideVerifiedColumn()).map(group=>({...group,tickets:group.tickets.map(row)}))} label="Project board"/></>;return <TicketList tickets={shown.map(row)} corruptTickets={corruptTickets.value} label="Project tickets"/>;}
function CompatibilityBanner(){const assessment=project()?.compatibility;if(!assessment||(assessment.kind==='compatible'&&!assessment.revisionMismatch))return null;const state:ConnectionState=assessment.kind==='compatible'?'revision-mismatch':assessment.kind==='unknown'?'compatibility-unknown':assessment.kind.replaceAll('_','-') as ConnectionState;const recovery=assessment.kind==='server_too_old'&&!assessment.canRestartServer?' Safe restart is unavailable because this server cannot verify that active work will be preserved.':'';const revision=assessment.sourceStale?' The running server was built from older local source. Rebuild if needed, then restart it to pick up your latest build.':assessment.revisionMismatch?' The protocol is compatible, but this detached server was built from another revision.':'';return <ConnectionStateBanner state={state} detail={`${assessment.detail??''}${recovery}${revision}`.trim()}/>;}
function TicketContextMenu(){const menu=ticketContextMenu.value;if(!menu)return <></>;const ticket=tickets.value.find(item=>item.slug===menu.ticketSlug),slugs=selectedTicketSlugs.value.length?selectedTicketSlugs.value:[menu.ticketSlug],onlyCompleted=slugs.length===1&&ticket?.status==='completed',allCompleted=slugs.length>0&&slugs.every(slug=>tickets.value.find(item=>item.slug===slug)?.status==='completed'),capabilities=ticket?capabilitiesFor(ticket.connection_id):undefined;return <TicketRowContextMenu x={menu.x} y={menu.y} category={ticket?.category} priority={priority(ticket?.priority)} status={status(ticket?.status)} upNextEligible={slugs.every(slug=>{const value=tickets.value.find(item=>item.slug===slug)?.status;return value==='not_started'||value==='started'})} verifyAction={allCompleted&&(capabilities?.update??true)} notWorkingAction={onlyCompleted&&(capabilities?.update??true)&&((capabilities?.notes??true)||(capabilities?.attachments??true))} selectionCount={slugs.length}/>}

const appRoot=document.querySelector<HTMLElement>('#app')!;
const renderMetrics=import.meta.env.DEV?createRenderMetrics(appRoot):undefined;
if(renderMetrics)(window as typeof window&{__hotsheetRenderMetrics?:typeof renderMetrics}).__hotsheetRenderMetrics=renderMetrics;
mount(appRoot,()=>{renderMetrics?.recordPass();const permission=visiblePermission(),automation=permission?permissionAutomation(permission.projectId):DEFAULT_PERMISSION_AUTOMATION,popup=permission?<PermissionRequestPopup item={permission} countdown={permissionRemainingMs.value===undefined?undefined:formatPermissionCountdown(permissionRemainingMs.value)} countdownAction={automation.action==='off'?undefined:automation.action}/>:undefined,target=notWorkingTarget.value,selectedSlug=selectedTicketSlugs.value.length===1?selectedTicketSlugs.value[0]:undefined,selectedReady=Boolean(selectedSlug&&selectedTicket.value?.slug===selectedSlug);return <>{project()?<AppShell tabs={projects.value.map(item=>({id:item.id,name:item.name,location:'local',selected:item.id===selectedProjectId.value,notificationCount:permissionCount(item.id)}))} sidebar={<Sidebar/>} sidebarVisible={sidebarVisible.value} header={<WorkspaceIdentity projectName={project()!.name}/>} headerActions={<WorkspaceControls mode={viewMode.value} searchOpen={searchOpen.value} searchQuery={searchQuery.value} sort={sort.value} sortDirection={sortDirection.value} notificationCount={permissionCount()}/>} banner={<CompatibilityBanner/>} pageHeader={viewMode.value==='notifications'?undefined:<PageHeader title={viewMode.value==='settings'?'Project Settings':selectedView.value==='archive'?'Archive':selectedView.value==='backlog'?'Backlog':'Queue'}/>} composer={!['settings','notifications'].includes(viewMode.value)?<QuickTicketComposer expanded={composerExpanded.value} title={composerTitle.value} category={composerCategory.value} providerName="Hot Sheet git"/>:undefined} workspace={<Workspace/>} workspacePresentation={viewMode.value==='board'?'edge-to-edge':'inset'} inspector={viewMode.value==='notifications'?<NotificationInspector/>:selectedReady?<Inspector/>:<InspectorPlaceholder/>} inspectorVisible={inspectorVisible.value&&viewMode.value!=='settings'} overlay={<>{popup}<TicketContextMenu/></>}/>:<EmptyState/>}<ProjectDialog/>{target&&<NotWorkingSurface target={target} note={notWorkingNote.value} files={notWorkingFiles.value} submitting={notWorkingSubmitting.value} submissionError={notWorkingError.value}/>} {readerOpen.value&&<div class="ticket-reader-backdrop"><Reader/></div>}{loading.value&&<div class="app-loading" role="status">Loading…</div>}{error.value&&project()&&<div class="app-error" role="alert">{error.value}</div>}</>});

delegate(document.body,'click','[data-action="add-project"]',()=>{error.value='';(document.querySelector('[data-project-dialog]') as Control).show?.()});
delegate(document.body,'click','[data-action="cancel-open-project"]',()=>{(document.querySelector('[data-project-dialog]') as Control).hide?.()});
delegate(document.body,'click','[data-action="reload-client"]',()=>{window.location.reload()});
delegate(document.body,'submit','[data-action="open-project-form"]',(event,target)=>{event.preventDefault();const root=(target.querySelector('[name="project-root"]') as Control).value,store=(target.querySelector('[name="ticket-store"]') as Control).value;void openProject(root,store||undefined)});
delegate(document.body,'click','[data-action="select-project-tab"]',(_event,target)=>{selectedProjectId.value=data(target).projectId!;selectedTicket.value=null;selectedTicketSlugs.value=[];ticketSelectionAnchor=undefined;void refreshProject()});
delegate(document.body,'click','[data-action="close-project-tab"]',(_event,target)=>{projects.value=projects.value.filter(item=>item.id!==data(target).projectId);selectedProjectId.value=projects.value[0]?.id??'';localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));syncProjectChangePolls();void refreshProject()});
delegate(document.body,'click','[data-action="select-ticket-row"]',(event,target)=>{if((event.target as Element).closest('[data-action="toggle-row-up-next"]'))return;const pointer=event as MouseEvent;void selectTickets(data(target).ticketSlug!,{range:pointer.shiftKey,toggle:pointer.metaKey||pointer.ctrlKey},selectionOrder(target))});
delegate(document.body,'dblclick','[data-action="select-ticket-row"]',(event,target)=>{if((event.target as Element).closest('button, input, textarea, select, a, [contenteditable="true"]'))return;void openTicketReader(data(target).ticketSlug!,selectionOrder(target))});
delegate(document.body,'contextmenu','[data-action="select-ticket-row"]',(event,target)=>{event.preventDefault();const pointer=event as MouseEvent,slug=data(target).ticketSlug!;if(!selectedTicketSlugs.value.includes(slug))void selectTickets(slug,{},selectionOrder(target));ticketContextMenu.value={x:Math.max(8,Math.min(pointer.clientX,window.innerWidth-240)),y:Math.max(8,Math.min(pointer.clientY,window.innerHeight-390)),ticketSlug:slug}});
delegate(document.body,'click','[data-context-field]',(event,target)=>{event.stopPropagation();const menu=ticketContextMenu.value,field=data(target).contextField as 'category'|'priority'|'status'|undefined,value=data(target).contextValue;if(!menu||!field||!value)return;const slugs=selectedTicketSlugs.value.length?selectedTicketSlugs.value:[menu.ticketSlug];ticketContextMenu.value=undefined;void history().executeMany(slugs.map(slug=>({slug,patch:{[field]:value}})))});
delegate(document.body,'click','[data-context-action="Report not working"]',(event)=>{event.stopImmediatePropagation();const menu=ticketContextMenu.value;if(!menu)return;const ticket=tickets.value.find(item=>item.slug===menu.ticketSlug);ticketContextMenu.value=undefined;if(ticket)openNotWorking(ticket)});
delegate(document.body,'click','[data-context-action]',(_event,target)=>{const menu=ticketContextMenu.value;if(!menu)return;const action=data(target).contextAction,slugs=selectedTicketSlugs.value.length?selectedTicketSlugs.value:[menu.ticketSlug],ticket=tickets.value.find(item=>item.slug===menu.ticketSlug);ticketContextMenu.value=undefined;if(action==='Open ticket'){void openTicketReader(menu.ticketSlug);return}if(action==='Verify ticket'){void history().executeMany(slugs.filter(slug=>tickets.value.find(item=>item.slug===slug)?.status==='completed').map(slug=>({slug,patch:{status:'verified'}})));return}if(action==='Toggle Up Next'&&ticket){void history().executeMany(slugs.map(slug=>({slug,patch:{up_next:!ticket.up_next}})));return}if(action==='Duplicate ticket'){copySelection(false);void pasteSelection();return}if(action==='Move to Backlog'){void history().executeMany(slugs.map(slug=>({slug,patch:{status:'backlog'}})));return}if(action==='Archive ticket'){void history().executeMany(slugs.map(slug=>({slug,patch:{status:'archive'}})));return}if(action==='Delete ticket'){void history().executeMany(slugs.map(slug=>({slug,patch:{status:'deleted'}})));return}const selector=action==='Change category'?'[name="inspector-category"]':action==='Change priority'?'[name="inspector-priority"]':action==='Change status'?'[name="inspector-status"]':action==='Add tag'?'[name="ticket-tag-input"]':undefined;if(selector){inspectorVisible.value=true;queueMicrotask(()=>{const control=document.querySelector<Control>(selector);control?.focus();control?.show?.();control?.click()})}});
delegate(document.body,'input','[name="not-working-note"]',(_event,target)=>{notWorkingNote.value=(target as HTMLTextAreaElement).value});
delegate(document.body,'change','input[name="not-working-attachments"]',(_event,target)=>{const input=target as HTMLInputElement;if(input.files?.length)void addNotWorkingFiles(input.files);input.value=''});
delegate(document.body,'click','[data-action="remove-not-working-attachment"]',(_event,target)=>{const id=data(target).pendingAttachmentId;notWorkingFiles.value=notWorkingFiles.value.filter(item=>item.id!==id)});
delegate(document.body,'dragover','[data-not-working-dropzone="true"]',(event,target)=>{event.preventDefault();(target as HTMLElement).dataset.dragging='true'});
delegate(document.body,'dragleave','[data-not-working-dropzone="true"]',(_event,target)=>{delete (target as HTMLElement).dataset.dragging});
delegate(document.body,'drop','[data-not-working-dropzone="true"]',(event,target)=>{event.preventDefault();delete (target as HTMLElement).dataset.dragging;const files=(event as DragEvent).dataTransfer?.files;if(files?.length)void addNotWorkingFiles(files)});
delegate(document.body,'submit','[data-action="submit-not-working"]',(event)=>{event.preventDefault();void submitNotWorking()});
delegate(document.body,'click','[data-action="cancel-not-working"]',()=>{closeNotWorking()});
delegate(document.body,'wa-request-close','[data-component="not-working-dialog"]',(event)=>{event.preventDefault()});
delegate(document.body,'keydown','[data-action="select-ticket-row"]',(event,target)=>{const keyboard=event as KeyboardEvent,row=target as HTMLElement,slug=data(row).ticketSlug!,ordered=selectionOrder(row);if((keyboard.metaKey||keyboard.ctrlKey)&&keyboard.key.toLowerCase()==='a'){event.preventDefault();const next=selectAllTickets(visibleTickets().map(ticket=>ticket.slug));ticketSelectionAnchor=next.anchor;selectedTicketSlugs.value=[...next.selected];return}if(keyboard.key==='ArrowUp'||keyboard.key==='ArrowDown'){event.preventDefault();const next=adjacentTicketSlug(ordered,slug,keyboard.key==='ArrowDown'?1:-1);if(next){document.querySelector<HTMLElement>(`[data-ticket-slug="${next}"]`)?.focus();void selectTickets(next,{range:keyboard.shiftKey},ordered)}return}if(keyboard.key==='Enter'||keyboard.key===' '){event.preventDefault();void selectTickets(slug,{range:keyboard.shiftKey,toggle:keyboard.metaKey||keyboard.ctrlKey},ordered)}});
delegate(document.body,'click','[data-ticket-selection-root="true"]',(event)=>{const pointer=event as MouseEvent;if((event.target as Element).closest('[data-action="select-ticket-row"]')||pointer.shiftKey||pointer.metaKey||pointer.ctrlKey)return;selectedTicketSlugs.value=[];ticketSelectionAnchor=undefined;selectedTicket.value=null});
delegate(document.body,'click','[data-action="select-view"]',(_event,target)=>{selectedView.value=(data(target).itemId??'all') as TicketView});
delegate(document.body,'click','[data-action="set-view-mode"]',(_event,target)=>{viewMode.value=data(target).viewMode as WorkspaceViewMode});
delegate(document.body,'change','[name="permission-automation-action"], [name="permission-automation-delay"]',()=>{const current=project();if(!current)return;const action=(document.querySelector<Control>('[name="permission-automation-action"]')?.value??'off') as PermissionAutomation['action'],delayMs=Number(document.querySelector<Control>('[name="permission-automation-delay"]')?.value??60_000),next=parsePermissionAutomation({action,delayMs});permissionAutomationByProject.value={...permissionAutomationByProject.value,[current.id]:next};localStorage.setItem(`hotsheet.project.${current.id}.permission-automation`,JSON.stringify(next));permissionTimer.hide();permissionRemainingMs.value=undefined});
delegate(document.body,'click','[data-action="ignore-permission"]',(_event,target)=>{const key=data(target).requestKey;if(!key)return;permissionTimer.hide();permissionInbox.ignore(key);permissionRemainingMs.value=undefined;permissionRevision.value+=1});
delegate(document.body,'click','[data-action="cancel-permission-automation"]',(_event,target)=>{const key=data(target).requestKey;if(!key)return;permissionTimer.cancel(key);permissionRemainingMs.value=undefined;permissionRevision.value+=1});
delegate(document.body,'click','[data-action="resolve-permission"]',(_event,target)=>{const key=data(target).requestKey,item=pendingPermissions().find(value=>value.key===key);if(item)void resolvePermission(item,data(target).decision as PermissionDecision,data(target).scope as PermissionScope)});
delegate(document.body,'change','[data-action="toggle-verified-column"]',(_event,target)=>{const id=selectedProjectId.value;if(!id)return;const checked=(target as HTMLInputElement).checked;hideVerifiedByProject.value={...hideVerifiedByProject.value,[id]:checked};localStorage.setItem(`hotsheet.project.${id}.hide-verified-column`,String(checked));});
delegate(document.body,'click','[data-action="open-workspace-search"]',()=>{searchOpen.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="workspace-search"]')?.focus())});
delegate(document.body,'input','[name="workspace-search"]',(_event,target)=>{updateTicketSearch((target as Control).value)});
delegate(document.body,'mousedown','[data-action="clear-workspace-search"]',event=>{event.preventDefault()});
delegate(document.body,'click','[data-action="clear-workspace-search"]',()=>{updateTicketSearch('');const input=document.querySelector<Control>('[name="workspace-search"]');if(input)input.value='';queueMicrotask(()=>input?.focus())});
delegate(document.body,'focusout','[name="workspace-search"]',(_event,target)=>{if(!(target as Control).value){searchOpen.value=false;updateTicketSearch('')}});
delegate(document.body,'click','[data-sort]',(_event,target)=>{const next=nextWorkspaceSort(sort.value,sortDirection.value,data(target).sort as WorkspaceSort);sort.value=next.sort;sortDirection.value=next.direction});
delegate(document.body,'click','[data-action="expand-ticket-composer"]',()=>{composerExpanded.value=true;queueMicrotask(()=>focusQuickTicketComposerTitle(document))});
delegate(document.body,'click','[data-action="cancel-ticket-composer"]',()=>{composerExpanded.value=false;composerTitle.value=''});
delegate(document.body,'input','[name="new-ticket-title"]',(_event,target)=>{composerTitle.value=(target as Control).value});
delegate(document.body,'change','[name="new-ticket-category"]',(_event,target)=>{composerCategory.value=(target as Control).value});
delegate(document.body,'submit','[data-action="create-ticket-form"]',(event)=>{event.preventDefault();const origin=project(),title=composerTitle.value.trim();if(!origin||!title)return;const client=new Api(origin.apiPath);void client.createCheckoutTicket(origin.id,{title,category:composerCategory.value}).then(async created=>{composerExpanded.value=false;composerTitle.value='';if(project()?.id!==origin.id)return;cancelTicketDrafts();selectedTicket.value=null;await refreshProject();if(project()?.id!==origin.id)return;selectedTicketSlugs.value=[created.slug];ticketSelectionAnchor=created.slug;presentTicket(created)}).catch(reason=>{error.value=String(reason)})});
delegate(document.body,'click','[data-action="toggle-row-up-next"]',(event,target)=>{event.stopPropagation();const article=target.closest('[data-ticket-slug]') as HTMLElement,ticket=tickets.value.find(item=>item.slug===article.dataset.ticketSlug);if(ticket)void history().execute(ticket.slug,{up_next:!ticket.up_next})});
delegate(document.body,'change','input[name="ticket-attachments"]',(_event,target)=>{const input=target as HTMLInputElement,slug=input.closest<HTMLElement>('[data-ticket-slug]')?.dataset.ticketSlug??selectedTicket.value?.slug;if(slug&&input.files?.length)void addAttachments(slug,input.files);input.value=''});
delegate(document.body,'dragover','[data-attachment-drop-target="true"]',(event,target)=>{event.preventDefault();(target as HTMLElement).dataset.draggingAttachment='true'});
delegate(document.body,'dragleave','[data-attachment-drop-target="true"]',(_event,target)=>{delete (target as HTMLElement).dataset.draggingAttachment});
delegate(document.body,'drop','[data-attachment-drop-target="true"]',(event,target)=>{event.preventDefault();const element=target as HTMLElement;delete element.dataset.draggingAttachment;const slug=element.closest<HTMLElement>('[data-ticket-slug]')?.dataset.ticketSlug??selectedTicket.value?.slug,files=(event as DragEvent).dataTransfer?.files;if(slug&&files?.length)void addAttachments(slug,files)});
function selectedAttachmentUrl(id:string){const current=project(),ticket=selectedTicket.value;return current&&ticket?api().checkoutAttachmentUrl(current.id,ticket.id,id):undefined}
delegate(document.body,'click','[data-action="open-attachment"]',(_event,target)=>{const url=selectedAttachmentUrl(data(target).attachmentActionId!);if(url)window.open(url,'_blank','noopener')});
delegate(document.body,'click','[data-action="download-attachment"]',(_event,target)=>{const url=selectedAttachmentUrl(data(target).attachmentActionId!);if(!url)return;const link=document.createElement('a');link.href=url;link.download=data(target).attachmentName??'';link.click()});
delegate(document.body,'click','[data-action="copy-attachment-reference"]',(_event,target)=>{const url=selectedAttachmentUrl(data(target).attachmentActionId!);if(!url)return;void navigator.clipboard.writeText(new URL(url,location.href).href).then(()=>{attachmentMessage.value='Attachment reference copied.'}).catch(reason=>{attachmentMessage.value=`Copy failed: ${reason instanceof Error?reason.message:String(reason)}`})});
delegate(document.body,'click','[data-action="remove-attachment"]',(_event,target)=>{const current=project(),ticket=selectedTicket.value,id=data(target).attachmentActionId;if(!current||!ticket||!id||!canUseAttachments())return;attachmentMessage.value='Removing attachment…';void api().deleteCheckoutAttachment(current.id,ticket.id,id).then(result=>{selectedTicket.value=result.ticket;attachmentMessage.value='Attachment removed.';return refreshProject()}).catch(reason=>{attachmentMessage.value=`Remove failed: ${reason instanceof Error?reason.message:String(reason)}`})});
delegate(document.body,'click','[data-action="toggle-inspector-up-next"]',()=>{if(selectedTicket.value)void updateSelectedTracked({up_next:!selectedTicket.value.up_next})});
delegate(document.body,'change','[name="inspector-category"]',(_event,target)=>{void updateSelectedTracked({category:(target as Control).value})});
delegate(document.body,'change','[name="inspector-priority"]',(_event,target)=>{void updateSelectedTracked({priority:(target as Control).value})});
delegate(document.body,'change','[name="inspector-status"]',(_event,target)=>{void updateSelectedTracked({status:(target as Control).value})});
function beginTitleEdit(){if(!selectedTicket.value||!canUpdateSelected())return;titleDraft.value=selectedTicket.value.title;titleEditing.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="ticket-title"]')?.focus())}
delegate(document.body,'dblclick','[data-action="edit-ticket-title"]',()=>{beginTitleEdit()});
delegate(document.body,'keydown','[data-action="edit-ticket-title"]',(event)=>{if(!['Enter',' '].includes((event as KeyboardEvent).key))return;event.preventDefault();beginTitleEdit()});
delegate(document.body,'input','[name="ticket-title"]',(_event,target)=>{titleDraft.value=(target as HTMLInputElement).value;if(titleDraft.value.trim())titleAutosave.schedule(titleDraft.value)});
delegate(document.body,'focusout','[name="ticket-title"]',()=>{if(!titleDraft.value.trim())return;void titleAutosave.flush().then(saved=>{if(saved)titleEditing.value=false})});
function setSelectedTags(tags:string[]){if(!selectedTicket.value||!canUpdateSelected())return;selectedTicket.value={...selectedTicket.value,tags};tagsAutosave.schedule(tags)}
function addTagFromInput(target:HTMLInputElement){const next=addTicketTag(selectedTicket.value?.tags??[],target.value);target.value='';setSelectedTags(next)}
delegate(document.body,'keydown','[name="ticket-tag-input"]',(event,target)=>{const keyboard=event as KeyboardEvent;if(!['Enter',','].includes(keyboard.key))return;event.preventDefault();addTagFromInput(target as HTMLInputElement)});
delegate(document.body,'focusout','[name="ticket-tag-input"]',(_event,target)=>{if((target as HTMLInputElement).value.trim())addTagFromInput(target as HTMLInputElement);void tagsAutosave.flush()});
delegate(document.body,'wa-remove','[data-component="tag-chip"]',(_event,target)=>{const tag=data(target).tagId;if(tag)setSelectedTags(removeTicketTag(selectedTicket.value?.tags??[],tag))});
function beginDetailsEdit(){if(!selectedTicket.value)return;detailsDraft.value=selectedTicket.value.details;detailsMode.value='write';queueMicrotask(()=>document.querySelector<HTMLElement>('[name="markdown-source"]')?.focus())}
delegate(document.body,'dblclick','[data-action="edit-markdown"]',()=>{beginDetailsEdit()});
delegate(document.body,'click','[data-action="edit-markdown"]',(_event,target)=>{if(data(target).empty==='true')beginDetailsEdit()});
delegate(document.body,'keydown','[data-action="edit-markdown"]',(event)=>{const keyboard=event as KeyboardEvent;if(!['Enter',' '].includes(keyboard.key))return;event.preventDefault();beginDetailsEdit()});
delegate(document.body,'input','[name="markdown-source"]',(_event,target)=>{detailsDraft.value=(target as HTMLTextAreaElement).value;detailsAutosave.schedule(detailsDraft.value)});
delegate(document.body,'focusout','[name="markdown-source"]',(event,target)=>{const next=(event as FocusEvent).relatedTarget;if(next instanceof Node&&target.closest('[data-component="markdown-editor"]')?.contains(next))return;void detailsAutosave.flush().then(saved=>{if(saved&&!readerOpen.value)detailsMode.value='preview'})});
function beginNoteEdit(id:string){const note=selectedTicket.value?.notes.find(item=>item.id===id);if(!note)return;editingNoteId.value=id;noteDraft.value=note.kind==='feedback_needed'?'':note.text;queueMicrotask(()=>document.querySelector<HTMLElement>(`[name="note-body"][data-note-id="${id}"]`)?.focus())}
delegate(document.body,'click','[data-action="add-ticket-note"]',()=>{if(!canAddNotes())return;editingNoteId.value=undefined;composingNote.value=true;newNoteDraft.value='';queueMicrotask(()=>document.querySelector<HTMLElement>('[name="new-note-body"]')?.focus())});
delegate(document.body,'input','[name="new-note-body"]',(_event,target)=>{newNoteDraft.value=(target as HTMLTextAreaElement).value});
delegate(document.body,'click','[data-action="cancel-new-note"]',()=>{composingNote.value=false;newNoteDraft.value=''});
delegate(document.body,'submit','[data-action="create-note-form"]',(event)=>{event.preventDefault();const text=newNoteDraft.value.trim();if(!text||!canAddNotes())return;void updateSelected({note:text,note_kind:'regular'}).then(saved=>{if(saved){composingNote.value=false;newNoteDraft.value=''}})});
delegate(document.body,'dblclick','[data-edit-on-double-click="true"]',(_event,target)=>{beginNoteEdit(data(target).noteId!)});
delegate(document.body,'click','[data-action="edit-note"]',(_event,target)=>{beginNoteEdit(data(target).noteId!)});
delegate(document.body,'input','[name="note-body"]',(_event,target)=>{editingNoteId.value=data(target).noteId;noteDraft.value=(target as HTMLTextAreaElement).value;if(data(target).noteResponse!=='true'&&editingNoteId.value)noteAutosave.schedule({id:editingNoteId.value,value:noteDraft.value})});
delegate(document.body,'focusout','[name="note-body"]',(_event,target)=>{if(data(target).noteResponse==='true')return;void noteAutosave.flush().then(saved=>{if(saved){editingNoteId.value=undefined;noteDraft.value=''}})});
delegate(document.body,'click','[data-action="save-note-edit"]',(_event,target)=>{const id=editingNoteId.value??data(target).noteId,note=selectedTicket.value?.notes.find(item=>item.id===id),response=data(target).noteResponse==='true'||note?.kind==='feedback_draft';if(!id||!noteDraft.value.trim())return;const patch=response?{note:noteDraft.value,note_kind:'regular'}:{note_id:id,note:noteDraft.value};void updateSelected(patch).then(saved=>{if(saved){editingNoteId.value=undefined;noteDraft.value=''}})});
delegate(document.body,'click','[data-action="delete-note"]',(_event,target)=>{const current=project(),ticket=selectedTicket.value,noteId=data(target).noteId;if(!current||!ticket||!noteId||!canDeleteNotes())return;void api().deleteCheckoutNote(current.id,ticket.id,noteId).then(result=>{selectedTicket.value=result.ticket;editingNoteId.value=undefined;noteDraft.value='';return refreshProject()}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})});
delegate(document.body,'click','[data-action="edit-blocked-reason"]',()=>{blockedReasonDraft.value=selectedTicket.value?.blocked_reason??'';blockedReasonEditing.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="blocked-reason"]')?.focus())});
delegate(document.body,'input','[name="blocked-reason"]',(_event,target)=>{blockedReasonDraft.value=(target as HTMLTextAreaElement).value;blockedReasonAutosave.schedule(blockedReasonDraft.value)});
delegate(document.body,'focusout','[name="blocked-reason"]',()=>{void blockedReasonAutosave.flush().then(saved=>{if(saved)blockedReasonEditing.value=false})});
delegate(document.body,'click','[data-action="open-ticket-reader"]',()=>{inspectorTab.value='info';readerEditing.value=detailsMode.value==='write';readerOpen.value=true});
delegate(document.body,'click','[data-action="edit-ticket-reader"]',()=>{readerEditing.value=true;beginDetailsEdit()});
delegate(document.body,'click','[data-action="close-ticket-reader"]',()=>{readerOpen.value=false;readerEditing.value=false});
delegate(document.body,'click','[data-action="set-inspector-tab"]',(_event,target)=>{inspectorTab.value=data(target).inspectorTab as InspectorTab});
delegate(document.body,'click','[data-action="close-ticket-inspector"]',()=>{inspectorVisible.value=false});
delegate(document.body,'click','[data-action="open-ticket-inspector"]',()=>{inspectorVisible.value=true});
delegate(document.body,'click','[data-action="toggle-project-sidebar"]',()=>{sidebarVisible.value=!sidebarVisible.value});
delegate(document.body,'dragstart','[data-action="select-ticket-row"]',(event,target)=>{const slug=data(target).ticketSlug!;draggedTicketSlugs=selectedTicketSlugs.value.includes(slug)?selectedTicketSlugs.value:[slug];(event as DragEvent).dataTransfer?.setData('application/x-hotsheet-tickets',draggedTicketSlugs.join(','))});
delegate(document.body,'dragover','[data-ticket-drop-status]',(event,target)=>{event.preventDefault();(target as HTMLElement).dataset.draggingTicket='true'});
delegate(document.body,'dragleave','[data-ticket-drop-status]',(_event,target)=>{delete (target as HTMLElement).dataset.draggingTicket});
delegate(document.body,'drop','[data-ticket-drop-status]',(event,target)=>{event.preventDefault();delete (target as HTMLElement).dataset.draggingTicket;const nextStatus=data(target).ticketDropStatus;if(nextStatus)void history().executeMany(draggedTicketSlugs.map(slug=>({slug,patch:{status:nextStatus}})));draggedTicketSlugs=[]});
document.addEventListener('keydown',event=>{const command=event.metaKey||event.ctrlKey,key=event.key.toLowerCase();if(!command||isEditableTarget(event.target))return;if(key==='z'){event.preventDefault();void (event.shiftKey?history().redo():history().undo());return}if(key==='c'||key==='x'){if(!selectedTicketSlugs.value.length)return;event.preventDefault();copySelection(key==='x');return}if(key==='v'&&clipboard?.tickets.length){event.preventDefault();void pasteSelection()}},{capture:true});
document.addEventListener('pointerdown',event=>{if(ticketContextMenu.value&&!(event.target as Element).closest('.ticket-context-menu,[data-action="select-ticket-row"]'))ticketContextMenu.value=undefined});
document.addEventListener('keydown',event=>{if(event.key==='Escape')ticketContextMenu.value=undefined});
for(const root of JSON.parse(localStorage.getItem('hotsheet.open-projects')||'[]') as string[])void openProject(root,undefined,false);
