import '@awesome.me/webawesome/dist/styles/webawesome.css';
import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/dialog/dialog.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import './style.css';

import { delegate, mount, signal } from 'kerfjs';

import { Api, type Capabilities, type FullTicket, type RepositoryStatus, type TicketRow as WireTicketRow } from './api';
import { describeUnreadableAttachments, screenAttachmentFiles } from './attachment-files';
import { AppShell } from './components/app-shell';
import { ConnectionStateBanner, type ConnectionState } from './components/connection-state-banner';
import type { MarkdownEditorMode } from './components/markdown-editor';
import { PageHeader } from './components/page-header';
import { ProjectSidebar } from './components/project-sidebar';
import { QuickTicketComposer } from './components/quick-ticket-composer';
import type { TicketStatus } from './components/status-badge';
import { TicketBoard } from './components/ticket-board';
import { type InspectorTab,TicketInspector } from './components/ticket-inspector';
import { TicketList } from './components/ticket-list';
import { TicketReader } from './components/ticket-reader';
import type { TicketPriority, TicketRowProps } from './components/ticket-row';
import { adjacentTicketSlug, selectAllTickets, updateTicketSelection } from './components/ticket-selection';
import { addTicketTag, removeTicketTag } from './components/ticket-tag-editor';
import { WorkspaceControls, WorkspaceIdentity, type WorkspaceSort, type WorkspaceViewMode } from './components/workspace-header';
import { createDebouncedAutosave } from './debounced-autosave';
import { priorityFromWire } from './priority-wire';
import { ticketBoardGroups } from './ticket-board-layout';
import { type ClipboardTicket, deduplicateTitle, TicketHistory, type TicketPatch, type TicketSnapshot } from './ticket-operations';
import { projectTicketPatch, reportMutationTiming, ticketRowFromFull } from './ticket-mutation';
import { isArchivedTicket, isQueuedTicket, ticketsForView, type TicketView } from './ticket-views';
import type { CompatibilityAssessment } from './compatibility';

type Control = HTMLElement & { value:string; show?():void; hide?():void };
interface Project { id:string; root:string; name:string; stores:string[]; apiPath:string; compatibility:CompatibilityAssessment }
const data = (target: Element) => (target as HTMLElement).dataset;

const projects = signal<Project[]>([]), selectedProjectId = signal(''), tickets = signal<WireTicketRow[]>([]), selectedTicket = signal<FullTicket|null>(null), repository = signal<RepositoryStatus|null>(null);
const selectedTicketSlugs = signal<string[]>([]);
let ticketSelectionAnchor: string | undefined;
const histories = new Map<string, TicketHistory>();
const mutationGenerations = new Map<string, number>();
let clipboard: { tickets: ClipboardTicket[]; cut: boolean; source: Project } | undefined;
let draggedTicketSlugs: string[] = [];
const loading = signal(false), error = signal(''), viewMode = signal<WorkspaceViewMode>('list'), selectedView = signal<TicketView>('all'), searchOpen = signal(false), searchQuery = signal(''), sort = signal<WorkspaceSort>('updated');
const composerExpanded = signal(false), composerTitle = signal(''), composerCategory = signal('task'), inspectorTab = signal<InspectorTab>('info'), sidebarVisible = signal(true), inspectorVisible = signal(true);
const detailsMode = signal<MarkdownEditorMode>('preview'), detailsDraft = signal('');
const readerOpen = signal(false), readerEditing = signal(false);
const editingNoteId = signal<string|undefined>(undefined), noteDraft = signal('');
const composingNote = signal(false), newNoteDraft = signal('');
const blockedReasonEditing = signal(false), blockedReasonDraft = signal('');
const titleEditing = signal(false), titleDraft = signal('');
const providerCapabilities = signal<Record<string, Capabilities>>({});
const hideVerifiedByProject = signal<Record<string, boolean>>({});
const project = () => projects.value.find(item => item.id === selectedProjectId.value);
const hideVerifiedColumn = () => hideVerifiedByProject.value[selectedProjectId.value] ?? false;
const canUpdateSelected = () => selectedTicket.value ? (providerCapabilities.value[selectedTicket.value.connection_id]?.update ?? true) : false;
const noteCapabilities = () => selectedTicket.value ? providerCapabilities.value[selectedTicket.value.connection_id] : undefined;
const canAddNotes = () => noteCapabilities()?.notes ?? true;
const canEditNotes = () => noteCapabilities()?.note_edit ?? canUpdateSelected();
const canDeleteNotes = () => noteCapabilities()?.note_delete ?? canUpdateSelected();
const tagSuggestions = () => [...new Set(tickets.value.flatMap(ticket => ticket.tags))];
const api = () => new Api(project()?.apiPath ?? '');
const status = (value?:string):TicketStatus => ['not_started','started','completed','verified','backlog'].includes(value ?? '') ? value as TicketStatus : 'not_started';
const priority = (value?:string):TicketPriority => priorityFromWire(value);
const ticketSnapshot = (slug:string) => tickets.value.find(item=>item.slug===slug) as TicketSnapshot|undefined;
const ago = (value?:string) => { if (!value) return 'Recently'; const seconds=Math.max(0,(Date.now()-Date.parse(value))/1000); if(seconds<60)return 'Now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`; };
const row = (ticket:WireTicketRow):TicketRowProps => ({slug:ticket.slug,title:ticket.title,status:status(ticket.status),priority:priority(ticket.priority),category:ticket.category??'issue',tags:ticket.tags,upNext:ticket.up_next,blocked:ticket.blocked_by.length>0,selected:selectedTicketSlugs.value.includes(ticket.slug),cutPending:Boolean(clipboard?.cut&&clipboard.source.id===project()?.id&&clipboard.tickets.some(item=>item.slug===ticket.slug)),busy:ticket.claim_count>0,agentName:ticket.worker_label||ticket.claimed_by||'AI',updatedLabel:ago(ticket.updated_at)});

function visibleTickets(){let result=ticketsForView(tickets.value,selectedView.value);const query=searchQuery.value.trim().toLowerCase();if(query)result=result.filter(ticket=>`${ticket.slug} ${ticket.title} ${ticket.tags.join(' ')}`.toLowerCase().includes(query));return result.slice().sort((a,b)=>sort.value==='title'?a.title.localeCompare(b.title):sort.value==='priority'?['urgent','high','default','low'].indexOf(a.priority??'default')-['urgent','high','default','low'].indexOf(b.priority??'default'):sort.value==='status'?(a.status??'').localeCompare(b.status??''):(b.updated_at??'').localeCompare(a.updated_at??''));}

async function refreshProject(){const current=project();if(!current)return;loading.value=true;try{const client=api();const [nextTickets,nextRepository]=await Promise.all([client.checkoutTickets(current.id),client.repositoryStatus(current.id).catch(()=>null)]);tickets.value=nextTickets;repository.value=nextRepository;error.value='';if(selectedTicket.value){const matching=nextTickets.find(item=>item.id===selectedTicket.value?.id);selectedTicket.value=matching?(await client.checkoutTicket(current.id,matching.id)).ticket:null;}}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
async function applyTicketPatch(slug:string,patch:TicketPatch){const current=project(),ticket=tickets.value.find(item=>item.slug===slug);if(!current||!ticket)return false;const selectedBefore=selectedTicket.value?.slug===slug?selectedTicket.value:null,started=performance.now(),generation=(mutationGenerations.get(slug)??0)+1;mutationGenerations.set(slug,generation);tickets.value=tickets.value.map(item=>item.slug===slug?projectTicketPatch(item,patch):item);if(selectedBefore)selectedTicket.value=projectTicketPatch(selectedBefore,patch);const optimistic=performance.now()-started;try{const updated=(await api().updateCheckoutTicket(current.id,ticket.id,patch)).ticket;if(mutationGenerations.get(slug)!==generation){reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'stale'});return true}tickets.value=tickets.value.map(item=>item.slug===slug?ticketRowFromFull(item,updated):item);if(selectedTicket.value?.slug===slug)selectedTicket.value=updated;error.value='';reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'committed'});return true}catch(reason){if(mutationGenerations.get(slug)===generation){tickets.value=tickets.value.map(item=>item.slug===slug?ticket:item);if(selectedBefore&&selectedTicket.value?.slug===slug)selectedTicket.value=selectedBefore;error.value=reason instanceof Error?reason.message:String(reason);reportMutationTiming({slug,optimistic_ms:optimistic,request_ms:performance.now()-started,outcome:'rolled_back'})}return false}}
async function updateSelected(patch:Record<string,unknown>){return selectedTicket.value?applyTicketPatch(selectedTicket.value.slug,patch):false}
function history(){const id=project()?.id??'';let value=histories.get(id);if(!value){value=new TicketHistory(ticketSnapshot,applyTicketPatch);histories.set(id,value)}return value}
async function updateSelectedTracked(patch:TicketPatch){return selectedTicket.value ? history().execute(selectedTicket.value.slug,patch) : false}
const detailsAutosave=createDebouncedAutosave((value:string)=>updateSelectedTracked({details:value}));
const noteAutosave=createDebouncedAutosave(({id,value}:{id:string;value:string})=>updateSelected({note_id:id,note:value}));
const blockedReasonAutosave=createDebouncedAutosave((value:string)=>updateSelected({blocked_reason:value.trim()||null}));
const titleAutosave=createDebouncedAutosave((value:string)=>updateSelectedTracked({title:value.trim()}));
const tagsAutosave=createDebouncedAutosave((value:string[])=>updateSelectedTracked({tags:value}));
function selectedRows(){const selected=new Set(selectedTicketSlugs.value);return tickets.value.filter(ticket=>selected.has(ticket.slug))}
function copySelection(cut:boolean){const current=project(),rows=selectedRows();if(!current||!rows.length)return;const snapshot={tickets:rows.map(ticket=>{const loaded=selectedTicket.value?.id===ticket.id?selectedTicket.value:undefined;return{id:ticket.id,slug:ticket.slug,title:ticket.title,details:loaded?.details??'',category:ticket.category??'issue',priority:ticket.priority,status:ticket.status,up_next:ticket.up_next,tags:ticket.tags,notes:loaded?.notes.map(note=>({kind:note.kind,text:note.text}))??[]}}),cut,source:current};clipboard=snapshot;selectedTicketSlugs.value=[...selectedTicketSlugs.value];void Promise.all(rows.map(ticket=>api().checkoutTicket(current.id,ticket.id).then(value=>value.ticket))).then(full=>{if(clipboard!==snapshot)return;snapshot.tickets=full.map(ticket=>({id:ticket.id,slug:ticket.slug,title:ticket.title,details:ticket.details,category:ticket.category??'issue',priority:ticket.priority,status:ticket.status,up_next:ticket.up_next,tags:ticket.tags,notes:ticket.notes.map(note=>({kind:note.kind,text:note.text}))}));const text=full.map(ticket=>[`${ticket.slug}: ${ticket.title}`,ticket.details,...ticket.notes.map(note=>`- ${note.text}`)].filter(Boolean).join('\n\n')).join('\n\n');void navigator.clipboard?.writeText(text).catch(()=>undefined)}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})}
async function pasteSelection(){const current=project(),snapshot=clipboard;if(!current||!snapshot?.tickets.length)return;const titles=tickets.value.map(ticket=>ticket.title),created:string[]=[];for(const source of snapshot.tickets){const title=deduplicateTitle(source.title,titles);titles.push(title);let ticket=await api().createCheckoutTicket(current.id,{title,details:source.details,category:source.category,priority:source.priority,status:source.status==='deleted'?'not_started':source.status,up_next:source.up_next,tags:source.tags});for(const note of source.notes)ticket=(await api().updateCheckoutTicket(current.id,ticket.id,{note:note.text,note_kind:note.kind})).ticket;created.push(ticket.slug)}if(snapshot.cut){const sourceApi=new Api(snapshot.source.apiPath);for(const source of snapshot.tickets)await sourceApi.updateCheckoutTicket(snapshot.source.id,source.id,{status:'deleted'});clipboard=undefined}await refreshProject();selectedTicketSlugs.value=created;ticketSelectionAnchor=created[0]}
function isEditableTarget(target:EventTarget|null){return target instanceof HTMLElement&&(target.matches('input, textarea, select, [contenteditable="true"]')||Boolean(target.closest('wa-dialog[open]')))}
async function openProject(root:string,ticketStore?:string,remember=true){loading.value=true;try{const response=await fetch('/__hotsheet/projects/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({root,ticketStore})});const value=await response.json() as Project&{error?:string};if(!response.ok)throw new Error(value.error||'Could not open project.');projects.value=[...projects.value.filter(item=>item.id!==value.id),value];hideVerifiedByProject.value={...hideVerifiedByProject.value,[value.id]:localStorage.getItem(`hotsheet.project.${value.id}.hide-verified-column`)==='true'};selectedProjectId.value=value.id;if(remember)localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));(document.querySelector<Control>('[data-project-dialog]'))?.hide?.();const descriptors=await new Api(value.apiPath).providers().catch(()=>[]);providerCapabilities.value={...providerCapabilities.value,...Object.fromEntries(descriptors.map(item=>[item.connection_id,item.capabilities]))};await refreshProject();}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
function timeline(ticket:FullTicket){return ticket.notes.filter(note=>note.kind==='activity'||note.kind==='status').map(note=>{const [title,...rest]=note.text.split('\n');return{id:note.id,time:ago(note.created_at),title:title||'Ticket updated',subtitle:rest.join('\n').trim()||undefined,emphasized:note.kind==='status'};});}
function notes(ticket:FullTicket){return ticket.notes.filter(note=>note.kind!=='activity').map(note=>({id:note.id,kind:note.kind,author:'Hot Sheet',time:ago(note.created_at),body:note.text} as const));}
async function addAttachments(slug:string,files:FileList|File[]){const current=project(),ticket=tickets.value.find(item=>item.slug===slug);if(!current||!ticket||files.length===0)return;loading.value=true;try{const screened=await screenAttachmentFiles(Array.from(files));let updated:FullTicket|undefined;for(const file of screened.readable)updated=(await api().addCheckoutAttachment(current.id,ticket.id,file)).ticket;if(updated&&selectedTicket.value?.id===ticket.id)selectedTicket.value=updated;if(screened.readable.length)await refreshProject();error.value=describeUnreadableAttachments(screened.unreadable)}catch(reason){error.value=reason instanceof Error?reason.message:String(reason)}finally{loading.value=false}}
function selectTickets(slug:string,intent:{range?:boolean;toggle?:boolean}={}){const ordered=visibleTickets().map(ticket=>ticket.slug),next=updateTicketSelection(ordered,{anchor:ticketSelectionAnchor,selected:new Set(selectedTicketSlugs.value)},slug,intent);ticketSelectionAnchor=next.anchor;selectedTicketSlugs.value=[...next.selected];const ticket=tickets.value.find(item=>item.slug===slug);if(ticket&&project()){detailsAutosave.cancel();noteAutosave.cancel();blockedReasonAutosave.cancel();titleAutosave.cancel();tagsAutosave.cancel();void api().checkoutTicket(project()!.id,ticket.id).then(result=>{selectedTicket.value=result.ticket;detailsMode.value='preview';detailsDraft.value=result.ticket.details;titleEditing.value=false;titleDraft.value=result.ticket.title;blockedReasonEditing.value=false;blockedReasonDraft.value=result.ticket.blocked_reason??'';inspectorVisible.value=true;error.value=''}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})}}

function ProjectDialog(){return <wa-dialog data-project-dialog label="Open project"><form class="project-dialog" data-action="open-project-form"><p>Select a code checkout. Hot Sheet automatically uses a valid sibling <code>&lt;project&gt;.hs2</code> ticket store. Override it when the project uses another store.</p><wa-input name="project-root" label="Project folder" value="/Users/westphal/Documents/hotsheet2" required></wa-input><wa-input name="ticket-store" label="Ticket store (optional)" placeholder="Automatically discover &lt;project&gt;.hs2"></wa-input><p class="project-dialog__error" role="alert">{error.value}</p><footer><wa-button appearance="plain" type="button" data-action="cancel-open-project">Cancel</wa-button><wa-button appearance="accent" type="submit">Open project</wa-button></footer></form></wa-dialog>;}
function EmptyState(){return <section class="app-empty"><h1>Open a Hot Sheet project</h1><p>Choose a code checkout to discover its ticket sources and start working.</p><wa-button appearance="accent" data-action="add-project">Open project</wa-button></section>;}
function Sidebar(){const queued=tickets.value.filter(isQueuedTicket),repo=repository.value;return <ProjectSidebar completedToday={tickets.value.filter(ticket=>ticket.completed_at?.startsWith(new Date().toISOString().slice(0,10))).length} inProgress={tickets.value.filter(ticket=>ticket.status==='started').length} completionTrend={[0,0,0,0,0,0,0]} branch={repo?.branch??'No git branch'} unpushed={repo?.ahead??0} uncommitted={(repo?.staged??0)+(repo?.unstaged??0)+(repo?.untracked??0)} views={[{id:'all',label:'Queue',count:queued.length,icon:'all'},{id:'backlog',label:'Backlog',count:tickets.value.filter(ticket=>ticket.status==='backlog').length,icon:'backlog'},{id:'archive',label:'Archive',count:tickets.value.filter(isArchivedTicket).length,icon:'archive'}]} selectedViewId={selectedView.value} commandGroupLabel="Project commands" commands={[]} commandGroupExpanded={false} driveRunning={false} driveTool="Codex" collapseControl/>;}
function Inspector(){const ticket=selectedTicket.value;if(!ticket)return null;return <TicketInspector slug={ticket.slug} title={ticket.title} titleEditing={titleEditing.value} titleDraft={titleDraft.value} canUpdate={canUpdateSelected()} canAddNotes={canAddNotes()} canEditNotes={canEditNotes()} canDeleteNotes={canDeleteNotes()} composingNote={composingNote.value} composerDraft={newNoteDraft.value} status={status(ticket.status)} priority={priority(ticket.priority)} category={ticket.category??'issue'} tags={ticket.tags} tagSuggestions={tagSuggestions()} details={detailsMode.value==='write'?detailsDraft.value:ticket.details} detailsMode={detailsMode.value} detailsDirty={detailsDraft.value!==ticket.details} notes={notes(ticket)} editingNoteId={editingNoteId.value} noteDraft={noteDraft.value} blockedReason={ticket.blocked_reason} blockedReasonEditing={blockedReasonEditing.value} blockedReasonDraft={blockedReasonDraft.value} providerName="Hot Sheet git" updatedLabel={`Updated ${ago(ticket.updated_at)}`} activeTab={inspectorTab.value} upNext={ticket.up_next} timelineEntries={timeline(ticket)} attachments={ticket.attachments.map(item=>({id:item.id,name:item.filename,size:'',kind:'file'}))}/>;}
function Reader(){const ticket=selectedTicket.value;if(!ticket)return null;return <TicketReader slug={ticket.slug} title={ticket.title} titleEditing={titleEditing.value} titleDraft={titleDraft.value} canUpdate={canUpdateSelected()} canAddNotes={canAddNotes()} canEditNotes={canEditNotes()} canDeleteNotes={canDeleteNotes()} composingNote={composingNote.value} composerDraft={newNoteDraft.value} status={status(ticket.status)} priority={priority(ticket.priority)} category={ticket.category??'issue'} tags={ticket.tags} tagSuggestions={tagSuggestions()} details={detailsMode.value==='write'?detailsDraft.value:ticket.details} detailsMode={detailsMode.value} detailsDirty={detailsDraft.value!==ticket.details} notes={notes(ticket)} editingNoteId={editingNoteId.value} noteDraft={noteDraft.value} blockedReason={ticket.blocked_reason} blockedReasonEditing={blockedReasonEditing.value} blockedReasonDraft={blockedReasonDraft.value} providerName="Hot Sheet git" updatedLabel={`Updated ${ago(ticket.updated_at)}`} activeTab={inspectorTab.value} upNext={ticket.up_next} timelineEntries={timeline(ticket)} attachments={ticket.attachments.map(item=>({id:item.id,name:item.filename,size:'',kind:'file'}))} readerEditing={readerEditing.value}/>;}
function Workspace(){const shown=visibleTickets();if(viewMode.value==='settings')return <section class="project-settings" aria-label="Project settings"><h2>Ticket sources</h2><p>This checkout uses {project()?.stores.length??0} git ticket source{project()?.stores.length===1?'':'s'}.</p>{project()?.stores.map(store=><div class="project-settings__source"><strong>Hot Sheet git</strong><code>{store}</code></div>)}<p>External provider connections live in the ticket store’s <code>providers.json</code>. Shared and local preferences remain in <code>hotsheet-settings.json</code> and <code>hotsheet-settings.local.json</code>; they are not the provider registry.</p><h2>Column view</h2><label class="project-settings__option"><input type="checkbox" data-action="toggle-verified-column" checked={hideVerifiedColumn()}/> Hide Verified column <span>Verified tickets appear in Completed.</span></label></section>;if(viewMode.value==='board')return <TicketBoard columns={ticketBoardGroups(shown,selectedView.value,hideVerifiedColumn()).map(group=>({...group,tickets:group.tickets.map(row)}))} label="Project board"/>;return <TicketList tickets={shown.map(row)} label="Project tickets"/>;}
function CompatibilityBanner(){const assessment=project()?.compatibility;if(!assessment||(assessment.kind==='compatible'&&!assessment.revisionMismatch))return null;const state:ConnectionState=assessment.kind==='compatible'?'revision-mismatch':assessment.kind==='unknown'?'compatibility-unknown':assessment.kind.replaceAll('_','-') as ConnectionState;const recovery=assessment.kind==='server_too_old'&&!assessment.canRestartServer?' Safe restart is unavailable because this server cannot verify that active work will be preserved.':'';const revision=assessment.revisionMismatch?' The protocol is compatible, but this detached server was built from another revision.':'';return <ConnectionStateBanner state={state} detail={`${assessment.detail??''}${recovery}${revision}`.trim()}/>;}

mount(document.querySelector('#app')!,()=> <>{project()?<AppShell tabs={projects.value.map(item=>({id:item.id,name:item.name,location:'local',selected:item.id===selectedProjectId.value}))} sidebar={<Sidebar/>} sidebarVisible={sidebarVisible.value} header={<WorkspaceIdentity projectName={project()!.name}/>} headerActions={<WorkspaceControls mode={viewMode.value} searchOpen={searchOpen.value} searchQuery={searchQuery.value} sort={sort.value}/>} banner={<CompatibilityBanner/>} pageHeader={<PageHeader title={selectedView.value==='archive'?'Archive':selectedView.value==='backlog'?'Backlog':'Queue'}/>} composer={viewMode.value!=='settings'?<QuickTicketComposer expanded={composerExpanded.value} title={composerTitle.value} category={composerCategory.value} providerName="Hot Sheet git"/>:undefined} workspace={<Workspace/>} workspacePresentation={viewMode.value==='board'?'edge-to-edge':'inset'} inspector={<Inspector/>} inspectorVisible={inspectorVisible.value&&viewMode.value!=='settings'}/>:<EmptyState/>}<ProjectDialog/>{readerOpen.value&&<div class="ticket-reader-backdrop"><Reader/></div>}{loading.value&&<div class="app-loading" role="status">Loading…</div>}{error.value&&project()&&<div class="app-error" role="alert">{error.value}</div>}</>);

delegate(document.body,'click','[data-action="add-project"]',()=>{error.value='';(document.querySelector('[data-project-dialog]') as Control).show?.()});
delegate(document.body,'click','[data-action="cancel-open-project"]',()=>{(document.querySelector('[data-project-dialog]') as Control).hide?.()});
delegate(document.body,'click','[data-action="reload-client"]',()=>{window.location.reload()});
delegate(document.body,'submit','[data-action="open-project-form"]',(event,target)=>{event.preventDefault();const root=(target.querySelector('[name="project-root"]') as Control).value,store=(target.querySelector('[name="ticket-store"]') as Control).value;void openProject(root,store||undefined)});
delegate(document.body,'click','[data-action="select-project-tab"]',(_event,target)=>{selectedProjectId.value=data(target).projectId!;selectedTicket.value=null;selectedTicketSlugs.value=[];ticketSelectionAnchor=undefined;void refreshProject()});
delegate(document.body,'click','[data-action="close-project-tab"]',(_event,target)=>{projects.value=projects.value.filter(item=>item.id!==data(target).projectId);selectedProjectId.value=projects.value[0]?.id??'';localStorage.setItem('hotsheet.open-projects',JSON.stringify(projects.value.map(item=>item.root)));void refreshProject()});
delegate(document.body,'click','[data-action="select-ticket-row"]',(event,target)=>{if((event.target as Element).closest('[data-action="toggle-row-up-next"]'))return;const pointer=event as MouseEvent;selectTickets(data(target).ticketSlug!,{range:pointer.shiftKey,toggle:pointer.metaKey||pointer.ctrlKey})});
delegate(document.body,'keydown','[data-action="select-ticket-row"]',(event,target)=>{const keyboard=event as KeyboardEvent,row=target as HTMLElement,slug=data(row).ticketSlug!;if((keyboard.metaKey||keyboard.ctrlKey)&&keyboard.key.toLowerCase()==='a'){event.preventDefault();const next=selectAllTickets(visibleTickets().map(ticket=>ticket.slug));ticketSelectionAnchor=next.anchor;selectedTicketSlugs.value=[...next.selected];return}if(keyboard.key==='ArrowUp'||keyboard.key==='ArrowDown'){event.preventDefault();const ordered=visibleTickets().map(ticket=>ticket.slug),next=adjacentTicketSlug(ordered,slug,keyboard.key==='ArrowDown'?1:-1);if(next){document.querySelector<HTMLElement>(`[data-ticket-slug="${next}"]`)?.focus();selectTickets(next,{range:keyboard.shiftKey})}return}if(keyboard.key==='Enter'||keyboard.key===' '){event.preventDefault();selectTickets(slug,{range:keyboard.shiftKey,toggle:keyboard.metaKey||keyboard.ctrlKey})}});
delegate(document.body,'click','[data-action="select-view"]',(_event,target)=>{selectedView.value=(data(target).itemId??'all') as TicketView});
delegate(document.body,'click','[data-action="set-view-mode"]',(_event,target)=>{viewMode.value=data(target).viewMode as WorkspaceViewMode});
delegate(document.body,'change','[data-action="toggle-verified-column"]',(_event,target)=>{const id=selectedProjectId.value;if(!id)return;const checked=(target as HTMLInputElement).checked;hideVerifiedByProject.value={...hideVerifiedByProject.value,[id]:checked};localStorage.setItem(`hotsheet.project.${id}.hide-verified-column`,String(checked));});
delegate(document.body,'click','[data-action="open-workspace-search"]',()=>{searchOpen.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="workspace-search"]')?.focus())});
delegate(document.body,'input','[name="workspace-search"]',(_event,target)=>{searchQuery.value=(target as Control).value});
delegate(document.body,'focusout','[name="workspace-search"]',(_event,target)=>{if(!(target as Control).value){searchOpen.value=false;searchQuery.value=''}});
delegate(document.body,'click','[data-sort]',(_event,target)=>{sort.value=data(target).sort as WorkspaceSort});
delegate(document.body,'click','[data-action="expand-ticket-composer"]',()=>{composerExpanded.value=true});
delegate(document.body,'click','[data-action="cancel-ticket-composer"]',()=>{composerExpanded.value=false;composerTitle.value=''});
delegate(document.body,'input','[name="new-ticket-title"]',(_event,target)=>{composerTitle.value=(target as Control).value});
delegate(document.body,'change','[name="new-ticket-category"]',(_event,target)=>{composerCategory.value=(target as Control).value});
delegate(document.body,'submit','[data-action="create-ticket-form"]',(event)=>{event.preventDefault();if(!project()||!composerTitle.value.trim())return;void api().createCheckoutTicket(project()!.id,{title:composerTitle.value.trim(),category:composerCategory.value}).then(()=>{composerExpanded.value=false;composerTitle.value='';return refreshProject()}).catch(reason=>{error.value=String(reason)})});
delegate(document.body,'click','[data-action="toggle-row-up-next"]',(event,target)=>{event.stopPropagation();const article=target.closest('[data-ticket-slug]') as HTMLElement,ticket=tickets.value.find(item=>item.slug===article.dataset.ticketSlug);if(ticket)void history().execute(ticket.slug,{up_next:!ticket.up_next})});
delegate(document.body,'change','input[name="ticket-attachments"]',(_event,target)=>{const input=target as HTMLInputElement,slug=input.closest<HTMLElement>('[data-ticket-slug]')?.dataset.ticketSlug??selectedTicket.value?.slug;if(slug&&input.files?.length)void addAttachments(slug,input.files);input.value=''});
delegate(document.body,'dragover','[data-attachment-drop-target="true"]',(event,target)=>{event.preventDefault();(target as HTMLElement).dataset.draggingAttachment='true'});
delegate(document.body,'dragleave','[data-attachment-drop-target="true"]',(_event,target)=>{delete (target as HTMLElement).dataset.draggingAttachment});
delegate(document.body,'drop','[data-attachment-drop-target="true"]',(event,target)=>{event.preventDefault();const element=target as HTMLElement;delete element.dataset.draggingAttachment;const slug=element.closest<HTMLElement>('[data-ticket-slug]')?.dataset.ticketSlug??selectedTicket.value?.slug,files=(event as DragEvent).dataTransfer?.files;if(slug&&files?.length)void addAttachments(slug,files)});
delegate(document.body,'click','[data-action="toggle-inspector-up-next"]',()=>{if(selectedTicket.value)void updateSelectedTracked({up_next:!selectedTicket.value.up_next})});
delegate(document.body,'change','[name="inspector-category"]',(_event,target)=>{void updateSelectedTracked({category:(target as Control).value})});
delegate(document.body,'change','[name="inspector-priority"]',(_event,target)=>{void updateSelectedTracked({priority:(target as Control).value})});
delegate(document.body,'click','[data-inspector-status]',(_event,target)=>{void updateSelectedTracked({status:data(target).inspectorStatus})});
function beginTitleEdit(){if(!selectedTicket.value||!canUpdateSelected())return;titleDraft.value=selectedTicket.value.title;titleEditing.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="ticket-title"]')?.focus())}
delegate(document.body,'dblclick','[data-action="edit-ticket-title"]',()=>{beginTitleEdit()});
delegate(document.body,'keydown','[data-action="edit-ticket-title"]',(event)=>{if(!['Enter',' '].includes((event as KeyboardEvent).key))return;event.preventDefault();beginTitleEdit()});
delegate(document.body,'input','[name="ticket-title"]',(_event,target)=>{titleDraft.value=(target as HTMLInputElement).value;if(titleDraft.value.trim())titleAutosave.schedule(titleDraft.value)});
delegate(document.body,'focusout','[name="ticket-title"]',()=>{if(!titleDraft.value.trim())return;void titleAutosave.flush().then(saved=>{if(saved)titleEditing.value=false})});
function setSelectedTags(tags:string[]){if(!selectedTicket.value||!canUpdateSelected())return;selectedTicket.value={...selectedTicket.value,tags};tagsAutosave.schedule(tags)}
function addTagFromInput(target:HTMLInputElement){const next=addTicketTag(selectedTicket.value?.tags??[],target.value);target.value='';setSelectedTags(next)}
delegate(document.body,'keydown','[name="ticket-tag-input"]',(event,target)=>{const keyboard=event as KeyboardEvent;if(!['Enter',','].includes(keyboard.key))return;event.preventDefault();addTagFromInput(target as HTMLInputElement)});
delegate(document.body,'focusout','[name="ticket-tag-input"]',(_event,target)=>{if((target as HTMLInputElement).value.trim())addTagFromInput(target as HTMLInputElement);void tagsAutosave.flush()});
delegate(document.body,'wa-remove','[data-component="tag-chip"]',(_event,target)=>{const tag=data(target).tagId;if(tag)setSelectedTags(removeTicketTag(selectedTicket.value?.tags??[],tag))});
function beginDetailsEdit(){if(!selectedTicket.value)return;detailsDraft.value=selectedTicket.value.details;detailsMode.value='write';queueMicrotask(()=>document.querySelector<HTMLElement>('[name="markdown-source"]')?.focus())}
delegate(document.body,'dblclick','[data-action="edit-markdown"]',()=>{beginDetailsEdit()});
delegate(document.body,'click','[data-action="edit-markdown"]',(_event,target)=>{if(data(target).empty==='true')beginDetailsEdit()});
delegate(document.body,'keydown','[data-action="edit-markdown"]',(event)=>{const keyboard=event as KeyboardEvent;if(!['Enter',' '].includes(keyboard.key))return;event.preventDefault();beginDetailsEdit()});
delegate(document.body,'input','[name="markdown-source"]',(_event,target)=>{detailsDraft.value=(target as HTMLTextAreaElement).value;detailsAutosave.schedule(detailsDraft.value)});
delegate(document.body,'focusout','[name="markdown-source"]',(event,target)=>{const next=(event as FocusEvent).relatedTarget;if(next instanceof Node&&target.closest('[data-component="markdown-editor"]')?.contains(next))return;void detailsAutosave.flush().then(saved=>{if(saved)detailsMode.value='preview'})});
function beginNoteEdit(id:string){const note=selectedTicket.value?.notes.find(item=>item.id===id);if(!note)return;editingNoteId.value=id;noteDraft.value=note.kind==='feedback_needed'?'':note.text;queueMicrotask(()=>document.querySelector<HTMLElement>(`[name="note-body"][data-note-id="${id}"]`)?.focus())}
delegate(document.body,'click','[data-action="add-ticket-note"]',()=>{if(!canAddNotes())return;editingNoteId.value=undefined;composingNote.value=true;newNoteDraft.value='';queueMicrotask(()=>document.querySelector<HTMLElement>('[name="new-note-body"]')?.focus())});
delegate(document.body,'input','[name="new-note-body"]',(_event,target)=>{newNoteDraft.value=(target as HTMLTextAreaElement).value});
delegate(document.body,'click','[data-action="cancel-new-note"]',()=>{composingNote.value=false;newNoteDraft.value=''});
delegate(document.body,'submit','[data-action="create-note-form"]',(event)=>{event.preventDefault();const text=newNoteDraft.value.trim();if(!text||!canAddNotes())return;void updateSelected({note:text,note_kind:'regular'}).then(saved=>{if(saved){composingNote.value=false;newNoteDraft.value=''}})});
delegate(document.body,'dblclick','[data-edit-on-double-click="true"]',(_event,target)=>{beginNoteEdit(data(target).noteId!)});
delegate(document.body,'click','[data-action="edit-note"]',(_event,target)=>{beginNoteEdit(data(target).noteId!)});
delegate(document.body,'input','[name="note-body"]',(_event,target)=>{editingNoteId.value=data(target).noteId;noteDraft.value=(target as HTMLTextAreaElement).value;if(data(target).noteResponse!=='true'&&editingNoteId.value)noteAutosave.schedule({id:editingNoteId.value,value:noteDraft.value})});
delegate(document.body,'focusout','[name="note-body"]',(_event,target)=>{if(data(target).noteResponse==='true')return;void noteAutosave.flush().then(saved=>{if(saved){editingNoteId.value=undefined;noteDraft.value=''}})});
delegate(document.body,'click','[data-action="save-note-edit"]',(_event,target)=>{const id=editingNoteId.value??data(target).noteId,note=selectedTicket.value?.notes.find(item=>item.id===id),response=data(target).noteResponse==='true'||note?.kind==='feedback_draft';if(!id||!noteDraft.value.trim())return;const patch=response?{note:noteDraft.value,note_kind:'regular'}:{note_id:id,note:noteDraft.value};void updateSelected(patch).then(saved=>{if(saved){editingNoteId.value=undefined;noteDraft.value=''}})});
delegate(document.body,'click','[data-action="delete-note"]',(_event,target)=>{const current=project(),ticket=selectedTicket.value,noteId=data(target).noteId;if(!current||!ticket||!noteId||!canDeleteNotes())return;void api().deleteCheckoutNote(current.id,ticket.id,noteId).then(result=>{selectedTicket.value=result.ticket;editingNoteId.value=undefined;noteDraft.value='';return refreshProject()}).catch(reason=>{error.value=reason instanceof Error?reason.message:String(reason)})});
delegate(document.body,'click','[data-action="edit-blocked-reason"]',()=>{blockedReasonDraft.value=selectedTicket.value?.blocked_reason??'';blockedReasonEditing.value=true;queueMicrotask(()=>document.querySelector<HTMLElement>('[name="blocked-reason"]')?.focus())});
delegate(document.body,'input','[name="blocked-reason"]',(_event,target)=>{blockedReasonDraft.value=(target as HTMLTextAreaElement).value;blockedReasonAutosave.schedule(blockedReasonDraft.value)});
delegate(document.body,'focusout','[name="blocked-reason"]',()=>{void blockedReasonAutosave.flush().then(saved=>{if(saved)blockedReasonEditing.value=false})});
delegate(document.body,'click','[data-action="open-ticket-reader"]',()=>{inspectorTab.value='info';readerEditing.value=detailsMode.value==='write';readerOpen.value=true});
delegate(document.body,'click','[data-action="edit-ticket-reader"]',()=>{readerEditing.value=true;beginDetailsEdit()});
delegate(document.body,'click','[data-action="close-ticket-reader"]',()=>{readerOpen.value=false;readerEditing.value=false});
delegate(document.body,'click','[data-action="set-inspector-tab"]',(_event,target)=>{inspectorTab.value=data(target).inspectorTab as InspectorTab});
delegate(document.body,'click','[data-action="close-ticket-inspector"]',()=>{inspectorVisible.value=false});
delegate(document.body,'click','[data-action="open-ticket-inspector"]',()=>{inspectorVisible.value=true});
delegate(document.body,'click','[data-action="toggle-project-sidebar"]',()=>{sidebarVisible.value=!sidebarVisible.value});
delegate(document.body,'dragstart','[data-action="select-ticket-row"]',(event,target)=>{const slug=data(target).ticketSlug!;draggedTicketSlugs=selectedTicketSlugs.value.includes(slug)?selectedTicketSlugs.value:[slug];(event as DragEvent).dataTransfer?.setData('application/x-hotsheet-tickets',draggedTicketSlugs.join(','))});
delegate(document.body,'dragover','[data-ticket-drop-status]',(event,target)=>{event.preventDefault();(target as HTMLElement).dataset.draggingTicket='true'});
delegate(document.body,'dragleave','[data-ticket-drop-status]',(_event,target)=>{delete (target as HTMLElement).dataset.draggingTicket});
delegate(document.body,'drop','[data-ticket-drop-status]',(event,target)=>{event.preventDefault();delete (target as HTMLElement).dataset.draggingTicket;const nextStatus=data(target).ticketDropStatus;if(nextStatus)void history().executeMany(draggedTicketSlugs.map(slug=>({slug,patch:{status:nextStatus}})));draggedTicketSlugs=[]});
document.addEventListener('keydown',event=>{const command=event.metaKey||event.ctrlKey,key=event.key.toLowerCase();if(!command||isEditableTarget(event.target))return;if(key==='z'){event.preventDefault();void (event.shiftKey?history().redo():history().undo());return}if(key==='c'||key==='x'){if(!selectedTicketSlugs.value.length)return;event.preventDefault();copySelection(key==='x');return}if(key==='v'&&clipboard?.tickets.length){event.preventDefault();void pasteSelection()}});
for(const root of JSON.parse(localStorage.getItem('hotsheet.open-projects')||'[]') as string[])void openProject(root,undefined,false);
