import { describe,expect,it } from 'vitest';

import { activeTerminalVisibilityGroup,addTerminalVisibilityGroup,DEFAULT_TERMINAL_VISIBILITY_GROUP_ID,hideNewTerminalInNamedGroups,initialTerminalVisibilityState,parseTerminalVisibilityState,removeTerminalVisibilityGroup,renameTerminalVisibilityGroup,selectTerminalVisibilityGroup,setAllTerminalsVisibleInGroup,setTerminalVisibleInGroup } from './terminal-visibility';

describe('terminal visibility groups',()=>{
  it('parses persisted groups tolerantly and restores invalid scopes to Default',()=>{const parsed=parseTerminalVisibilityState(JSON.stringify({groups:[{id:'focus',name:' Focus ',hiddenKeys:['project:a','project:a',3]}],activeByScope:{dashboard:'missing','project:p':'focus'}}));expect(parsed.groups.map(group=>group.id)).toEqual(['default','focus']);expect(parsed.groups[1]).toMatchObject({name:'Focus',hiddenKeys:['project:a']});expect(activeTerminalVisibilityGroup(parsed,'dashboard').id).toBe(DEFAULT_TERMINAL_VISIBILITY_GROUP_ID);expect(activeTerminalVisibilityGroup(parsed,'project:p').id).toBe('focus');expect(parseTerminalVisibilityState('{')).toEqual(initialTerminalVisibilityState())});
  it('creates, selects, renames, and removes named groups without mutating Default',()=>{let state=initialTerminalVisibilityState();const added=addTerminalVisibilityGroup(state,'focus',' Focus ');state=selectTerminalVisibilityGroup(added.state,'dashboard',added.group.id);state=renameTerminalVisibilityGroup(state,'focus','Builds');expect(activeTerminalVisibilityGroup(state,'dashboard').name).toBe('Builds');expect(renameTerminalVisibilityGroup(state,'default','Changed')).toBe(state);state=removeTerminalVisibilityGroup(state,'focus');expect(activeTerminalVisibilityGroup(state,'dashboard').id).toBe('default');expect(removeTerminalVisibilityGroup(state,'default')).toBe(state)});
  it('keeps independent hidden sets and active choices across scopes',()=>{let state=addTerminalVisibilityGroup(initialTerminalVisibilityState(),'focus').state;state=selectTerminalVisibilityGroup(state,'dashboard','focus');state=setTerminalVisibleInGroup(state,'focus','p:a',false);state=setAllTerminalsVisibleInGroup(state,'focus',['p:a','p:b'],false);expect(activeTerminalVisibilityGroup(state,'dashboard').hiddenKeys).toEqual(['p:a','p:b']);state=setTerminalVisibleInGroup(state,'focus','p:a',true);expect(activeTerminalVisibilityGroup(state,'dashboard').hiddenKeys).toEqual(['p:b']);expect(activeTerminalVisibilityGroup(state,'project:p').hiddenKeys).toEqual([])});
  it('keeps newly created terminals visible in Default and hidden in named views',()=>{const state=hideNewTerminalInNamedGroups(addTerminalVisibilityGroup(initialTerminalVisibilityState(),'focus').state,'p:new');expect(state.groups.find(group=>group.id==='default')?.hiddenKeys).toEqual([]);expect(state.groups.find(group=>group.id==='focus')?.hiddenKeys).toEqual(['p:new'])});
});
