import { describe,expect,it } from 'vitest';

import { parseTerminalSizeMessage,TERMINAL_DASHBOARD_COLS,TERMINAL_DASHBOARD_ROWS,TERMINAL_DRAWER_RESIZE_END_EVENT,TERMINAL_PREVIEW_NATURAL_HEIGHT,TERMINAL_PREVIEW_NATURAL_WIDTH,TERMINAL_RESIZE_SETTLE_MS,terminalBrowserWebSocketUrl,terminalDashboardTypography,terminalPreviewScale,terminalReconnectDelay,terminalResizeClaim,terminalShouldAdoptServerSize,terminalViewportScale,terminalViewportShouldAutoFocus } from './terminal-viewport';

describe('terminal viewport protocol',()=>{
  it('builds a credential-free same-origin attach URL',()=> { expect(terminalBrowserWebSocketUrl('/__hotsheet/project-api/project%20one','codex/main',{protocol:'https:',host:'hs.test'})).toBe('wss://hs.test/__hotsheet/project-api/project%20one/terminals/codex%2Fmain/attach'); });
  it('encodes leased viewport identity, focus, visibility, and bounded dimensions',()=> { expect(JSON.parse(terminalResizeClaim('viewer-1',0,24.9,true,false))).toEqual({resize:{viewer_id:'viewer-1',cols:1,rows:24,focus:true,visible:false}}); });
  it('accepts only valid server size broadcasts',()=>{expect(parseTerminalSizeMessage('{"pty_size":{"cols":120,"rows":40},"driven_by":"viewer-1"}')).toEqual({pty_size:{cols:120,rows:40},driven_by:'viewer-1'});expect(parseTerminalSizeMessage('terminal text')).toBeUndefined();expect(parseTerminalSizeMessage('{"pty_size":{"cols":0,"rows":40}}')).toBeUndefined()});
  it('caps exponential reconnect backoff',()=> { expect([0,1,2,8].map(terminalReconnectDelay)).toEqual([250,500,1000,8000]); });
  it('sends a final resize claim shortly after a drag settles',()=>{expect(TERMINAL_RESIZE_SETTLE_MS).toBe(120)});
  it('uses one explicit drawer-resize completion event',()=>{expect(TERMINAL_DRAWER_RESIZE_END_EVENT).toBe('hotsheet-terminal-drawer-resize-end')});
  it('focuses only the exact newly created project terminal',()=>{const request={projectId:'project-a',terminalId:'new-terminal'};expect(terminalViewportShouldAutoFocus(request,'project-a','new-terminal')).toBe(true);expect(terminalViewportShouldAutoFocus(request,'project-a','old-terminal')).toBe(false);expect(terminalViewportShouldAutoFocus(request,'project-b','new-terminal')).toBe(false);expect(terminalViewportShouldAutoFocus(undefined,'project-a','new-terminal')).toBe(false)});
  it('letterboxes smaller PTYs and always contains larger PTYs without clipping',()=>{expect(terminalViewportScale(120,40,80,24)).toBe(1);expect(terminalViewportScale(80,24,100,30)).toBe(.8);expect(terminalViewportScale(40,12,120,40)).toBe(.3)});
  it('uniformly scales the fixed 1280 by 960 dashboard surface into its frame',()=>{expect([TERMINAL_PREVIEW_NATURAL_WIDTH,TERMINAL_PREVIEW_NATURAL_HEIGHT]).toEqual([1280,960]);expect(terminalPreviewScale(640,480)).toBe(.5);expect(terminalPreviewScale(640,240)).toBe(.25);expect(terminalPreviewScale(0,480)).toBe(0)});
  it('keeps dashboard grids at 80 by 24 while fitting both physical axes without distorting glyphs',()=>{expect([TERMINAL_DASHBOARD_COLS,TERMINAL_DASHBOARD_ROWS]).toEqual([80,24]);expect(terminalDashboardTypography({fontSize:12,letterSpacing:0,lineHeight:1},640,384,1280,960)).toEqual({fontSize:24,letterSpacing:0,lineHeight:1.25});expect(terminalDashboardTypography({fontSize:12,letterSpacing:0,lineHeight:1},960,480,1280,960)).toEqual({fontSize:16,letterSpacing:0,lineHeight:1.5});expect(terminalDashboardTypography({fontSize:12,letterSpacing:0,lineHeight:1},480,480,1280,960)).toEqual({fontSize:24,letterSpacing:4,lineHeight:1});expect(terminalDashboardTypography({fontSize:12,letterSpacing:0,lineHeight:1},0,0,1280,960)).toEqual({fontSize:12,letterSpacing:0,lineHeight:1})});
  it('keeps preview and locally authoritative grids stable when server-size messages race',()=>{expect(terminalShouldAdoptServerSize(true,false,false)).toBe(false);expect(terminalShouldAdoptServerSize(false,true,false)).toBe(false);expect(terminalShouldAdoptServerSize(false,false,true)).toBe(false);expect(terminalShouldAdoptServerSize(false,false,false)).toBe(true)});
});
