import '@xterm/xterm/css/xterm.css';

import { FitAddon } from '@xterm/addon-fit';
import { WebglAddon } from '@xterm/addon-webgl';
import { Terminal } from '@xterm/xterm';

import { parseTerminalSizeMessage,TERMINAL_DASHBOARD_COLS,TERMINAL_DASHBOARD_FONT_SIZE,TERMINAL_DASHBOARD_LINE_HEIGHT,TERMINAL_DASHBOARD_ROWS,TERMINAL_DRAWER_RESIZE_END_EVENT,TERMINAL_PREVIEW_NATURAL_HEIGHT,TERMINAL_PREVIEW_NATURAL_WIDTH,TERMINAL_RESIZE_SETTLE_MS,terminalDedicatedGridSize,terminalPhysicalScale,terminalPreviewScale,terminalReconnectDelay,terminalResizeClaim,terminalScrollbackLimit,terminalShouldAdoptServerSize,terminalViewportClaimsSizingFocus,terminalViewportScale } from './terminal-viewport';

export function mountStaticTerminalViewportRuntime(element:HTMLElement,{output,autoFocus=false}:{output:string;autoFocus?:boolean}):()=>void {
  const scaledPreview=element.dataset.displayMode==='scaled-preview',background=getComputedStyle(element).getPropertyValue('--hs-terminal-background').trim()||'#000';
  if(scaledPreview){element.style.width=`${TERMINAL_PREVIEW_NATURAL_WIDTH}px`;element.style.height=`${TERMINAL_PREVIEW_NATURAL_HEIGHT}px`;element.dataset.naturalSize=`${TERMINAL_PREVIEW_NATURAL_WIDTH}x${TERMINAL_PREVIEW_NATURAL_HEIGHT}`}
  const terminal=new Terminal({cols:TERMINAL_DASHBOARD_COLS,rows:TERMINAL_DASHBOARD_ROWS,lineHeight:TERMINAL_DASHBOARD_LINE_HEIGHT,cursorBlink:!scaledPreview,disableStdin:scaledPreview,convertEol:false,scrollback:terminalScrollbackLimit(element.dataset.displayMode,true),fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace',fontSize:TERMINAL_DASHBOARD_FONT_SIZE,theme:{background}});
  terminal.open(element);element.dataset.renderer='dom';element.dataset.connection='connected';element.dataset.driving='true';element.dataset.ptySize=`${TERMINAL_DASHBOARD_COLS}x${TERMINAL_DASHBOARD_ROWS}`;element.dataset.gridSize=`${TERMINAL_DASHBOARD_COLS}x${TERMINAL_DASHBOARD_ROWS}`;element.dataset.sizingFocus='true';element.dataset.viewportVisible='true';element.dataset.fontSize=String(TERMINAL_DASHBOARD_FONT_SIZE);element.dataset.letterSpacing='0';element.dataset.lineHeight=String(TERMINAL_DASHBOARD_LINE_HEIGHT);element.dataset.scrollbackLimit=String(terminalScrollbackLimit(element.dataset.displayMode,true));element.dataset.geometryReady='false';
  let frame:number|undefined,disposed=false,initialFocusPending=autoFocus;
  const fill=()=>{frame=undefined;if(disposed||!terminal.element)return;const screen=terminal.element.querySelector<HTMLElement>('.xterm-screen');if(!screen||screen.offsetWidth<=0||screen.offsetHeight<=0)return;const target=element.parentElement??element,scale=terminalPhysicalScale(screen.offsetWidth,screen.offsetHeight,Math.max(1,target.clientWidth-1),Math.max(1,target.clientHeight-1));if(scale<=0)return;terminal.element.style.transform=`scale(${scale})`;element.dataset.scale=String(scale);element.dataset.physicalScale=String(scale);element.dataset.geometryReady='true';if(initialFocusPending){initialFocusPending=false;if(document.activeElement===document.body||document.activeElement===null)terminal.focus()}};
  const schedule=()=>{if(frame===undefined)frame=window.requestAnimationFrame(fill)};
  const render=terminal.onRender(schedule),resize=new ResizeObserver(schedule);resize.observe(element.parentElement??element);terminal.write(output,schedule);schedule();
  const focus=()=>{terminal.focus()};if(!scaledPreview)element.addEventListener('click',focus);
  return()=>{disposed=true;if(frame!==undefined)window.cancelAnimationFrame(frame);resize.disconnect();render.dispose();if(!scaledPreview)element.removeEventListener('click',focus);terminal.dispose()};
}

export function mountTerminalViewportRuntime(element:HTMLElement,{url,viewerId,autoFocus=false}:{url:string;viewerId:string;autoFocus?:boolean}):()=>void {
  const scaledPreview=element.dataset.displayMode==='scaled-preview',fixedDashboardGrid=element.dataset.gridPolicy==='dashboard-80x24',settledResize=element.classList.contains('terminal-viewport--dedicated'),insideDrawer=Boolean(element.closest('[data-region-id="app-terminal-drawer"]'));
  const background=getComputedStyle(element).getPropertyValue('--hs-terminal-background').trim()||'#000';
  if(scaledPreview){element.style.width=`${TERMINAL_PREVIEW_NATURAL_WIDTH}px`;element.style.height=`${TERMINAL_PREVIEW_NATURAL_HEIGHT}px`;element.dataset.naturalSize=`${TERMINAL_PREVIEW_NATURAL_WIDTH}x${TERMINAL_PREVIEW_NATURAL_HEIGHT}`}
  const scrollback=terminalScrollbackLimit(element.dataset.displayMode,fixedDashboardGrid);element.dataset.scrollbackLimit=String(scrollback);
  if(fixedDashboardGrid){element.dataset.geometryReady='false';element.dataset.fontSize=String(TERMINAL_DASHBOARD_FONT_SIZE);element.dataset.letterSpacing='0';element.dataset.lineHeight=String(TERMINAL_DASHBOARD_LINE_HEIGHT)}
  const terminal=new Terminal({...fixedDashboardGrid?{cols:TERMINAL_DASHBOARD_COLS,rows:TERMINAL_DASHBOARD_ROWS,lineHeight:TERMINAL_DASHBOARD_LINE_HEIGHT}:{},cursorBlink:!scaledPreview,disableStdin:scaledPreview,convertEol:false,scrollback,fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace',fontSize:fixedDashboardGrid?TERMINAL_DASHBOARD_FONT_SIZE:12,theme:{background}}),fit=new FitAddon();
  terminal.loadAddon(fit);terminal.open(element);
  let webgl:WebglAddon|undefined;
  if(element.classList.contains('terminal-viewport--dedicated'))try{webgl=new WebglAddon();terminal.loadAddon(webgl);element.dataset.renderer='webgl';webgl.onContextLoss(()=>{webgl?.dispose();webgl=undefined;element.dataset.renderer='dom'})}catch{element.dataset.renderer='dom'}else element.dataset.renderer='dom';
  let socket:WebSocket|undefined,reconnect:number|undefined,heartbeat:number|undefined,fitFrame:number|undefined,dashboardFrame:number|undefined,settleClaim:number|undefined,attempt=0,visible=false,disposed=false,focusRequested=autoFocus,serverSize:{cols:number;rows:number}|undefined;
  const focused=()=>terminalViewportClaimsSizingFocus(scaledPreview,fixedDashboardGrid,focusRequested,element.contains(document.activeElement));
  const proposed=()=>{if(fixedDashboardGrid)return{cols:TERMINAL_DASHBOARD_COLS,rows:TERMINAL_DASHBOARD_ROWS};const dimensions=fit.proposeDimensions()??{cols:terminal.cols,rows:terminal.rows};return settledResize?terminalDedicatedGridSize(dimensions.cols,dimensions.rows):dimensions};
  const reconcileScale=()=>{if(!terminal.element)return;if(fixedDashboardGrid){const scale=scaledPreview?terminalPreviewScale(element.parentElement?.clientWidth??0,element.parentElement?.clientHeight??0):1;element.style.transform=scaledPreview?`scale(${scale})`:'';element.dataset.scale=String(scale);delete element.dataset.viewingLabel;element.removeAttribute('aria-description');return}if(!serverSize)return;const authoritative=focused()||element.dataset.driving==='true',size=proposed(),scale=authoritative?1:terminalViewportScale(size.cols,size.rows,serverSize.cols,serverSize.rows),mismatch=scale<1;terminal.element.style.transform=mismatch?`scale(${scale})`:'';terminal.element.style.width=mismatch?`${100/scale}%`:'';terminal.element.style.height=mismatch?`${100/scale}%`:'';element.dataset.scale=String(scale);if(element.dataset.driving==='false'&&!authoritative){const label=`Viewing at ${serverSize.cols}×${serverSize.rows} · focus to resize`;element.dataset.viewingLabel=label;element.setAttribute('aria-description',label)}else{delete element.dataset.viewingLabel;element.removeAttribute('aria-description')}};
  const claim=()=>{const sizingFocus=focused();element.dataset.sizingFocus=String(sizingFocus);element.dataset.viewportVisible=String(visible);if(socket?.readyState!==WebSocket.OPEN)return;const size=proposed();socket.send(terminalResizeClaim(viewerId,size.cols,size.rows,sizingFocus,visible))};
  const applyDashboardPhysicalFill=()=>{const screen=terminal.element?.querySelector<HTMLElement>('.xterm-screen');if(!terminal.element||!screen||screen.offsetWidth<=0||screen.offsetHeight<=0)return;const targetWidth=Math.max(1,element.clientWidth-1),targetHeight=Math.max(1,element.clientHeight-1),scale=terminalPhysicalScale(screen.offsetWidth,screen.offsetHeight,targetWidth,targetHeight);if(scale<=0)return;terminal.element.style.transform=`scale(${scale})`;terminal.element.style.width='';terminal.element.style.height='';element.dataset.physicalScale=String(scale);element.dataset.geometryReady='true';if(autoFocus&&focusRequested){terminal.focus();claim()}};
  const scheduleDashboardFill=()=>{if(!fixedDashboardGrid||dashboardFrame!==undefined)return;dashboardFrame=window.requestAnimationFrame(()=>{dashboardFrame=undefined;applyDashboardPhysicalFill()})};
  const render=terminal.onRender(scheduleDashboardFill);
  const applySettledGeometry=()=>{if(disposed)return;try{if(fixedDashboardGrid){terminal.resize(TERMINAL_DASHBOARD_COLS,TERMINAL_DASHBOARD_ROWS);scheduleDashboardFill()}else{fit.fit();if(settledResize){const contained=terminalDedicatedGridSize(terminal.cols,terminal.rows);terminal.resize(contained.cols,contained.rows);element.dataset.containmentRows='1'}}}catch{/* layout can be transiently zero-sized */}element.dataset.gridSize=`${terminal.cols}x${terminal.rows}`;reconcileScale();claim()};
  const drawerResizeActive=()=>insideDrawer&&document.body.dataset.resizingRegion==='vertical';
  const fitAndClaim=()=>{if(fitFrame!==undefined)window.cancelAnimationFrame(fitFrame);if(settleClaim!==undefined)window.clearTimeout(settleClaim);if(drawerResizeActive())return;fitFrame=window.requestAnimationFrame(()=>{fitFrame=undefined;applySettledGeometry();if(!fixedDashboardGrid)settleClaim=window.setTimeout(()=>{settleClaim=undefined;applySettledGeometry()},TERMINAL_RESIZE_SETTLE_MS)})};
  const finishDrawerResize=()=>{if(!insideDrawer)return;if(settledResize)terminal.focus();applySettledGeometry()};
  window.addEventListener(TERMINAL_DRAWER_RESIZE_END_EVENT,finishDrawerResize);
  const connect=()=>{
    if(disposed)return;element.dataset.connection='connecting';const current=new WebSocket(url);socket=current;current.binaryType='arraybuffer';
    current.addEventListener('open',()=>{if(socket!==current)return;attempt=0;element.dataset.connection='connected';fitAndClaim();if(autoFocus)terminal.focus();heartbeat=window.setInterval(claim,5_000)});
    current.addEventListener('message',event=>{if(socket!==current)return;if(typeof event.data==='string'){const size=parseTerminalSizeMessage(event.data);if(!size)return;serverSize=size.pty_size;const drivenByViewer=size.driven_by===viewerId;if(!fixedDashboardGrid&&terminalShouldAdoptServerSize(scaledPreview,focused(),drivenByViewer))terminal.resize(size.pty_size.cols,size.pty_size.rows);else{const local=proposed();terminal.resize(local.cols,local.rows)}element.dataset.driving=String(drivenByViewer);element.dataset.ptySize=`${size.pty_size.cols}x${size.pty_size.rows}`;element.dataset.gridSize=`${terminal.cols}x${terminal.rows}`;queueMicrotask(reconcileScale);return}if(event.data instanceof Blob){void event.data.arrayBuffer().then(value=> { terminal.write(new Uint8Array(value)); });return}if(event.data instanceof ArrayBuffer)terminal.write(new Uint8Array(event.data))});
    const disconnected=()=>{if(socket!==current||disposed)return;if(heartbeat!==undefined)window.clearInterval(heartbeat);heartbeat=undefined;element.dataset.connection='reconnecting';const delay=terminalReconnectDelay(attempt++);reconnect=window.setTimeout(connect,delay)};
    current.addEventListener('close',disconnected);current.addEventListener('error',()=> { current.close(); });
  };
  const resize=new ResizeObserver(fitAndClaim);resize.observe(scaledPreview?element.parentElement??element:element);fitAndClaim();
  const intersection=new IntersectionObserver(entries=>{const next=entries[0]?.isIntersecting??false;if(next!==visible){visible=next;claim()} });intersection.observe(element);
  const focus=()=> {if(fixedDashboardGrid&&element.dataset.geometryReady!=='true')return;focusRequested=false;if(fixedDashboardGrid)claim();else applySettledGeometry() },focusTerminal=()=> { terminal.focus(); };if(!scaledPreview){element.addEventListener('click',focusTerminal);element.addEventListener('focusin',focus);element.addEventListener('focusout',focus)}
  const input=terminal.onData(value=>{if(!scaledPreview&&socket?.readyState===WebSocket.OPEN)socket.send(value)});
  connect();
  if(autoFocus){const focusIfCurrent=(force=false)=>{if(disposed||!terminal.element)return;const active=document.activeElement,activeTile=active instanceof Element?active.closest<HTMLElement>('[data-component="terminal-tile"]'):undefined,sameTerminalCard=activeTile?.dataset.terminalKey===`${element.dataset.projectId}:${element.dataset.terminalId}`;if(!force&&active!==document.body&&!element.contains(active)&&!element.closest('[data-magnified="true"]')?.contains(active)&&!sameTerminalCard)return;terminal.focus();claim()};focusIfCurrent(true);window.requestAnimationFrame(()=>{focusIfCurrent();window.setTimeout(focusIfCurrent,TERMINAL_RESIZE_SETTLE_MS)})}
  return ()=>{disposed=true;if(reconnect!==undefined)window.clearTimeout(reconnect);if(heartbeat!==undefined)window.clearInterval(heartbeat);if(fitFrame!==undefined)window.cancelAnimationFrame(fitFrame);if(dashboardFrame!==undefined)window.cancelAnimationFrame(dashboardFrame);if(settleClaim!==undefined)window.clearTimeout(settleClaim);window.removeEventListener(TERMINAL_DRAWER_RESIZE_END_EVENT,finishDrawerResize);resize.disconnect();intersection.disconnect();render.dispose();input.dispose();if(!scaledPreview){element.removeEventListener('click',focusTerminal);element.removeEventListener('focusin',focus);element.removeEventListener('focusout',focus)}socket?.close();terminal.dispose()};
}
