import {describe,expect,it} from 'vitest';

import {activeProjectRoot,dismissHs1MigrationPrompt,hs1MigrationPromptDismissed,loadProjectWorkspaceSession,reconcileRememberedProjectRoots,saveActiveProjectRoot,saveProjectWorkspaceSession} from './workspace-session';

describe('workspace session',()=>{
  it('round trips independently restorable inspector and reader tabs',()=>{const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value)};const session={selectedView:'backlog' as const,selectedTicketSlugs:['HS2-ONE'],searchOpen:true,searchQuery:'draft',inspectorTab:'timeline' as const,readerTab:'attachments' as const,composer:{open:true,title:'Lost thought',details:'Still here',category:'bug',upNext:true,attachments:[{id:'a',name:'proof.png'}]},composingNote:true,newNoteDraft:'note',feedbackReplies:{n:[{offset:4,text:'reply'}]},feedbackSelections:{n:['a']},feedbackNoteId:'n',feedbackDraft:'overall response',notWorking:{ticketId:'1',slug:'HS2-ONE',connectionId:'git',note:'broken',attachments:[]}};saveProjectWorkspaceSession(storage,'project',session);expect(loadProjectWorkspaceSession(storage,'project')).toEqual(session);saveActiveProjectRoot(storage,'/repo');expect(activeProjectRoot(storage)).toBe('/repo')});
  it('ignores malformed state, defaults older reader tabs, and sanitizes nested collections',()=>{expect(loadProjectWorkspaceSession({getItem:()=>'{bad'},'p')).toBeUndefined();const value=JSON.stringify({selectedView:'wat',composer:{attachments:[null,{id:'x',name:'x'}]},selectedTicketSlugs:[1,'HS2-X'],feedbackReplies:{n:[null,{offset:1,text:'ok'}]}});expect(loadProjectWorkspaceSession({getItem:()=>value},'p')).toMatchObject({selectedView:'all',selectedTicketSlugs:['HS2-X'],inspectorTab:'info',readerTab:'info',composer:{attachments:[{id:'x',name:'x'}]},feedbackReplies:{n:[{offset:1,text:'ok'}]}})});
  it('restores well-formed custom view ids and rejects malformed ones',()=>{const stored=(selectedView:string)=>JSON.stringify({selectedView,composer:{open:false},selectedTicketSlugs:[],feedbackReplies:{}});expect(loadProjectWorkspaceSession({getItem:()=>stored('custom:needs-docs')},'p')?.selectedView).toBe('custom:needs-docs');expect(loadProjectWorkspaceSession({getItem:()=>stored('custom:Needs docs!')},'p')?.selectedView).toBe('all')});
  it('dismisses one detected HS1 source without hiding a changed source identity',()=>{const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value)};expect(hs1MigrationPromptDismissed(storage,'project','/work/.hotsheet/db\u000017')).toBe(false);dismissHs1MigrationPrompt(storage,'project','/work/.hotsheet/db\u000017');expect(hs1MigrationPromptDismissed(storage,'project','/work/.hotsheet/db\u000017')).toBe(true);expect(hs1MigrationPromptDismissed(storage,'project','/work/.hotsheet/db\u000016')).toBe(false)});
  it('prunes failed hidden roots while retaining projects that reopened',()=>{expect(reconcileRememberedProjectRoots(['/work/good','/work/old'],['/work/good'])).toEqual({remembered:['/work/good'],failed:['/work/old']})});
});
