//! Disposable, bounded cache for cropped still-image renditions.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};
use std::time::SystemTime;

const MAX_ENTRIES: usize = 128;
const MAX_BYTES: u64 = 256 * 1024 * 1024;

fn writer_lock() -> std::sync::MutexGuard<'static, ()> {
    static WRITER: OnceLock<Mutex<()>> = OnceLock::new();
    WRITER
        .get_or_init(|| Mutex::new(()))
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

fn path(root: &Path, key: &str) -> PathBuf {
    root.join("image-crops").join(key)
}

/// A cache hit owns its bytes before another request can evict the file.
pub(crate) fn read(root: &Path, key: &str) -> Option<Vec<u8>> {
    let path = path(root, key);
    let bytes = fs::read(&path).ok()?;
    if let Ok(file) = fs::OpenOptions::new().write(true).open(path) {
        let _ = file.set_modified(SystemTime::now());
    }
    Some(bytes)
}

/// Atomically publish one completed rendition, then evict older entries. Failure is
/// only a cache miss; the response already owns the generated bytes.
pub(crate) fn store(root: &Path, key: &str, bytes: &[u8]) {
    store_bounded(root, key, bytes, MAX_ENTRIES, MAX_BYTES);
}

fn store_bounded(root: &Path, key: &str, bytes: &[u8], max_entries: usize, max_bytes: u64) {
    if bytes.len() as u64 > max_bytes {
        return;
    }
    let _writer = writer_lock();
    let cache_dir = root.join("image-crops");
    if fs::create_dir_all(&cache_dir).is_err() {
        return;
    }
    let Ok(mut staged) = tempfile::NamedTempFile::new_in(&cache_dir) else {
        return;
    };
    if staged.write_all(bytes).is_err() || staged.flush().is_err() {
        return;
    }
    let keep = path(root, key);
    // Two requests for the same digest may finish together. Either complete file is valid.
    if staged.persist_noclobber(&keep).is_err() && !keep.exists() {
        return;
    }
    prune(&cache_dir, &keep, max_entries, max_bytes);
}

fn prune(cache_dir: &Path, keep: &Path, max_entries: usize, max_bytes: u64) {
    let Ok(entries) = fs::read_dir(cache_dir) else {
        return;
    };
    let mut files = entries
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let name = entry.file_name();
            let name = name.to_str()?;
            // Ignore in-progress temporary writes and anything not owned by this cache.
            if name.len() != 64 || !name.bytes().all(|byte| byte.is_ascii_hexdigit()) {
                return None;
            }
            let metadata = entry.metadata().ok()?;
            metadata.is_file().then(|| {
                (
                    entry.path(),
                    metadata.len(),
                    metadata.modified().unwrap_or(SystemTime::UNIX_EPOCH),
                )
            })
        })
        .collect::<Vec<_>>();
    let mut total = files.iter().map(|(_, size, _)| size).sum::<u64>();
    let mut count = files.len();
    files.sort_by(|left, right| left.2.cmp(&right.2).then(left.0.cmp(&right.0)));
    for (path, size, _) in files {
        if count <= max_entries && total <= max_bytes {
            break;
        }
        if path == keep {
            continue;
        }
        if fs::remove_file(path).is_ok() {
            count -= 1;
            total -= size;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    fn key(char: char) -> String {
        char.to_string().repeat(64)
    }

    #[test]
    fn prunes_old_bytes_and_entries_but_keeps_current_and_temporary_files() {
        let root = tempfile::tempdir().unwrap();
        let dir = root.path().join("image-crops");
        fs::create_dir(&dir).unwrap();
        for (index, name) in [key('a'), key('b'), key('c')].iter().enumerate() {
            let path = dir.join(name);
            fs::write(&path, [index as u8; 4]).unwrap();
            fs::File::open(path)
                .unwrap()
                .set_modified(SystemTime::UNIX_EPOCH + Duration::from_secs(index as u64 + 1))
                .unwrap();
        }
        fs::write(dir.join("unfinished.tmp"), [0; 8]).unwrap();
        prune(&dir, &dir.join(key('c')), 2, 8);
        assert!(!dir.join(key('a')).exists());
        assert!(dir.join(key('b')).exists());
        assert!(dir.join(key('c')).exists());
        assert!(dir.join("unfinished.tmp").exists());
        prune(&dir, &dir.join(key('c')), 2, 4);
        assert!(!dir.join(key('b')).exists());
        assert!(dir.join(key('c')).exists());
    }

    #[test]
    fn cache_hit_refreshes_recency_and_concurrent_publication_stays_complete() {
        let root = tempfile::tempdir().unwrap();
        let first = key('a');
        let second = key('b');
        store(root.path(), &first, &[1; 32]);
        store(root.path(), &second, &[2; 32]);
        let old = SystemTime::UNIX_EPOCH + Duration::from_secs(1);
        fs::File::open(path(root.path(), &first))
            .unwrap()
            .set_modified(old)
            .unwrap();
        assert_eq!(read(root.path(), &first), Some(vec![1; 32]));
        assert!(
            fs::metadata(path(root.path(), &first))
                .unwrap()
                .modified()
                .unwrap()
                > old
        );
        let shared = key('c');
        std::thread::scope(|scope| {
            for _ in 0..4 {
                scope.spawn(|| store(root.path(), &shared, &[3; 8_192]));
            }
        });
        assert_eq!(read(root.path(), &shared), Some(vec![3; 8_192]));
        assert_eq!(
            fs::read_dir(root.path().join("image-crops"))
                .unwrap()
                .count(),
            3
        );
    }

    #[test]
    fn oversized_rendition_is_served_without_entering_cache() {
        let root = tempfile::tempdir().unwrap();
        store_bounded(root.path(), &key('a'), &[0; 9], 2, 8);
        assert!(read(root.path(), &key('a')).is_none());
    }
}
