import { attr, type AttrSpec } from 'kerfjs';

// Delegation targets for the UX demo (`main.tsx`). Each spec owns one `[name="value"]` selector so a
// delegate() call and any demo-owned markup share a single rename-safe constant (HS2-G838PZ).

/** `data-action` values the UX demo delegates to its fixture handlers. */
export const DEMO_ACTIONS = {
  addCommandGroup: attr('data-action', 'add-command-group'),
  addCommandSetting: attr('data-action', 'add-command-setting'),
  addTerminalVisibilityGroup: attr('data-action', 'add-terminal-visibility-group'),
  addTicketNote: attr('data-action', 'add-ticket-note'),
  addView: attr('data-action', 'add-view'),
  attachmentMenuAction: attr('data-action', 'attachment-menu-action'),
  authenticateConnection: attr('data-action', 'authenticate-connection'),
  cancelNewNote: attr('data-action', 'cancel-new-note'),
  cancelNotWorking: attr('data-action', 'cancel-not-working'),
  cancelPermissionAutomation: attr('data-action', 'cancel-permission-automation'),
  cancelTerminalVisibilityName: attr('data-action', 'cancel-terminal-visibility-name'),
  clearNewTicketAttachments: attr('data-action', 'clear-new-ticket-attachments'),
  closeAttachmentGallery: attr('data-action', 'close-attachment-gallery'),
  closeCommandEditor: attr('data-action', 'close-command-editor'),
  closeConversation: attr('data-action', 'close-conversation'),
  closeProjectTab: attr('data-action', 'close-project-tab'),
  createNoteForm: attr('data-action', 'create-note-form'),
  createTicketForm: attr('data-action', 'create-ticket-form'),
  deleteCommandGroup: attr('data-action', 'delete-command-group'),
  deleteCommandSetting: attr('data-action', 'delete-command-setting'),
  dismissHs1Migration: attr('data-action', 'dismiss-hs1-migration'),
  editAttachmentBatchLabel: attr('data-action', 'edit-attachment-batch-label'),
  editBlockedReason: attr('data-action', 'edit-blocked-reason'),
  editCommandSetting: attr('data-action', 'edit-command-setting'),
  editMarkdown: attr('data-action', 'edit-markdown'),
  editTicketTitle: attr('data-action', 'edit-ticket-title'),
  expandTicketComposer: attr('data-action', 'expand-ticket-composer'),
  hideAllTerminalsInGroup: attr('data-action', 'hide-all-terminals-in-group'),
  moreWorkspaceActions: attr('data-action', 'more-workspace-actions'),
  nextGalleryImage: attr('data-action', 'next-gallery-image'),
  openAiConversationDemo: attr('data-action', 'open-ai-conversation-demo'),
  openAttachmentMenu: attr('data-action', 'open-attachment-menu'),
  openCodeReview: attr('data-action', 'open-code-review'),
  openBulkTicketDialogDemo: attr('data-action', 'open-bulk-ticket-dialog-demo'),
  openCommandRunDialogDemo: attr('data-action', 'open-command-run-dialog-demo'),
  openGalleryDemo: attr('data-action', 'open-gallery-demo'),
  openHs1MigrationDemo: attr('data-action', 'open-hs1-migration-demo'),
  openNotWorkingDemo: attr('data-action', 'open-not-working-demo'),
  openProjectStats: attr('data-action', 'open-project-stats'),
  openRepositoryReview: attr('data-action', 'open-repository-review'),
  openRepositoryStatus: attr('data-action', 'open-repository-status'),
  openSelectedTicketActions: attr('data-action', 'open-selected-ticket-actions'),
  openTerminalContextMenu: attr('data-action', 'open-terminal-context-menu'),
  previousGalleryImage: attr('data-action', 'previous-gallery-image'),
  projectTabContextAction: attr('data-action', 'project-tab-context-action'),
  refreshRepositoryStatus: attr('data-action', 'refresh-repository-status'),
  removeNewTicketAttachment: attr('data-action', 'remove-new-ticket-attachment'),
  removeNotWorkingAttachment: attr('data-action', 'remove-not-working-attachment'),
  removeTerminalVisibilityGroup: attr('data-action', 'remove-terminal-visibility-group'),
  renameTerminalVisibilityGroup: attr('data-action', 'rename-terminal-visibility-group'),
  resetSettings: attr('data-action', 'reset-settings'),
  resetWorkspaceNotifications: attr('data-action', 'reset-workspace-notifications'),
  resizeProjectSidebar: attr('data-action', 'resize-project-sidebar'),
  retryConnection: attr('data-action', 'retry-connection'),
  runCommand: attr('data-action', 'run-command'),
  saveConversation: attr('data-action', 'save-conversation'),
  saveNoteEdit: attr('data-action', 'save-note-edit'),
  seekGalleryAnnotation: attr('data-action', 'seek-gallery-annotation'),
  selectChangeEvidenceView: attr('data-action', 'select-change-evidence-view'),
  selectCommandIcon: attr('data-action', 'select-command-icon'),
  selectConversationProvider: attr('data-action', 'select-conversation-provider'),
  selectProjectTab: attr('data-action', 'select-project-tab'),
  selectRepositoryComparisonCommit: attr('data-action', 'select-repository-comparison-commit'),
  selectRepositoryView: attr('data-action', 'select-repository-view'),
  selectTerminalVisibilityTab: attr('data-action', 'select-terminal-visibility-tab'),
  selectTicketColumn: attr('data-action', 'select-ticket-column'),
  selectTicketRow: attr('data-action', 'select-ticket-row'),
  selectView: attr('data-action', 'select-view'),
  sendConversationTurn: attr('data-action', 'send-conversation-turn'),
  setInspectorTab: attr('data-action', 'set-inspector-tab'),
  setRepositoryComparisonSide: attr('data-action', 'set-repository-comparison-side'),
  setShellMode: attr('data-action', 'set-shell-mode'),
  setToolbarGroupDemoMode: attr('data-action', 'set-toolbar-group-demo-mode'),
  setViewMode: attr('data-action', 'set-view-mode'),
  showAllTerminalsInGroup: attr('data-action', 'show-all-terminals-in-group'),
  showConnectionDetails: attr('data-action', 'show-connection-details'),
  showTerminalVisibilityDemo: attr('data-action', 'show-terminal-visibility-demo'),
  stopConversation: attr('data-action', 'stop-conversation'),
  submitNotWorking: attr('data-action', 'submit-not-working'),
  submitTerminalVisibilityName: attr('data-action', 'submit-terminal-visibility-name'),
  toggleCodeReviewCommit: attr('data-action', 'toggle-code-review-commit'),
  toggleCommandGroup: attr('data-action', 'toggle-command-group'),
  toggleCommandSection: attr('data-action', 'toggle-command-section'),
  toggleDevReview: attr('data-action', 'toggle-dev-review'),
  toggleDrive: attr('data-action', 'toggle-drive'),
  toggleFavorite: attr('data-action', 'toggle-favorite'),
  toggleFeedbackChoice: attr('data-action', 'toggle-feedback-choice'),
  toggleGalleryDraw: attr('data-action', 'toggle-gallery-draw'),
  toggleGalleryMarkup: attr('data-action', 'toggle-gallery-markup'),
  toggleGalleryMuted: attr('data-action', 'toggle-gallery-muted'),
  toggleGalleryPlayback: attr('data-action', 'toggle-gallery-playback'),
  toggleGalleryVolume: attr('data-action', 'toggle-gallery-volume'),
  toggleInspectorUpNext: attr('data-action', 'toggle-inspector-up-next'),
  toggleMarkdownExpanded: attr('data-action', 'toggle-markdown-expanded'),
  toggleNewTicketUpNext: attr('data-action', 'toggle-new-ticket-up-next'),
  toggleProjectSidebar: attr('data-action', 'toggle-project-sidebar'),
  toggleReaderTextSize: attr('data-action', 'toggle-reader-text-size'),
  toggleRepositoryComparison: attr('data-action', 'toggle-repository-comparison'),
  toggleResizableCollapse: attr('data-action', 'toggle-resizable-collapse'),
  toggleRowUpNext: attr('data-action', 'toggle-row-up-next'),
  toggleSelectedUpNext: attr('data-action', 'toggle-selected-up-next'),
  toggleSettings: attr('data-action', 'toggle-settings'),
  toggleTerminalVisibility: attr('data-action', 'toggle-terminal-visibility'),
  toggleTicketInspector: attr('data-action', 'toggle-ticket-inspector'),
  transitionBack: attr('data-action', 'transition-back'),
  transitionForward: attr('data-action', 'transition-forward'),
  zoomGalleryImage: attr('data-action', 'zoom-gallery-image'),
} as const satisfies Record<string, AttrSpec<'data-action'>>;

/** `data-component` roots whose demo-lifetime events the catalog handles. */
export const DEMO_COMPONENTS = {
  aiConversation: attr('data-component', 'ai-conversation'),
  attachmentGallery: attr('data-component', 'attachment-gallery'),
  hs1MigrationDialog: attr('data-component', 'hs1-migration-dialog'),
  notWorkingDialog: attr('data-component', 'not-working-dialog'),
  quickTicketComposer: attr('data-component', 'quick-ticket-composer'),
  terminalTile: attr('data-component', 'terminal-tile'),
  ticketReader: attr('data-component', 'ticket-reader'),
} as const satisfies Record<string, AttrSpec<'data-component'>>;

/** Form-control `name` values whose input the UX demo mirrors into fixture state. */
export const DEMO_FIELDS = {
  attachmentBatchLabel: attr('name', 'attachment-batch-label'),
  blockedReason: attr('name', 'blocked-reason'),
  commandIconSearch: attr('name', 'command-icon-search'),
  conversationDraft: attr('name', 'conversation-draft'),
  inspectorCategory: attr('name', 'inspector-category'),
  inspectorPriority: attr('name', 'inspector-priority'),
  inspectorStatus: attr('name', 'inspector-status'),
  markdownSource: attr('name', 'markdown-source'),
  newNoteBody: attr('name', 'new-note-body'),
  newTicketCategory: attr('name', 'new-ticket-category'),
  newTicketDetails: attr('name', 'new-ticket-details'),
  newTicketSource: attr('name', 'new-ticket-source'),
  newTicketTitle: attr('name', 'new-ticket-title'),
  noteBody: attr('name', 'note-body'),
  notWorkingNote: attr('name', 'not-working-note'),
  ticketTagInput: attr('name', 'ticket-tag-input'),
  ticketTitle: attr('name', 'ticket-title'),
} as const satisfies Record<string, AttrSpec<'name'>>;

/** Other single-attribute markers (drop targets, editable surfaces, tab kinds) the demo delegates to. */
export const DEMO_MARKERS = {
  attachmentDropTarget: attr('data-attachment-drop-target', 'true'),
  editBlockedReason: attr('data-edit-blocked-reason', 'true'),
  editOnClick: attr('data-edit-on-click', 'true'),
  galleryAnnotationSurface: attr('data-gallery-annotation-surface', 'true'),
  notWorkingDropzone: attr('data-not-working-dropzone', 'true'),
  tabKindProject: attr('data-tab-kind', 'project'),
} as const satisfies Record<string, AttrSpec>;
