import {expect,test} from '@playwright/test';

const project={id:'saved-views',root:'/work/saved-views',name:'Saved views',stores:['/work/saved-views.hs2'],apiPath:'/__hotsheet/project-api/saved-views'};
const base={connection_id:'git',native_id:'1',qualified_id:'git:1',id:'1',slug:'HS2-DOCS',title:'Document the saved view',category:'task',priority:'default',status:'not_started',up_next:true,feedback_needed:false,tags:['docs'],blocked_by:[],claim_count:0,created_at:'2026-09-10T00:00:00Z',updated_at:'2026-09-10T00:00:00Z'};
const rows=[base,{...base,native_id:'2',qualified_id:'git:2',id:'2',slug:'HS2-CODE',title:'Implement the parser',tags:['client']}];

test('creates, renames, deletes, and shares a custom ticket view',async({page})=>{
  let views:Array<{id:string;name:string;query:string}>=[];
  await page.route('**/*',route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname;
    if(path==='/__hotsheet/projects/open')return route.fulfill({status:201,json:project});
    if(path.endsWith('/views')&&request.method()==='PUT'){views=request.postDataJSON();return route.fulfill({json:views})}
    if(path.endsWith('/views'))return route.fulfill({json:views});
    if(path.endsWith('/tickets')&&request.method()==='GET'){const tags=url.searchParams.get('tags')?.split(' ').filter(Boolean)??[],items=tags.length?rows.filter(ticket=>tags.every(tag=>ticket.tags.includes(tag))):rows;return route.fulfill({json:url.searchParams.has('page_size')?{items,counts:{total:rows.length,queued:rows.length,backlog:0,archive:0,open:rows.length,up_next:rows.length,active:0,started:0,completed_today:0}}:items})}
    if(path.endsWith('/providers'))return route.fulfill({json:[{connection_id:'git-local',provider:'git',display_name:'Hot Sheet git',locator:project.stores[0],default:true,capabilities:{create:true,update:true,notes:true,attachments:true,watch:true,query_fields:[]}}]});
    if(path.endsWith('/connections')||path.endsWith('/permissions')||path.endsWith('/commands')||path.endsWith('/command-runs')||path.endsWith('/terminals')||path.endsWith('/corrupt-tickets'))return route.fulfill({json:[]});
    if(path.endsWith('/repository/status'))return route.fulfill({json:{branch:'main',ahead:0,behind:0,staged:0,unstaged:0,untracked:0,conflicted:0,clean:true}});
    if(path.endsWith('/ws/poll'))return route.fulfill({json:{cursor:Number(url.searchParams.get('since')??0),events:[],overflow:false}});
    return route.continue();
  });
  await page.setViewportSize({width:1440,height:900});await page.goto('/');await page.getByRole('button',{name:'Open project'}).click();await page.getByRole('button',{name:'Open project',exact:true}).last().click();
  await page.getByRole('button',{name:'Add view'}).click();const dialog=page.locator('[data-component="saved-view-dialog"]');await expect(dialog.getByRole('textbox',{name:'View name'})).toBeVisible();await dialog.getByRole('textbox',{name:'View name'}).fill('Needs docs');const query=dialog.getByRole('textbox',{name:'Search query'});await query.fill('tag:docs ');await expect(dialog.locator('[data-component="filter-chip"]')).toContainText('tag:docs');await page.waitForTimeout(250);await page.screenshot({path:'/private/tmp/hs2-r7gpjm-create-view-wide.png',clip:{x:430,y:175,width:580,height:550}});await dialog.getByRole('button',{name:'Create View'}).click();
  await expect(page.getByRole('button',{name:'Needs docs',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('heading',{name:'Needs docs'})).toBeVisible();await expect(page.locator('[data-ticket-slug="HS2-DOCS"]')).toBeVisible();await expect(page.locator('[data-ticket-slug="HS2-CODE"]')).toHaveCount(0);expect(views).toEqual([{id:'needs-docs',name:'Needs docs',query:'tag:docs'}]);
  await expect(page.getByRole('button',{name:'More actions for Needs docs'})).toBeVisible();await expect(page.getByRole('button',{name:'Rename Needs docs'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Delete Needs docs'})).toHaveCount(0);await page.getByRole('button',{name:'More actions for Needs docs'}).click();const menu=page.getByRole('menu',{name:'Needs docs view actions'});await expect(menu).toBeVisible();await page.waitForTimeout(250);await page.screenshot({path:'/private/tmp/hs2-r7gpjm-view-menu-wide.png',clip:{x:0,y:260,width:520,height:400}});
  await menu.getByText('Edit view…').click();await expect(dialog).toHaveAttribute('data-mode','rename');await expect(query).toBeVisible();await expect(dialog.locator('[data-component="filter-chip"]')).toContainText('tag:docs');await dialog.getByRole('textbox',{name:'View name'}).fill('Documentation');await query.fill('tag:client ');await expect(dialog.locator('[data-component="filter-chip"]')).toContainText('tag:client');await page.waitForTimeout(250);await page.screenshot({path:'/private/tmp/hs2-r7gpjm-edit-view-wide.png',clip:{x:430,y:175,width:580,height:550}});await dialog.getByRole('button',{name:'Edit View'}).click();
  await expect(page.getByRole('button',{name:'Documentation',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('heading',{name:'Documentation'})).toBeVisible();await expect(page.locator('[data-ticket-slug="HS2-CODE"]')).toBeVisible();await expect(page.locator('[data-ticket-slug="HS2-DOCS"]')).toHaveCount(0);expect(views).toEqual([{id:'needs-docs',name:'Documentation',query:'tag:client'}]);
  const savedRow=page.locator('[data-saved-view-id="custom:needs-docs"]');await page.setViewportSize({width:720,height:760});await savedRow.click({button:'right'});const narrowMenu=page.getByRole('menu',{name:'Documentation view actions'});await expect(narrowMenu).toBeVisible();await page.waitForTimeout(250);await page.screenshot({path:'/private/tmp/hs2-r7gpjm-view-menu-narrow.png',clip:{x:0,y:230,width:420,height:430}});await narrowMenu.getByText('Delete view…').click();const confirmation=page.locator('[data-component="saved-view-delete-dialog"]');await expect(confirmation).toContainText('Tickets are not affected.');await confirmation.getByRole('button',{name:'Delete View'}).click();
  await expect(page.getByRole('button',{name:/Queue/})).toHaveAttribute('aria-current','page');await expect(page.getByRole('button',{name:/Documentation/})).toHaveCount(0);await expect(page.locator('[data-ticket-slug="HS2-CODE"]')).toBeVisible();await expect(page.getByRole('button',{name:'Search tickets'})).toBeVisible();expect(views).toEqual([]);
});
