import { expect, test } from '@playwright/test';

test('navigates the catalog and preserves URL-addressable selection', async ({ page }) => {
  await page.goto('/ux-demo');
  await expect(page.getByRole('heading', { name: 'UX components' })).toBeVisible();
  const catalog = page.getByRole('navigation');
  await expect(catalog.locator('[data-demo-id="app-shell"]')).toHaveCSS('color', 'rgb(154, 156, 165)');
  await expect(catalog.locator('[data-demo-id="ticket-row"]')).not.toHaveCSS('color', 'rgb(154, 156, 165)');
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: /TicketRow/ }).click();
  await expect(page).toHaveURL('/ux-demo?component=ticket-row');
  await expect(page.getByRole('heading', { name: 'TicketRow', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'TicketRow demo' })).toBeVisible();
  await expect(page.getByRole('complementary', { name: 'Component catalog' }).getByText('Uses')).toHaveCount(0);
  const relationships = page.locator('.demo-relationships');
  await expect(relationships.getByRole('button', { name: /Related components/ })).toBeVisible();
  await relationships.getByRole('button', { name: /Related components/ }).click();
  await expect(relationships.getByRole('heading', { name: 'Uses' })).toBeVisible();
  await relationships.locator('wa-dropdown-item', { hasText: 'TagChip' }).click();
  await expect(page).toHaveURL('/ux-demo?component=tag-chip');
  await relationships.getByRole('button', { name: /Related components/ }).click();
  await expect(relationships.getByRole('heading', { name: 'Used by' })).toBeVisible();
  await relationships.locator('wa-dropdown-item', { hasText: 'TicketRow' }).click();
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
});

test('round-trips StatusBadge controls through reset and a post-reset edit', async ({ page }) => {
  await page.goto('/ux-demo?component=status-badge');
  const badge = page.locator('[data-component="status-badge"]');
  await expect(badge).toContainText('Started');
  await expect(badge.locator('[data-lucide="clock"]')).toHaveAttribute('aria-hidden', 'true');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'StatusBadge settings' });
  const status = inspector.locator('wa-select[name="status"]');
  const appearance = inspector.locator('wa-select[name="appearance"]');
  const icon = inspector.locator('wa-checkbox[name="show-icon"]');
  const compact = inspector.locator('wa-checkbox[name="compact"]');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toContainText('Verified');
  await expect(badge.locator('[data-lucide="badge-check"]')).toHaveCount(1);
  await appearance.evaluate((node: HTMLElement & { value: string }) => { node.value = 'plain'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toHaveAttribute('data-appearance', 'plain');
  await expect(badge).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  await compact.click();
  await expect(badge).toHaveClass(/status-badge--compact/);
  await icon.click();
  await expect(badge.locator('.status-badge__icon')).toHaveCount(0);
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(appearance).toHaveJSProperty('value', 'filled');
  await expect(icon).toHaveJSProperty('checked', true);
  await expect(compact).toHaveJSProperty('checked', false);
  await expect(badge).toContainText('Started');
  await expect(badge).toHaveAttribute('data-appearance', 'filled');
  await expect(badge).not.toHaveClass(/status-badge--compact/);
  await expect(badge.locator('[data-lucide="clock"]')).toHaveCount(1);
  await expect(badge.locator('.status-badge__icon')).toHaveCount(1);
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'completed'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toContainText('Completed');
  await expect(badge.locator('[data-lucide="circle-check"]')).toHaveCount(1);
});

test('round-trips every TicketRow setting and selection action', async ({ page }) => {
  await page.goto('/ux-demo?component=ticket-row');
  const row = page.locator('[data-component="ticket-list-row"]');
  await expect(row).toContainText('Build the first client ticket list');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'TicketRow settings' });
  const title = inspector.getByRole('textbox', { name: 'Title' });
  const category = inspector.getByRole('textbox', { name: 'Category' });
  const tags = inspector.getByRole('textbox', { name: 'Tags (comma separated)' });
  const agent = inspector.getByRole('textbox', { name: 'Active agent' });
  const updated = inspector.getByRole('textbox', { name: 'Updated label' });
  const status = inspector.locator('wa-select[name="status"]');
  const priority = inspector.locator('wa-select[name="priority"]');
  const categoryIcon = inspector.locator('wa-select[name="category-icon"]');
  const categoryColor = inspector.locator('wa-select[name="category-color"]');
  const upNext = inspector.locator('wa-checkbox[name="up-next"]');
  const blocked = inspector.locator('wa-checkbox[name="blocked"]');
  const needsReview = inspector.locator('wa-checkbox[name="needs-review"]');
  const selected = inspector.locator('wa-checkbox[name="selected"]');
  const busy = inspector.locator('wa-checkbox[name="busy"]');
  await title.fill('Fix selection synchronization');
  await category.fill('bug');
  await tags.fill('client, regression');
  await agent.fill('Codex');
  await updated.fill('Now');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'urgent'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await categoryIcon.evaluate((node: HTMLElement & { value: string }) => { node.value = 'bug'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await categoryColor.evaluate((node: HTMLElement & { value: string }) => { node.value = '#ef4444'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await upNext.click();
  await blocked.click();
  await needsReview.click();
  await selected.click();
  await busy.click();
  await expect(row).toContainText('Fix selection synchronization');
  await expect(row).toContainText('Verified');
  await expect(row.locator('[data-component="status-badge"]')).toHaveAttribute('data-appearance', 'plain');
  await expect(row.locator('[data-component="status-badge"]')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  await expect(row.locator('[data-lucide="bug"]')).toHaveCount(1);
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('color', 'rgb(239, 68, 68)');
  await categoryColor.evaluate((node: HTMLElement & { value: string }) => { node.value = '#e5e7eb'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('color', 'rgb(156, 163, 175)');
  await categoryIcon.evaluate((node: HTMLElement & { value: string }) => { node.value = ''; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('.ticket-list-row__category--label')).toHaveText('BUG');
  await expect(row.locator('.ticket-list-row__category--label')).toHaveCSS('color', 'rgb(156, 163, 175)');
  await expect(row.locator('.ticket-list-row__category--label')).toHaveCSS('width', '32px');
  await expect(row).toContainText('regression');
  await expect(row.locator('[data-lucide="star"]')).toHaveCount(1);
  await expect(row.locator('[data-action="toggle-row-up-next"]')).not.toHaveClass(/active/);
  await expect(row).toContainText('Codex');
  await expect(row).toContainText('Now');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(row.locator('[data-lucide="chevrons-up"]')).toHaveCount(1);
  await expect(row.locator('.ticket-list-row__priority')).toHaveCSS('color', 'rgb(239, 68, 68)');
  await expect(row.locator('.ticket-list-row__indicator')).toHaveClass(/needs-review/);
  await row.click();
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(row).toHaveAttribute('data-selected', 'false');
  await expect(page.getByText('Ticket deselected')).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(title).toHaveJSProperty('value', 'Build the first client ticket list');
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(priority).toHaveJSProperty('value', 'high');
  await expect(category).toHaveJSProperty('value', 'feature');
  await expect(tags).toHaveJSProperty('value', 'client, ux');
  await expect(agent).toHaveJSProperty('value', 'Claude');
  await expect(updated).toHaveJSProperty('value', '1h ago');
  await expect(upNext).toHaveJSProperty('checked', true);
  await expect(blocked).toHaveJSProperty('checked', false);
  await expect(needsReview).toHaveJSProperty('checked', false);
  await expect(categoryIcon).toHaveJSProperty('value', 'sparkles');
  await expect(categoryColor).toHaveJSProperty('value', '#3b82f6');
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(busy).toHaveJSProperty('checked', true);
  await expect(row).toContainText('Build the first client ticket list');
  await expect(row).toContainText('Started');
  await expect(row.locator('[data-action="toggle-row-up-next"]')).toHaveClass(/active/);
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('width', '32px');
  await expect(row.locator('.ticket-list-row__indicator')).toHaveClass(/up-next/);
  await expect(row).toContainText('Claude');
  await expect(row).toContainText('1h ago');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await title.fill('Post-reset edit works');
  await expect(row).toContainText('Post-reset edit works');
  await row.focus();
  await page.keyboard.press('Enter');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(selected).toHaveJSProperty('checked', true);

  const star = row.locator('[data-action="toggle-row-up-next"]');
  const starBox = await star.boundingBox();
  expect(starBox).not.toBeNull();
  await star.click();
  await expect(upNext).toHaveJSProperty('checked', false);
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(star).not.toHaveClass(/active/);
  await star.focus();
  await page.keyboard.press('Enter');
  await expect(upNext).toHaveJSProperty('checked', true);
  await expect(star).toHaveClass(/active/);

  await row.click({ button: 'right' });
  const menu = page.getByRole('menu', { name: 'Ticket actions' });
  await expect(menu).toBeVisible();
  const menuItems = menu.locator('wa-dropdown-item');
  await expect(menuItems).toHaveCount(9);
  expect(await menuItems.evaluateAll(items => items.every(item => item.querySelector('[data-lucide]') !== null))).toBe(true);
  await expect(row).toHaveAttribute('data-selected', 'true');
  await menu.getByText('Toggle Up Next', { exact: true }).click();
  await expect(star).not.toHaveClass(/active/);
  await expect(upNext).toHaveJSProperty('checked', false);
  await expect(page.getByText('Toggle Up Next selected')).toBeVisible();

  await title.fill('A deliberately long ticket title that must wrap across no more than two lines while the AI working indicator remains entirely visible');
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'default'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('[data-lucide="minus"]')).toHaveCount(1);
  await tags.fill('client, regression, server, ux');
  await row.evaluate((node: HTMLElement) => { node.style.width = '320px'; });
  const [rowBox, timeBox, slugBox, identityBox] = await Promise.all([row.boundingBox(), row.locator('.ticket-list-row__updated').boundingBox(), row.locator('.ticket-list-row__slug').boundingBox(), row.locator('.ticket-list-row__identity').boundingBox()]);
  expect(rowBox).not.toBeNull(); expect(timeBox).not.toBeNull(); expect(slugBox).not.toBeNull(); expect(identityBox).not.toBeNull();
  expect(timeBox!.x + timeBox!.width).toBeLessThanOrEqual(rowBox!.x + rowBox!.width);
  expect(Math.abs(timeBox!.y + timeBox!.height - (slugBox!.y + slugBox!.height))).toBeLessThanOrEqual(3);
  expect(identityBox!.height).toBeLessThanOrEqual(43);
  await expect(row.locator('.ticket-list-row__identity')).toHaveCSS('display', 'block');
  await expect(row.locator('.ticket-list-row__slug')).toHaveCSS('display', 'inline-block');
  await expect(row.locator('.ticket-list-row__priority')).toHaveCSS('display', 'inline');
  expect(await row.locator('.ticket-list-row__identity > *').evaluateAll(elements => elements.map(element => element.className || element.tagName.toLowerCase()))).toEqual([
    'ticket-list-row__slug', 'ticket-list-row__priority', 'strong',
  ]);
  await expect(row.locator('[data-component="tag-chip"]')).toHaveCount(4);
  for (const chip of await row.locator('[data-component="tag-chip"]').all()) await expect(chip).toBeVisible();
});

test('uses the identical responsive TicketRow in list and board compositions', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await page.goto('/ux-demo?component=ticket-list');
  const list = page.getByRole('listbox', { name: 'Example ticket list' });
  const listRows = list.locator('[data-component="ticket-list-row"]');
  await expect(listRows).toHaveCount(5);
  await expect(list).toHaveCSS('border-radius', '10.4px');
  const listRow = listRows.first();
  const listWidth = await listRow.evaluate(node => node.getBoundingClientRect().width);
  expect(listWidth).toBeGreaterThan(600);
  await expect(listRows.first()).toHaveCSS('border-radius', '10.4px 10.4px 0px 0px');
  await expect(listRows.nth(1)).toHaveCSS('border-radius', '0px');
  await expect(listRows.last()).toHaveCSS('border-radius', '0px 0px 10.4px 10.4px');
  await expect(listRow).toHaveCSS('box-shadow', 'none');
  await listRow.click();
  await expect(listRow).toHaveAttribute('data-selected', 'true');
  await expect(page.getByText('HS2-R76MMW selected')).toBeVisible();
  const listStar = listRow.locator('[data-action="toggle-row-up-next"]');
  await listStar.click();
  await expect(listStar).not.toHaveClass(/active/);
  await expect(page.getByText('HS2-R76MMW removed from Up Next')).toBeVisible();

  await page.getByRole('navigation').getByRole('link', { name: /TicketBoard/ }).click();
  await expect(page).toHaveURL('/ux-demo?component=ticket-board');
  const board = page.getByRole('region', { name: 'Example status board' });
  await expect(board.locator('.ticket-board__column')).toHaveCount(3);
  await expect(board).toHaveCSS('padding', '0px');
  await expect(board).toHaveCSS('border-top-width', '0px');
  await expect(board).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  await expect(board.getByLabel('2 tickets')).toHaveCount(2);
  await expect(board.getByLabel('1 tickets')).toHaveCount(1);
  const boardRows = board.locator('[data-component="ticket-list-row"]');
  await expect(boardRows).toHaveCount(5);
  const narrowRow = boardRows.first();
  const boardWidth = await narrowRow.evaluate(node => node.getBoundingClientRect().width);
  expect(boardWidth).toBeLessThan(384);
  await expect(narrowRow).toHaveCSS('border-radius', '10.4px');
  await expect(narrowRow).not.toHaveCSS('box-shadow', 'none');
  await expect(page.locator('[data-component="ticket-card"]')).toHaveCount(0);
  await narrowRow.focus();
  await page.keyboard.press('Enter');
  await expect(narrowRow).toHaveAttribute('data-selected', 'true');
  await narrowRow.click({ button: 'right' });
  const menu = page.getByRole('menu', { name: 'Ticket actions' });
  await expect(menu).toBeVisible();
  await menu.getByText('Toggle Up Next', { exact: true }).click();
  await expect(page.getByText(/Toggle Up Next selected for HS2-/)).toBeVisible();
});

test('switches and searches the connected workspace through WorkspaceHeader', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await page.goto('/ux-demo?component=workspace-header');
  const header = page.locator('[data-component="workspace-header"]');
  await expect(header).toContainText('Hot Sheet 2');
  await expect(header.getByRole('button', { name: 'List view' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('listbox', { name: 'Workspace tickets' }).locator('[data-component="ticket-list-row"]')).toHaveCount(5);
  await header.getByRole('button', { name: 'Columns view' }).click();
  await expect(header.getByRole('button', { name: 'Columns view' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('region', { name: 'Workspace board' })).toBeVisible();
  const closedHeaderHeight = await header.evaluate(node => node.getBoundingClientRect().height);
  const searchGroup = header.locator('.workspace-header__search-group');
  const collapsedWidth = await searchGroup.evaluate(node => node.getBoundingClientRect().width);
  const collapsedHeight = await searchGroup.evaluate(node => node.getBoundingClientRect().height);
  expect(collapsedWidth).toBeCloseTo(collapsedHeight, 0);
  const findButton = header.getByRole('button', { name: 'Search tickets' });
  await findButton.click();
  await expect(findButton).toHaveCount(0);
  const searchControl = header.locator('wa-input[name="workspace-search"]');
  const search = header.getByRole('textbox', { name: 'Search tickets' });
  await expect(search).toBeFocused();
  await expect(searchControl.locator('[data-lucide="search"]')).toBeVisible();
  await expect(searchGroup).not.toHaveCSS('box-shadow', 'none');
  await expect.poll(() => searchGroup.evaluate(node => node.getBoundingClientRect().width)).toBeGreaterThan(collapsedWidth * 3);
  const openHeaderHeight = await header.evaluate(node => node.getBoundingClientRect().height);
  expect(Math.abs(openHeaderHeight - closedHeaderHeight)).toBeLessThanOrEqual(3);
  await search.fill('long-tag-example');
  await expect(page.getByRole('region', { name: 'Workspace board' }).locator('[data-component="ticket-list-row"]')).toHaveCount(1);
  await header.getByRole('button', { name: 'Columns view' }).focus();
  await expect(search).toBeVisible();
  await search.fill('');
  await header.getByRole('button', { name: 'Columns view' }).focus();
  await expect(header.getByRole('textbox', { name: 'Search tickets' })).toHaveCount(0);
  await expect(header.getByRole('button', { name: 'Search tickets' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Workspace board' }).locator('[data-component="ticket-list-row"]')).toHaveCount(5);
  await header.getByRole('button', { name: 'Sort tickets' }).click();
  await header.locator('wa-dropdown-item[data-sort="priority"]').click();
  await expect(page.getByText('Sorted by priority')).toBeVisible();
  await header.getByRole('button', { name: 'Settings view' }).click();
  await expect(header.getByRole('button', { name: 'Settings view' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('region', { name: 'Project settings' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Workspace board' })).toHaveCount(0);
  await header.getByRole('button', { name: 'List view' }).click();
  await expect(page.getByRole('listbox', { name: 'Workspace tickets' })).toBeVisible();
});

test('shows the ToolbarControlGroup variants with shared geometry', async ({ page }) => {
  await page.goto('/ux-demo?component=toolbar-control-group');
  const demo = page.getByRole('region', { name: 'ToolbarControlGroup demo' });
  const groups = demo.locator('.toolbar-control-group');
  await expect(groups).toHaveCount(4);
  for (const icon of ['arrow-down-a-z', 'star', 'ellipsis', 'pin']) await expect(demo.locator(`[data-lucide="${icon}"]`)).toBeVisible();
  const heights = await groups.evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect().height));
  expect(new Set(heights).size).toBe(1);
  const popup = demo.locator('wa-button[with-caret]');
  const caretSpacing = await popup.evaluate(node => {
    const button = node.shadowRoot?.querySelector<HTMLElement>('[part~="button"]');
    const caret = node.shadowRoot?.querySelector<HTMLElement>('[part~="caret"]');
    return button && caret ? { gap: getComputedStyle(button).gap, margin: getComputedStyle(caret).marginInlineStart, width: button.getBoundingClientRect().width, height: button.getBoundingClientRect().height } : null;
  });
  expect(caretSpacing).toEqual({ gap: '2px', margin: '2px', width: 48, height: 32 });
  const popupGroupWidth = await groups.nth(1).evaluate(node => node.getBoundingClientRect().width);
  expect(popupGroupWidth - caretSpacing!.width).toBeCloseTo(8.4, 0);
  await popup.hover();
  await expect(groups.nth(1)).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  const popupBackground = await popup.evaluate(node => {
    const button = node.shadowRoot?.querySelector<HTMLElement>('[part~="base"]');
    return button ? getComputedStyle(button).backgroundColor : null;
  });
  expect(popupBackground).toBe('rgba(0, 0, 0, 0)');
  const groupedButton = demo.locator('wa-button[aria-label="Favorite view"]').first();
  await groupedButton.hover();
  const groupedGeometry = await groupedButton.evaluate(node => {
    const button = node.shadowRoot?.querySelector<HTMLElement>('[part~="base"]');
    if (!button) return null;
    return { height: button.getBoundingClientRect().height, background: getComputedStyle(node).backgroundColor };
  });
  expect(groupedGeometry).toEqual({ height: 32, background: 'rgb(255, 255, 255)' });
  const iconAlignment = await groupedButton.evaluate(node => {
    const button = node.shadowRoot?.querySelector<HTMLElement>('[part~="base"]');
    const icon = node.querySelector<HTMLElement>('[data-lucide]');
    if (!button || !icon) return null;
    const buttonBox = button.getBoundingClientRect(); const iconBox = icon.getBoundingClientRect();
    return Math.abs((buttonBox.top + buttonBox.height / 2) - (iconBox.top + iconBox.height / 2));
  });
  expect(iconAlignment).toBeLessThan(1);
  await expect(demo.getByRole('heading', { name: 'Single button' })).toBeVisible();
});

test('expands, validates, creates, and cancels through QuickTicketComposer', async ({ page }) => {
  await page.goto('/ux-demo?component=quick-ticket-composer');
  await page.getByRole('button', { name: /New ticket/ }).click();
  const form = page.locator('[data-action="create-ticket-form"]');
  const title = form.getByRole('textbox', { name: 'Ticket title' });
  await expect(title).toBeFocused();
  await form.getByRole('button', { name: 'Create ticket' }).click();
  expect(await title.evaluate((node: HTMLInputElement) => node.checkValidity())).toBe(false);
  await expect(form).toBeVisible();
  await title.fill('Created from the UX demo');
  const category = form.locator('wa-select[name="new-ticket-category"]');
  await expect(category.locator('.ticket-category-select__icon--selected [data-lucide="list-checks"]')).toBeVisible();
  await category.click();
  await expect(category.locator('wa-option[value="bug"] [data-lucide="bug"]')).toBeVisible();
  await page.keyboard.press('Escape');
  await category.evaluate((node: HTMLElement & { value: string }) => { node.value = 'bug'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(form.locator('.ticket-category-select__icon--selected [data-lucide="bug"]')).toBeVisible();
  await form.getByRole('button', { name: 'Create ticket' }).click();
  const createdList = page.getByRole('listbox', { name: 'Recently updated tickets' });
  await expect(createdList).toContainText('Created from the UX demo');
  await expect(createdList.locator('[data-component="ticket-list-row"]').first().locator('[data-lucide="bug"]')).toBeVisible();
  await expect(page.getByText(/HS2-DEMO\d created/)).toBeVisible();
  await page.getByRole('button', { name: /New ticket/ }).click();
  await page.getByRole('textbox', { name: 'Ticket title' }).fill('Discard this');
  const cancel = page.getByRole('button', { name: /Cancel/ });
  await expect(cancel.locator('[data-lucide="x"]')).toHaveCount(0);
  await cancel.click();
  await expect(page.getByText('Ticket creation cancelled')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Ticket title' })).toHaveCount(0);
  const launcher = page.getByRole('button', { name: /New ticket/ });
  await expect(launcher).toHaveCSS('cursor', 'pointer');
  await launcher.click();
  await expect(page.getByRole('textbox', { name: 'Ticket title' })).toBeFocused();
});

test('navigates, toggles, closes, and reopens TicketInspector', async ({ page }) => {
  await page.goto('/ux-demo?component=ticket-inspector');
  const inspector = page.locator('[data-component="ticket-inspector"]');
  await expect(inspector).toContainText('Build TicketList and TicketBoard');
  await expect(inspector.getByRole('button', { name: 'Info' })).toHaveAttribute('aria-current', 'page');
  await expect(inspector.locator('[data-component="status-badge"]')).toBeVisible();
  await expect(inspector.locator('wa-select[name="inspector-category"] [data-lucide="sparkles"]')).toHaveCount(2);
  await expect(inspector.locator('wa-select[name="inspector-priority"] [data-lucide="chevron-up"]')).toHaveCount(2);
  await expect(inspector.locator('.ticket-category-select__icon--selected [data-lucide="sparkles"]')).toBeVisible();
  await expect(inspector.locator('.ticket-priority-select__icon--selected [data-lucide="chevron-up"]')).toBeVisible();
  const category = inspector.locator('wa-select[name="inspector-category"]');
  await category.evaluate((node: HTMLElement & { value: string }) => { node.value = 'bug'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(inspector.locator('.ticket-category-select__icon--selected [data-lucide="bug"]')).toBeVisible();
  await expect(inspector.locator('.ticket-category-select__icon--selected [data-lucide="sparkles"]')).toHaveCount(0);
  const priority = inspector.locator('wa-select[name="inspector-priority"]');
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'low'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(inspector.locator('.ticket-priority-select__icon--selected [data-lucide="chevron-down"]')).toBeVisible();
  await expect(inspector.locator('.ticket-priority-select__icon--selected [data-lucide="chevron-up"]')).toHaveCount(0);
  await inspector.locator('wa-button[aria-label="Change status, Started"]').click();
  await inspector.locator('wa-dropdown-item[data-inspector-status="completed"]').click();
  await expect(inspector.locator('[data-component="status-badge"]')).toHaveAttribute('data-status', 'completed');
  await expect(inspector.locator('wa-button[aria-label="Change status, Completed"]')).toBeVisible();
  await expect(inspector.locator('[data-component="ticket-info-panel"]')).toBeVisible();
  await inspector.getByRole('button', { name: 'Timeline' }).click();
  await expect(inspector.locator('[data-component="ticket-timeline"]')).toBeVisible();
  await expect(inspector.getByRole('heading', { name: 'Timeline' })).toBeVisible();
  await expect(inspector.locator('.ticket-inspector__timeline > li')).toHaveCount(2);
  await expect(inspector.getByText('2 notes total')).toBeVisible();
  await inspector.getByRole('button', { name: 'Attachments' }).click();
  await expect(inspector.locator('[data-component="ticket-attachments"]')).toBeVisible();
  await expect(inspector.getByRole('heading', { name: 'Attachments' })).toBeVisible();
  await expect(inspector.locator('[data-attachment-id]')).toHaveCount(2);
  await expect(inspector.getByText('2 attachments total')).toBeVisible();
  const star = inspector.getByRole('button', { name: 'Remove from Up Next' });
  await star.click();
  await expect(inspector.getByRole('button', { name: 'Add to Up Next' })).toBeVisible();
  await inspector.getByRole('button', { name: 'Close inspector' }).click();
  await expect(inspector).toHaveCount(0);
  await page.getByRole('button', { name: 'Open ticket inspector' }).click();
  const reopened = page.locator('[data-component="ticket-inspector"]');
  await expect(reopened).toBeVisible();
  await reopened.getByRole('button', { name: 'Info' }).click();
  await expect(reopened.locator('.ticket-category-select__icon--selected [data-lucide="bug"]')).toBeVisible();
  await expect(reopened.locator('.ticket-priority-select__icon--selected [data-lucide="chevron-down"]')).toBeVisible();
  await expect(reopened.locator('[data-component="status-badge"]')).toHaveAttribute('data-status', 'completed');
});

test('renders standalone ticket metadata and inspector-section demos', async ({ page }) => {
  for (const [id, component] of [['ticket-category-select', 'ticket-category-select'], ['ticket-priority-select', 'ticket-priority-select'], ['ticket-status-menu', 'ticket-status-menu'], ['ticket-info-panel', 'ticket-info-panel'], ['ticket-timeline', 'ticket-timeline'], ['ticket-attachments', 'ticket-attachments']] as const) {
    await page.goto(`/ux-demo?component=${id}`);
    await expect(page.locator(`[data-component="${component}"]`).or(page.locator(`.${component}`))).toBeVisible();
  }
});

test('adjusts and removes TagChip through its settings inspector', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await page.goto('/ux-demo?component=tag-chip');
  const chip = page.locator('[data-component="tag-chip"]');
  await expect(chip).toContainText('needs-design');
  const padding = await chip.evaluate(node => {
    const style = getComputedStyle(node);
    return { horizontal: Number.parseFloat(style.paddingLeft), vertical: Number.parseFloat(style.paddingTop) };
  });
  expect(padding.horizontal / padding.vertical).toBeCloseTo(2, 1);
  const toggle = page.locator('[data-action="toggle-settings"]');
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Settings');
  const closedToggleBox = await toggle.boundingBox();
  await toggle.click();
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Close settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  const openToggleBox = await toggle.boundingBox();
  expect(closedToggleBox).not.toBeNull();
  expect(openToggleBox).not.toBeNull();
  expect(Math.abs(openToggleBox!.x - closedToggleBox!.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(openToggleBox!.y - closedToggleBox!.y)).toBeLessThanOrEqual(1);
  const inspector = page.getByRole('complementary', { name: 'TagChip settings' });
  await expect(inspector).toBeVisible();
  const [detailBox, inspectorBox] = await Promise.all([
    page.locator('.demo-detail').boundingBox(),
    inspector.boundingBox(),
  ]);
  expect(detailBox).not.toBeNull();
  expect(inspectorBox).not.toBeNull();
  expect(detailBox!.x + detailBox!.width).toBeLessThanOrEqual(inspectorBox!.x + 1);
  const label = page.getByRole('textbox', { name: 'Label' });
  await label.fill('server');
  await expect(chip).toContainText('server');
  await expect(inspector).toBeVisible();
  await page.locator('wa-select[name="variant"]').evaluate((node: HTMLElement & { value: string }) => {
    node.value = 'success'; node.dispatchEvent(new Event('change', { bubbles: true }));
  });
  await expect(chip).toHaveAttribute('variant', 'success');
  await expect(inspector).toBeVisible();
  await inspector.locator('wa-checkbox[name="pill"]').click();
  await expect(inspector).toBeVisible();
  await chip.locator('[part~="remove-button"]').click();
  await expect(page.getByText('Remove requested for demo-tag')).toBeVisible();
  await expect(inspector).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(label).toHaveJSProperty('value', 'needs-design');
  await expect(page.locator('wa-select[name="variant"]')).toHaveJSProperty('value', 'neutral');
  await expect(page.locator('wa-select[name="appearance"]')).toHaveJSProperty('value', 'filled');
  await expect(page.locator('wa-select[name="size"]')).toHaveJSProperty('value', 'small');
  await expect(inspector.locator('wa-checkbox[name="removable"]')).toHaveJSProperty('checked', true);
  await expect(inspector.locator('wa-checkbox[name="pill"]')).toHaveJSProperty('checked', false);
  await expect(inspector.locator('wa-checkbox[name="disabled"]')).toHaveJSProperty('checked', false);
  await expect(chip).toContainText('needs-design');
  await expect(chip).toHaveAttribute('variant', 'neutral');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await expect(inspector).toBeVisible();
  await toggle.click();
  await expect(inspector).toBeHidden();
  await expect(toggle).toContainText('Settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
});

test('uses semantic cursors across native and Web Awesome interactions', async ({ page }) => {
  await page.goto('/ux-demo?component=ticket-row');
  await expect(page.locator('[data-component="ticket-list-row"]')).toHaveCSS('cursor', 'pointer');
  await expect(page.locator('[data-action="toggle-row-up-next"]')).toHaveCSS('cursor', 'pointer');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'TicketRow settings' });
  await expect(inspector.getByRole('textbox', { name: 'Title' })).toHaveCSS('cursor', 'text');
  const selectCursor = await inspector.locator('wa-select[name="status"]').evaluate(node => getComputedStyle(node.shadowRoot!.querySelector('[part~="combobox"]')!).cursor);
  expect(selectCursor).toBe('pointer');
  const checkboxCursor = await inspector.locator('wa-checkbox[name="up-next"]').evaluate(node => getComputedStyle(node.shadowRoot!.querySelector('[part~="checkbox"]')!).cursor);
  expect(checkboxCursor).toBe('pointer');
  const buttonCursor = await inspector.locator('wa-button[data-action="reset-settings"]').evaluate(node => getComputedStyle(node.shadowRoot!.querySelector('[part~="base"]')!).cursor);
  expect(buttonCursor).toBe('pointer');
  await page.locator('[data-action="toggle-settings"]').click();
  await page.locator('[data-component="ticket-list-row"]').click({ button: 'right' });
  await expect(page.getByRole('menu', { name: 'Ticket actions' }).locator('wa-dropdown-item').first()).toHaveCSS('cursor', 'pointer');
  await page.goto('/ux-demo?component=quick-ticket-composer');
  await page.getByRole('button', { name: /New ticket/ }).click();
  const create = page.locator('wa-button[type="submit"]');
  await create.evaluate(node => { node.setAttribute('disabled', ''); });
  const disabledCursor = await create.evaluate(node => getComputedStyle(node.shadowRoot!.querySelector('[part~="base"]')!).cursor);
  expect(disabledCursor).toBe('not-allowed');
});

test('exercises the five ProjectSidebar component demos and their controlled transitions', async ({ page }) => {
  await page.goto('/ux-demo?component=project-summary');
  const summary = page.locator('[data-component="project-summary"]');
  await expect(summary).toContainText('6 completed today');
  await expect(summary).toContainText('3 in progress');
  await expect(summary).not.toContainText('%');
  await expect(summary.locator('[data-bar]')).toHaveCount(7);
  await expect(summary.locator('[data-zero="true"]')).toHaveCount(1);
  await expect(summary.locator('[data-zero="true"]')).toHaveCSS('height', '1px');
  await expect(summary.locator('[data-zero="true"]')).toHaveCSS('background-color', 'rgb(174, 177, 186)');

  await page.goto('/ux-demo?component=repository-summary');
  const repository = page.getByRole('button', { name: 'Repository status for feature/client-sidebar' });
  await expect(repository.locator('[data-lucide="git-branch"]')).toHaveCount(1);
  await expect(repository.locator('.repository-summary__branch-name')).toHaveCSS('direction', 'rtl');
  await expect(repository.locator('.repository-summary__branch-name')).toHaveCSS('text-overflow', 'ellipsis');
  await repository.click();
  await expect(page.getByText('Repository status requested.')).toBeVisible();

  await page.goto('/ux-demo?component=view-navigation');
  const views = page.locator('[data-component="view-navigation"]');
  const navigationGeometry = await views.evaluate(node => {
    const header = node.querySelector('header')!.getBoundingClientRect();
    const button = node.querySelector('li button')!.getBoundingClientRect();
    const icon = node.querySelector('li button svg')!.getBoundingClientRect();
    return { headerLeft: header.left, buttonLeft: button.left, iconLeft: icon.left, headerRight: header.right, buttonRight: button.right };
  });
  expect(navigationGeometry.headerLeft - navigationGeometry.buttonLeft).toBeCloseTo(5.2, 0);
  expect(navigationGeometry.buttonRight - navigationGeometry.headerRight).toBeCloseTo(5.2, 0);
  expect(navigationGeometry.iconLeft).toBeCloseTo(navigationGeometry.headerLeft, 0);
  await expect(views.getByRole('button', { name: /All Tickets/ })).toHaveAttribute('aria-current', 'page');
  await views.getByRole('button', { name: /Needs Review/ }).click();
  await expect(views.getByRole('button', { name: /Needs Review/ })).toHaveAttribute('aria-current', 'page');
  await expect(views.getByRole('button', { name: /All Tickets/ })).not.toHaveAttribute('aria-current', 'page');
  await views.getByRole('button', { name: 'Add view' }).click();
  await expect(page.getByText('New view editor requested.')).toBeVisible();

  await page.goto('/ux-demo?component=command-navigation');
  const commands = page.locator('[data-component="command-navigation"]');
  const heading = commands.getByRole('button', { name: /Project commands/ });
  await expect(heading).toHaveAttribute('aria-expanded', 'true');
  await commands.getByRole('button', { name: 'Verify project' }).click();
  await expect(commands.getByRole('button', { name: /Running Verify project/ })).toHaveAttribute('aria-pressed', 'true');
  await commands.getByRole('button', { name: /Running Verify project/ }).click();
  await expect(commands.getByRole('button', { name: 'Verify project' })).toHaveAttribute('aria-pressed', 'false');
  await heading.click();
  await expect(commands.getByRole('button', { name: 'Verify project' })).toHaveCount(0);
  await expect(heading).toHaveAttribute('aria-expanded', 'false');

  await page.goto('/ux-demo?component=drive-control');
  const drive = page.locator('[data-component="drive-control"]');
  await expect(drive).toHaveAttribute('aria-label', 'Start Codex');
  await drive.click();
  await expect(drive).toHaveAttribute('aria-label', 'Stop Codex');
  await expect(drive.locator('[data-lucide="square"]')).toHaveCount(1);
  await drive.click();
  await expect(drive).toHaveAttribute('aria-label', 'Start Codex');
  await expect(drive.locator('[data-lucide="play"]')).toHaveCount(1);
});

test('composes and operates the complete ProjectSidebar demo', async ({ page }) => {
  await page.goto('/ux-demo?component=project-sidebar');
  const sidebar = page.locator('[data-component="project-sidebar"]');
  await expect(sidebar).toBeVisible();
  for (const component of ['project-summary', 'repository-summary', 'view-navigation', 'command-navigation', 'drive-control']) await expect(sidebar.locator(`[data-component="${component}"]`)).toHaveCount(1);
  await sidebar.getByRole('button', { name: /Backlog/ }).click();
  await expect(sidebar.getByRole('button', { name: /Backlog/ })).toHaveAttribute('aria-current', 'page');
  await sidebar.getByRole('button', { name: 'Verify project' }).click();
  await expect(sidebar.getByRole('button', { name: /Running Verify project/ })).toHaveAttribute('aria-pressed', 'true');
  await sidebar.getByRole('button', { name: 'Start Codex' }).click();
  await expect(sidebar.getByRole('button', { name: 'Stop Codex' })).toBeVisible();
  const handle = page.getByRole('separator', { name: 'Resize project sidebar' });
  await expect(handle).toHaveAttribute('aria-valuenow', '640');
  const handleBox = await handle.boundingBox();
  expect(handleBox).not.toBeNull();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2, handleBox!.y + handleBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2, handleBox!.y - 230, { steps: 5 });
  await page.mouse.up();
  await expect(handle).toHaveAttribute('aria-valuenow', '400');
  const scrollState = await sidebar.evaluate(node => {
    const content = node.querySelector('.project-sidebar__content')!;
    const drive = node.querySelector('.drive-control')!;
    return { contentClientHeight: content.clientHeight, contentScrollHeight: content.scrollHeight, sidebarBottom: node.getBoundingClientRect().bottom, driveBottom: drive.getBoundingClientRect().bottom };
  });
  expect(scrollState.contentScrollHeight).toBeGreaterThan(scrollState.contentClientHeight);
  expect(scrollState.sidebarBottom - scrollState.driveBottom).toBeLessThan(16);
  await handle.focus();
  await page.keyboard.press('ArrowDown');
  await expect(handle).toHaveAttribute('aria-valuenow', '424');
});
