import { expect, test } from '@playwright/test';

test('navigates the catalog and preserves URL-addressable selection', async ({ page }) => {
  await page.goto('/ux-demo');
  await expect(page.getByRole('heading', { name: 'UX components' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: /TicketRow/ }).click();
  await expect(page).toHaveURL('/ux-demo?component=ticket-row');
  await expect(page.getByRole('heading', { name: 'TicketRow', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'TicketRow demo' })).toBeVisible();
  await expect(page.getByRole('complementary', { name: 'Component catalog' }).getByText('Uses')).toHaveCount(0);
  const relationships = page.locator('.demo-relationships');
  await expect(relationships.getByRole('button', { name: /Related components/ })).toBeVisible();
  await relationships.getByRole('button', { name: /Related components/ }).click();
  await expect(relationships.getByRole('heading', { name: 'Uses' })).toBeVisible();
  await relationships.locator('wa-dropdown-item', { hasText: 'TagChip' }).click();
  await expect(page).toHaveURL('/ux-demo?component=tag-chip');
  await relationships.getByRole('button', { name: /Related components/ }).click();
  await expect(relationships.getByRole('heading', { name: 'Used by' })).toBeVisible();
  await relationships.locator('wa-dropdown-item', { hasText: 'TicketRow' }).click();
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
});

test('round-trips StatusBadge controls through reset and a post-reset edit', async ({ page }) => {
  await page.goto('/ux-demo?component=status-badge');
  const badge = page.locator('[data-component="status-badge"]');
  await expect(badge).toContainText('Started');
  await expect(badge.locator('[data-lucide="clock"]')).toHaveAttribute('aria-hidden', 'true');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'StatusBadge settings' });
  const status = inspector.locator('wa-select[name="status"]');
  const icon = inspector.locator('wa-checkbox[name="show-icon"]');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toContainText('Verified');
  await expect(badge.locator('[data-lucide="badge-check"]')).toHaveCount(1);
  await icon.click();
  await expect(badge.locator('.status-badge__icon')).toHaveCount(0);
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(icon).toHaveJSProperty('checked', true);
  await expect(badge).toContainText('Started');
  await expect(badge.locator('[data-lucide="clock"]')).toHaveCount(1);
  await expect(badge.locator('.status-badge__icon')).toHaveCount(1);
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'completed'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toContainText('Completed');
  await expect(badge.locator('[data-lucide="circle-check"]')).toHaveCount(1);
});

test('round-trips every TicketRow setting and selection action', async ({ page }) => {
  await page.goto('/ux-demo?component=ticket-row');
  const row = page.locator('[data-component="ticket-list-row"]');
  await expect(row).toContainText('Build the first client ticket list');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'TicketRow settings' });
  const title = inspector.getByRole('textbox', { name: 'Title' });
  const category = inspector.getByRole('textbox', { name: 'Category' });
  const tags = inspector.getByRole('textbox', { name: 'Tags (comma separated)' });
  const agent = inspector.getByRole('textbox', { name: 'Active agent' });
  const updated = inspector.getByRole('textbox', { name: 'Updated label' });
  const status = inspector.locator('wa-select[name="status"]');
  const priority = inspector.locator('wa-select[name="priority"]');
  const categoryIcon = inspector.locator('wa-select[name="category-icon"]');
  const categoryColor = inspector.locator('wa-select[name="category-color"]');
  const upNext = inspector.locator('wa-checkbox[name="up-next"]');
  const blocked = inspector.locator('wa-checkbox[name="blocked"]');
  const needsReview = inspector.locator('wa-checkbox[name="needs-review"]');
  const selected = inspector.locator('wa-checkbox[name="selected"]');
  const busy = inspector.locator('wa-checkbox[name="busy"]');
  await title.fill('Fix selection synchronization');
  await category.fill('bug');
  await tags.fill('client, regression');
  await agent.fill('Codex');
  await updated.fill('Now');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'urgent'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await categoryIcon.evaluate((node: HTMLElement & { value: string }) => { node.value = 'bug'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await categoryColor.evaluate((node: HTMLElement & { value: string }) => { node.value = '#ef4444'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await upNext.click();
  await blocked.click();
  await needsReview.click();
  await selected.click();
  await busy.click();
  await expect(row).toContainText('Fix selection synchronization');
  await expect(row).toContainText('Verified');
  await expect(row.locator('[data-lucide="bug"]')).toHaveCount(1);
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('color', 'rgb(239, 68, 68)');
  await categoryColor.evaluate((node: HTMLElement & { value: string }) => { node.value = '#e5e7eb'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('color', 'rgb(156, 163, 175)');
  await categoryIcon.evaluate((node: HTMLElement & { value: string }) => { node.value = ''; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('.ticket-list-row__category--label')).toHaveText('BUG');
  await expect(row.locator('.ticket-list-row__category--label')).toHaveCSS('color', 'rgb(156, 163, 175)');
  await expect(row.locator('.ticket-list-row__category--label')).toHaveCSS('width', '32px');
  await expect(row).toContainText('regression');
  await expect(row.locator('[data-lucide="star"]')).toHaveCount(1);
  await expect(row.locator('[data-action="toggle-row-up-next"]')).not.toHaveClass(/active/);
  await expect(row).toContainText('Codex');
  await expect(row).toContainText('Now');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(row.locator('[data-lucide="chevrons-up"]')).toHaveCount(1);
  await expect(row.locator('.ticket-list-row__priority')).toHaveCSS('color', 'rgb(239, 68, 68)');
  await expect(row.locator('.ticket-list-row__indicator')).toHaveClass(/needs-review/);
  await row.click();
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(row).toHaveAttribute('data-selected', 'false');
  await expect(page.getByText('Ticket deselected')).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(title).toHaveJSProperty('value', 'Build the first client ticket list');
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(priority).toHaveJSProperty('value', 'high');
  await expect(category).toHaveJSProperty('value', 'feature');
  await expect(tags).toHaveJSProperty('value', 'client, ux');
  await expect(agent).toHaveJSProperty('value', 'Claude');
  await expect(updated).toHaveJSProperty('value', '1h ago');
  await expect(upNext).toHaveJSProperty('checked', true);
  await expect(blocked).toHaveJSProperty('checked', false);
  await expect(needsReview).toHaveJSProperty('checked', false);
  await expect(categoryIcon).toHaveJSProperty('value', 'sparkles');
  await expect(categoryColor).toHaveJSProperty('value', '#3b82f6');
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(busy).toHaveJSProperty('checked', true);
  await expect(row).toContainText('Build the first client ticket list');
  await expect(row).toContainText('Started');
  await expect(row.locator('[data-action="toggle-row-up-next"]')).toHaveClass(/active/);
  await expect(row.locator('.ticket-list-row__category')).toHaveCSS('width', '32px');
  await expect(row.locator('.ticket-list-row__indicator')).toHaveClass(/up-next/);
  await expect(row).toContainText('Claude');
  await expect(row).toContainText('1h ago');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await title.fill('Post-reset edit works');
  await expect(row).toContainText('Post-reset edit works');
  await row.focus();
  await page.keyboard.press('Enter');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(selected).toHaveJSProperty('checked', true);

  const star = row.locator('[data-action="toggle-row-up-next"]');
  const starBox = await star.boundingBox();
  expect(starBox).not.toBeNull();
  await star.click();
  await expect(upNext).toHaveJSProperty('checked', false);
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(star).not.toHaveClass(/active/);
  await star.focus();
  await page.keyboard.press('Enter');
  await expect(upNext).toHaveJSProperty('checked', true);
  await expect(star).toHaveClass(/active/);

  await row.click({ button: 'right' });
  const menu = page.getByRole('menu', { name: 'Ticket actions' });
  await expect(menu).toBeVisible();
  const menuItems = menu.locator('wa-dropdown-item');
  await expect(menuItems).toHaveCount(9);
  expect(await menuItems.evaluateAll(items => items.every(item => item.querySelector('[data-lucide]') !== null))).toBe(true);
  await expect(row).toHaveAttribute('data-selected', 'true');
  await menu.getByText('Toggle Up Next', { exact: true }).click();
  await expect(star).not.toHaveClass(/active/);
  await expect(upNext).toHaveJSProperty('checked', false);
  await expect(page.getByText('Toggle Up Next selected')).toBeVisible();

  await title.fill('A deliberately long ticket title that must wrap across no more than two lines while the AI working indicator remains entirely visible');
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'default'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(row.locator('[data-lucide="minus"]')).toHaveCount(1);
  await tags.fill('client, regression, server, ux');
  await row.evaluate((node: HTMLElement) => { node.style.width = '320px'; });
  const [rowBox, timeBox, slugBox, identityBox] = await Promise.all([row.boundingBox(), row.locator('.ticket-list-row__updated').boundingBox(), row.locator('.ticket-list-row__slug').boundingBox(), row.locator('.ticket-list-row__identity').boundingBox()]);
  expect(rowBox).not.toBeNull(); expect(timeBox).not.toBeNull(); expect(slugBox).not.toBeNull(); expect(identityBox).not.toBeNull();
  expect(timeBox!.x + timeBox!.width).toBeLessThanOrEqual(rowBox!.x + rowBox!.width);
  expect(Math.abs(timeBox!.y + timeBox!.height - (slugBox!.y + slugBox!.height))).toBeLessThanOrEqual(3);
  expect(identityBox!.height).toBeLessThanOrEqual(43);
  await expect(row.locator('.ticket-list-row__identity')).toHaveCSS('display', 'block');
  await expect(row.locator('.ticket-list-row__slug')).toHaveCSS('display', 'inline-block');
  await expect(row.locator('.ticket-list-row__priority')).toHaveCSS('display', 'inline');
  expect(await row.locator('.ticket-list-row__identity > *').evaluateAll(elements => elements.map(element => element.className || element.tagName.toLowerCase()))).toEqual([
    'ticket-list-row__slug', 'ticket-list-row__priority', 'strong',
  ]);
  await expect(row.locator('[data-component="tag-chip"]')).toHaveCount(4);
  for (const chip of await row.locator('[data-component="tag-chip"]').all()) await expect(chip).toBeVisible();
});

test('adjusts and removes TagChip through its settings inspector', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await page.goto('/ux-demo?component=tag-chip');
  const chip = page.locator('[data-component="tag-chip"]');
  await expect(chip).toContainText('needs-design');
  const padding = await chip.evaluate(node => {
    const style = getComputedStyle(node);
    return { horizontal: Number.parseFloat(style.paddingLeft), vertical: Number.parseFloat(style.paddingTop) };
  });
  expect(padding.horizontal / padding.vertical).toBeCloseTo(2, 1);
  const toggle = page.locator('[data-action="toggle-settings"]');
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Settings');
  const closedToggleBox = await toggle.boundingBox();
  await toggle.click();
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Close settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  const openToggleBox = await toggle.boundingBox();
  expect(closedToggleBox).not.toBeNull();
  expect(openToggleBox).not.toBeNull();
  expect(Math.abs(openToggleBox!.x - closedToggleBox!.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(openToggleBox!.y - closedToggleBox!.y)).toBeLessThanOrEqual(1);
  const inspector = page.getByRole('complementary', { name: 'TagChip settings' });
  await expect(inspector).toBeVisible();
  const [detailBox, inspectorBox] = await Promise.all([
    page.locator('.demo-detail').boundingBox(),
    inspector.boundingBox(),
  ]);
  expect(detailBox).not.toBeNull();
  expect(inspectorBox).not.toBeNull();
  expect(detailBox!.x + detailBox!.width).toBeLessThanOrEqual(inspectorBox!.x + 1);
  const label = page.getByRole('textbox', { name: 'Label' });
  await label.fill('server');
  await expect(chip).toContainText('server');
  await expect(inspector).toBeVisible();
  await page.locator('wa-select[name="variant"]').evaluate((node: HTMLElement & { value: string }) => {
    node.value = 'success'; node.dispatchEvent(new Event('change', { bubbles: true }));
  });
  await expect(chip).toHaveAttribute('variant', 'success');
  await expect(inspector).toBeVisible();
  await inspector.locator('wa-checkbox[name="pill"]').click();
  await expect(inspector).toBeVisible();
  await chip.locator('[part~="remove-button"]').click();
  await expect(page.getByText('Remove requested for demo-tag')).toBeVisible();
  await expect(inspector).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(label).toHaveJSProperty('value', 'needs-design');
  await expect(page.locator('wa-select[name="variant"]')).toHaveJSProperty('value', 'neutral');
  await expect(page.locator('wa-select[name="appearance"]')).toHaveJSProperty('value', 'filled');
  await expect(page.locator('wa-select[name="size"]')).toHaveJSProperty('value', 'small');
  await expect(inspector.locator('wa-checkbox[name="removable"]')).toHaveJSProperty('checked', true);
  await expect(inspector.locator('wa-checkbox[name="pill"]')).toHaveJSProperty('checked', false);
  await expect(inspector.locator('wa-checkbox[name="disabled"]')).toHaveJSProperty('checked', false);
  await expect(chip).toContainText('needs-design');
  await expect(chip).toHaveAttribute('variant', 'neutral');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await expect(inspector).toBeVisible();
  await toggle.click();
  await expect(inspector).toBeHidden();
  await expect(toggle).toContainText('Settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
});
