import { expect, test } from '@playwright/test';

test('navigates the catalog and preserves URL-addressable selection', async ({ page }) => {
  await page.goto('/ux-demo');
  await expect(page.getByRole('heading', { name: 'UX components' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
  await page.getByRole('link', { name: /TicketRow/ }).click();
  await expect(page).toHaveURL('/ux-demo?component=ticket-row');
  await expect(page.getByRole('heading', { name: 'TicketRow', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'TicketRow demo' })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'TagChip', exact: true })).toBeVisible();
});

test('round-trips StatusBadge controls through reset and a post-reset edit', async ({ page }) => {
  await page.goto('/ux-demo?component=status-badge');
  const badge = page.locator('[data-component="status-badge"]');
  await expect(badge).toContainText('Started');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'StatusBadge settings' });
  const status = inspector.locator('wa-select[name="status"]');
  const icon = inspector.locator('wa-checkbox[name="show-icon"]');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await icon.click();
  await expect(badge).toContainText('Verified');
  await expect(badge.locator('.status-badge__icon')).toHaveCount(0);
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(icon).toHaveJSProperty('checked', true);
  await expect(badge).toContainText('Started');
  await expect(badge.locator('.status-badge__icon')).toHaveCount(1);
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'completed'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await expect(badge).toContainText('Completed');
});

test('round-trips every TicketRow setting and selection action', async ({ page }) => {
  await page.goto('/ux-demo?component=ticket-row');
  const row = page.locator('[data-component="ticket-list-row"]');
  await expect(row).toContainText('Build the first client ticket list');
  await page.locator('[data-action="toggle-settings"]').click();
  const inspector = page.getByRole('complementary', { name: 'TicketRow settings' });
  const title = inspector.getByRole('textbox', { name: 'Title' });
  const category = inspector.getByRole('textbox', { name: 'Category' });
  const tags = inspector.getByRole('textbox', { name: 'Tags (comma separated)' });
  const status = inspector.locator('wa-select[name="status"]');
  const priority = inspector.locator('wa-select[name="priority"]');
  const upNext = inspector.locator('wa-checkbox[name="up-next"]');
  const selected = inspector.locator('wa-checkbox[name="selected"]');
  const busy = inspector.locator('wa-checkbox[name="busy"]');
  await title.fill('Fix selection synchronization');
  await category.fill('bug');
  await tags.fill('client, regression');
  await status.evaluate((node: HTMLElement & { value: string }) => { node.value = 'verified'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await priority.evaluate((node: HTMLElement & { value: string }) => { node.value = 'urgent'; node.dispatchEvent(new Event('change', { bubbles: true })); });
  await upNext.click();
  await selected.click();
  await busy.click();
  await expect(row).toContainText('Fix selection synchronization');
  await expect(row).toContainText('Verified');
  await expect(row).toContainText('bug');
  await expect(row).toContainText('regression');
  await expect(row).not.toContainText('Up Next');
  await expect(row).not.toContainText('AI working');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(row.locator('.ticket-list-row__priority')).toHaveClass(/urgent/);
  await row.click();
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(row).toHaveAttribute('data-selected', 'false');
  await expect(page.getByText('Ticket deselected')).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(title).toHaveJSProperty('value', 'Build the first client ticket list');
  await expect(status).toHaveJSProperty('value', 'started');
  await expect(priority).toHaveJSProperty('value', 'high');
  await expect(category).toHaveJSProperty('value', 'feature');
  await expect(tags).toHaveJSProperty('value', 'client, ux');
  await expect(upNext).toHaveJSProperty('checked', true);
  await expect(selected).toHaveJSProperty('checked', false);
  await expect(busy).toHaveJSProperty('checked', true);
  await expect(row).toContainText('Build the first client ticket list');
  await expect(row).toContainText('Started');
  await expect(row).toContainText('Up Next');
  await expect(row).toContainText('AI working');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await title.fill('Post-reset edit works');
  await expect(row).toContainText('Post-reset edit works');
  await row.focus();
  await page.keyboard.press('Enter');
  await expect(row).toHaveAttribute('data-selected', 'true');
  await expect(selected).toHaveJSProperty('checked', true);
});

test('adjusts and removes TagChip through its settings inspector', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await page.goto('/ux-demo?component=tag-chip');
  const chip = page.locator('[data-component="tag-chip"]');
  await expect(chip).toContainText('needs-design');
  const toggle = page.locator('[data-action="toggle-settings"]');
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Settings');
  const closedToggleBox = await toggle.boundingBox();
  await toggle.click();
  await expect(toggle).toHaveCount(1);
  await expect(toggle).toContainText('Close settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  const openToggleBox = await toggle.boundingBox();
  expect(closedToggleBox).not.toBeNull();
  expect(openToggleBox).not.toBeNull();
  expect(Math.abs(openToggleBox!.x - closedToggleBox!.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(openToggleBox!.y - closedToggleBox!.y)).toBeLessThanOrEqual(1);
  const inspector = page.getByRole('complementary', { name: 'TagChip settings' });
  await expect(inspector).toBeVisible();
  const [detailBox, inspectorBox] = await Promise.all([
    page.locator('.demo-detail').boundingBox(),
    inspector.boundingBox(),
  ]);
  expect(detailBox).not.toBeNull();
  expect(inspectorBox).not.toBeNull();
  expect(detailBox!.x + detailBox!.width).toBeLessThanOrEqual(inspectorBox!.x + 1);
  const label = page.getByRole('textbox', { name: 'Label' });
  await label.fill('server');
  await expect(chip).toContainText('server');
  await expect(inspector).toBeVisible();
  await page.locator('wa-select[name="variant"]').evaluate((node: HTMLElement & { value: string }) => {
    node.value = 'success'; node.dispatchEvent(new Event('change', { bubbles: true }));
  });
  await expect(chip).toHaveAttribute('variant', 'success');
  await expect(inspector).toBeVisible();
  await inspector.locator('wa-checkbox[name="pill"]').click();
  await expect(inspector).toBeVisible();
  await chip.locator('[part~="remove-button"]').click();
  await expect(page.getByText('Remove requested for demo-tag')).toBeVisible();
  await expect(inspector).toBeVisible();
  await inspector.getByRole('button', { name: 'Reset' }).click();
  await expect(label).toHaveJSProperty('value', 'needs-design');
  await expect(page.locator('wa-select[name="variant"]')).toHaveJSProperty('value', 'neutral');
  await expect(page.locator('wa-select[name="appearance"]')).toHaveJSProperty('value', 'filled-outlined');
  await expect(page.locator('wa-select[name="size"]')).toHaveJSProperty('value', 'small');
  await expect(inspector.locator('wa-checkbox[name="removable"]')).toHaveJSProperty('checked', true);
  await expect(inspector.locator('wa-checkbox[name="pill"]')).toHaveJSProperty('checked', true);
  await expect(inspector.locator('wa-checkbox[name="disabled"]')).toHaveJSProperty('checked', false);
  await expect(chip).toContainText('needs-design');
  await expect(chip).toHaveAttribute('variant', 'neutral');
  await expect(page.getByText('No actions yet')).toBeVisible();
  await expect(inspector).toBeVisible();
  await toggle.click();
  await expect(inspector).toBeHidden();
  await expect(toggle).toContainText('Settings');
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
});
