import './ai-conversation.css';

import {Activity,Bot,CircleAlert,MessageSquare,Send,Square,X} from 'lucide';

import {type ConversationActivity,type ConversationMessage,type ConversationUsage,formatConversationCost,formatConversationTokens} from '../ai-conversation';
import type { PermissionItem } from '../permission-notifications';
import {AIContentLabel} from './ai-content-label';
import {DialogHeader} from './dialog-layout';
import {LucideIcon} from './lucide-icon';
import {MarkdownPreview} from './markdown-preview';
import {PermissionRequestCard} from './permission-request-card';

export interface AIConversationProps {open:boolean;tool:string;sessionId?:string;messages:ConversationMessage[];draft:string;busy:boolean;progress?:string;interruptible:boolean;permissions?:PermissionItem[];activity?:ConversationActivity[];totalUsage?:ConversationUsage;error?:string;feedbackAvailable?:boolean;presentation?:'dialog'|'embedded'}

function UsageLine({usage,label='Turn usage'}:{usage:ConversationUsage;label?:string}){const total=usage.tokensIn+usage.tokensOut;return <p class="ai-conversation__usage" aria-label={`${label}: ${usage.tokensIn} input tokens, ${usage.tokensOut} output tokens, ${formatConversationCost(usage.costUsd)}`}><span>{formatConversationTokens(total)} tokens</span><span>{formatConversationCost(usage.costUsd)}</span>{usage.model&&<span title={usage.model}>{usage.model}</span>}</p>}

export function AIConversation({open,tool,sessionId,messages,draft,busy,progress,interruptible,permissions=[],activity=[],totalUsage,error,feedbackAvailable=false,presentation='dialog'}:AIConversationProps){
  const actions=<>{totalUsage&&<span class="ai-conversation__header-usage"><UsageLine usage={totalUsage} label="Conversation usage"/></span>}{busy&&interruptible&&<wa-button class="ai-conversation__header-action" appearance="plain" size="small" data-action="stop-conversation" aria-label={`Stop ${tool}`} title={`Stop ${tool}`}><LucideIcon icon={Square} name="square"/></wa-button>}<wa-button class="ai-conversation__header-action" appearance="plain" size="small" data-action="close-conversation" aria-label="Close conversation" title="Close conversation"><LucideIcon icon={X} name="x"/></wa-button></>;
  const transcript=<section class="ai-conversation__transcript" aria-label="Conversation transcript" aria-live="polite">{messages.length===0&&<div class="ai-conversation__empty"><LucideIcon icon={MessageSquare} name="message-square"/><strong>Start a conversation</strong><p>Ask {tool} about this project or send it a task.</p></div>}{messages.map(message=><article class={`ai-conversation__message ai-conversation__message--${message.role}`} data-message-id={message.id} data-status={message.status} aria-label={message.role==='assistant'?`AI-generated response by ${tool}`:undefined}><strong>{message.role==='user'?'You':<AIContentLabel tool={tool} feedbackTarget={feedbackAvailable&&message.status==='completed'?`conversation:${message.id}`:undefined}/>}</strong>{message.content?<MarkdownPreview source={message.content}/>:<p aria-label="Awaiting response"> </p>}{message.usage&&<UsageLine usage={message.usage}/>}</article>)}{activity.length>0&&<section class="ai-conversation__activity" aria-label="AI-generated activity summaries; may contain errors"><header><span><LucideIcon icon={Activity} name="activity"/><strong>Activity</strong></span><AIContentLabel mayContainErrors/></header><ol>{activity.map(item=><li data-activity-id={item.id} data-importance={item.importance} aria-label={`AI-generated activity by ${item.tool}; may contain errors: ${item.summary}`}><AIContentLabel tool={item.tool} mayContainErrors feedbackTarget={feedbackAvailable?`activity:${item.id}`:undefined}/><span>{item.summary}</span></li>)}</ol></section>}{permissions.map(item=><div data-permission-key={item.key}><PermissionRequestCard item={item} presentation="list"/></div>)}{busy&&progress&&<p class="ai-conversation__progress" role="status"><LucideIcon icon={Bot} name="bot"/>{progress}</p>}{error&&<p class="ai-conversation__error" role="alert"><LucideIcon icon={CircleAlert} name="circle-alert"/><span><strong>Conversation unavailable</strong>{error}</span></p>}</section>;
  const composer=<form slot={presentation==='dialog'?'footer':undefined} class="ai-conversation__composer" data-action="send-conversation-turn"><label><span class="ai-conversation__composer-label">Message {tool}</span><textarea name="conversation-draft" aria-label={`Message ${tool}`} placeholder={`Message ${tool}…`} rows={2} disabled={busy}>{draft}</textarea><small>Enter to send · Shift+Enter for a new line</small></label><wa-button appearance="accent" type="submit" disabled={busy||!draft.trim()} aria-label={`Send message to ${tool}`} title={busy?`${tool} is still working`:`Send message to ${tool}`}><LucideIcon icon={Send} name="send"/></wa-button></form>;
  if(presentation==='embedded')return <section class="ai-conversation ai-conversation--embedded" data-component="ai-conversation" data-presentation="embedded" aria-label={`${tool} conversation`}>{transcript}{composer}</section>;
  return <wa-dialog class="ai-conversation" data-component="ai-conversation" data-presentation="dialog" label={`${tool} conversation`} open={open||undefined} without-header with-footer><DialogHeader title={`${tool} conversation`} titleId="ai-conversation-title" summary={sessionId?`Session ${sessionId}`:'Ask about this project or send a task.'} icon={<LucideIcon icon={Bot} name="bot"/>} actions={actions}/>{transcript}{composer}</wa-dialog>;
}
