import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { AIContentLabel } from './ai-content-label';

describe('AIContentLabel', () => {
  it('renders persistent factual attribution and consequence-labeled optional feedback', () => {
    const markup = String(AIContentLabel({ tool: 'Claude', mayContainErrors: true, feedbackTarget: 'note:one' }));
    expect(markup).toContain('aria-label="AI-generated by Claude; may contain errors"');
    expect(markup).toContain('Helpful — keep suggestions like this');
    expect(markup).toContain('Not helpful — stop suggestions like this');
    expect(markup).toContain('data-ai-feedback-target="note:one"');
  });
  it('keeps AI provenance while announcing a later human edit', () => {
    const markup = String(AIContentLabel({ tool: 'Codex', humanEdited: true }));
    expect(markup).toContain('aria-label="AI-generated by Codex; edited by human"');
    expect(markup).toContain('AI-generated by Codex<span> · edited by human</span>');
  });
  it('exposes the inherit tone as a variant instead of consumer color overrides', () => {
    expect(String(AIContentLabel({}))).toContain('data-component="text" data-tone="quiet"');
    expect(String(AIContentLabel({ tone: 'quiet' }))).toContain('data-component="text" data-tone="quiet"');
    expect(String(AIContentLabel({ tone: 'inherit' }))).toContain('data-tone="inherit"');
    expect(String(AIContentLabel({ tone: 'inherit' }))).toContain('data-component="text" data-tone="default"');
    const css = readFileSync(new URL('./ai-content-label.css', import.meta.url), 'utf8');
    expect(css).not.toContain('.kui-text');
  });
  it('uses semantic spacing while keeping feedback targets and glyphs explicit geometry', () => {
    const css = readFileSync(new URL('./ai-content-label.css', import.meta.url), 'utf8');
    expect(css).not.toContain('--wa-space-');
    expect(css).toMatch(/\.ai-content-label \{[^}]*gap: var\(--kui-space-xs\)/);
    expect(css).toMatchSource(/__attribution \{ gap: var\(--kui-space-2xs\)/);
    expect(css).toMatchSource(/__feedback \{ gap: var\(--kui-space-2xs\)/);
    expect(css).toMatchSource(/__feedback button \{[^}]*width: remify\(32px\); height: remify\(32px\)/);
    // Glyphs are sized by the LucideIcon size prop, never by CSS on the Kerf svg (HS2-4AQJEX).
    expect(css).not.toMatch(/svg/);
    const markup = String(AIContentLabel({ tool: 'Claude', feedbackTarget: 'note:one' }));
    const icons = markup.match(/<svg[^>]*>/g) ?? [];
    expect(icons).toHaveLength(3);
    for (const icon of icons) expect(icon).toContain('data-size="xs"');
  });
});
