import './ai-content-label.css';

import { LucideIcon } from '@kerfjs/ui/lucide-icon';
import { Text } from '@kerfjs/ui/text';
import { Sparkles, ThumbsDown, ThumbsUp } from 'lucide';

import { COMMANDS_AND_AI_ACTIONS } from '../interaction-attrs/commands-and-ai';

export interface AIContentLabelProps {
  tool?: string;
  mayContainErrors?: boolean;
  feedbackTarget?: string;
  /** `quiet` (default) uses the secondary text color; `inherit` takes the surrounding heading's color. */
  tone?: 'quiet' | 'inherit';
}

export function AIContentFeedback({ tool = 'AI', feedbackTarget }: { tool?: string; feedbackTarget: string }) {
  const attribution = tool === 'AI' ? 'AI-generated' : `AI-generated by ${tool}`;
  return (
    <span class="ai-content-label__feedback" role="group" aria-label={`Feedback on ${attribution}`}>
      <button
        type="button"
        {...COMMANDS_AND_AI_ACTIONS.rateAiContent.attrs}
        data-ai-feedback-target={feedbackTarget}
        data-ai-feedback-rating="helpful"
        aria-label="Helpful — keep suggestions like this"
        title="Helpful — keep suggestions like this"
      >
        <LucideIcon size="xs" icon={ThumbsUp} name="thumbs-up" />
      </button>
      <button
        type="button"
        {...COMMANDS_AND_AI_ACTIONS.rateAiContent.attrs}
        data-ai-feedback-target={feedbackTarget}
        data-ai-feedback-rating="not-helpful"
        aria-label="Not helpful — stop suggestions like this"
        title="Not helpful — stop suggestions like this"
      >
        <LucideIcon size="xs" icon={ThumbsDown} name="thumbs-down" />
      </button>
    </span>
  );
}

/** Persistent, accessible attribution shared by every AI-authored client artifact. */
export function AIContentLabel({
  tool = 'AI',
  mayContainErrors = false,
  feedbackTarget,
  tone = 'quiet',
}: AIContentLabelProps) {
  const attribution = tool === 'AI' ? 'AI-generated' : `AI-generated by ${tool}`;
  const accessible = `${attribution}${mayContainErrors ? '; may contain errors' : ''}`;
  return (
    <span
      class="ai-content-label"
      data-component="ai-content-label"
      data-tone={tone === 'quiet' ? undefined : tone}
      aria-label={accessible}
    >
      <span class="ai-content-label__attribution">
        <LucideIcon size="xs" icon={Sparkles} name="sparkles" />
        <Text variant="span" size="compact" tone={tone === 'quiet' ? 'quiet' : 'default'}>
          {attribution}
          {mayContainErrors && <span> · may contain errors</span>}
        </Text>
      </span>
      {feedbackTarget && <AIContentFeedback tool={tool} feedbackTarget={feedbackTarget} />}
    </span>
  );
}
