import {describe,expect,it} from 'vitest';

import {AIContentLabel} from './ai-content-label';

describe('AIContentLabel',()=>{
  it('renders persistent factual attribution and consequence-labeled optional feedback',()=>{
    const markup=String(AIContentLabel({tool:'Claude',mayContainErrors:true,feedbackTarget:'note:one'}));
    expect(markup).toContain('aria-label="AI-generated by Claude; may contain errors"');
    expect(markup).toContain('Helpful — keep suggestions like this');
    expect(markup).toContain('Not helpful — stop suggestions like this');
    expect(markup).toContain('data-ai-feedback-target="note:one"');
  });
});
