import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { AIContentLabel } from './ai-content-label';

describe('AIContentLabel', () => {
  it('renders persistent factual attribution and consequence-labeled optional feedback', () => {
    const markup = String(AIContentLabel({ tool: 'Claude', mayContainErrors: true, feedbackTarget: 'note:one' }));
    expect(markup).toContain('aria-label="AI-generated by Claude; may contain errors"');
    expect(markup).toContain('Helpful — keep suggestions like this');
    expect(markup).toContain('Not helpful — stop suggestions like this');
    expect(markup).toContain('data-ai-feedback-target="note:one"');
  });
  it('uses semantic spacing while keeping feedback targets and glyphs explicit geometry', () => {
    const css = readFileSync(new URL('./ai-content-label.css', import.meta.url), 'utf8');
    expect(css).not.toContain('--wa-space-');
    expect(css).toMatch(/\.ai-content-label \{[^}]*gap: var\(--kui-space-xs\)/);
    expect(css).toMatchSource(/__attribution \{ gap: var\(--kui-space-2xs\)/);
    expect(css).toMatchSource(/__feedback \{ gap: var\(--kui-space-2xs\)/);
    expect(css).toMatchSource(/__feedback button \{[^}]*width: remify\(32px\); height: remify\(32px\)/);
    expect(css).toMatchSource(/__feedback svg \{ width: remify\(12px\); height: remify\(12px\)/);
  });
});
