import './ai-content-label.css';

import {LucideIcon} from '@kerfjs/ui/lucide-icon';
import {Sparkles,ThumbsDown,ThumbsUp} from 'lucide';

export interface AIContentLabelProps {
  tool?:string;
  mayContainErrors?:boolean;
  feedbackTarget?:string;
}

/** Persistent, accessible attribution shared by every AI-authored client artifact. */
export function AIContentLabel({tool='AI',mayContainErrors=false,feedbackTarget}:AIContentLabelProps){
  const attribution=tool==='AI'?'AI-generated':`AI-generated by ${tool}`;
  const accessible=`${attribution}${mayContainErrors?'; may contain errors':''}`;
  return <span class="ai-content-label" data-component="ai-content-label" aria-label={accessible}>
    <span class="ai-content-label__attribution"><LucideIcon icon={Sparkles} name="sparkles"/>{attribution}{mayContainErrors&&<span> · may contain errors</span>}</span>
    {feedbackTarget&&<span class="ai-content-label__feedback" role="group" aria-label={`Feedback on ${attribution}`}>
      <button type="button" data-action="rate-ai-content" data-ai-feedback-target={feedbackTarget} data-ai-feedback-rating="helpful" aria-label="Helpful — keep suggestions like this" title="Helpful — keep suggestions like this"><LucideIcon icon={ThumbsUp} name="thumbs-up"/></button>
      <button type="button" data-action="rate-ai-content" data-ai-feedback-target={feedbackTarget} data-ai-feedback-rating="not-helpful" aria-label="Not helpful — stop suggestions like this" title="Not helpful — stop suggestions like this"><LucideIcon icon={ThumbsDown} name="thumbs-down"/></button>
    </span>}
  </span>;
}
