import './ai-conversation.css';

import {Activity,Bot,MessageSquare,Send,Sparkles,Square,X} from 'lucide';

import {type ConversationActivity,type ConversationMessage,type ConversationUsage,formatConversationCost,formatConversationTokens} from '../ai-conversation';
import type { PermissionItem } from '../permission-notifications';
import {LucideIcon} from './lucide-icon';
import {MarkdownPreview} from './markdown-preview';
import {PermissionRequestCard} from './permission-request-card';

export interface AIConversationProps {open:boolean;tool:string;sessionId?:string;messages:ConversationMessage[];draft:string;busy:boolean;progress?:string;interruptible:boolean;permissions?:PermissionItem[];activity?:ConversationActivity[];totalUsage?:ConversationUsage;error?:string}

function UsageLine({usage,label='Turn usage'}:{usage:ConversationUsage;label?:string}){const total=usage.tokensIn+usage.tokensOut;return <p class="ai-conversation__usage" aria-label={`${label}: ${usage.tokensIn} input tokens, ${usage.tokensOut} output tokens, ${formatConversationCost(usage.costUsd)}`}><span>{formatConversationTokens(total)} tokens</span><span>{formatConversationCost(usage.costUsd)}</span>{usage.model&&<span title={usage.model}>{usage.model}</span>}</p>}

export function AIConversation({open,tool,sessionId,messages,draft,busy,progress,interruptible,permissions=[],activity=[],totalUsage,error}:AIConversationProps){
  return <wa-dialog class="ai-conversation" data-component="ai-conversation" label={`${tool} conversation`} open={open||undefined} with-footer>
    <header class="ai-conversation__header"><span><LucideIcon icon={Bot} name="bot"/><span><strong>{tool}</strong><small>{sessionId?`Session ${sessionId}`:'Project conversation'}</small></span></span><div>{totalUsage&&<UsageLine usage={totalUsage} label="Conversation usage"/>}{busy&&interruptible&&<button type="button" data-action="stop-conversation" aria-label={`Stop ${tool}`} title={`Stop ${tool}`}><LucideIcon icon={Square} name="square"/></button>}<button type="button" data-action="close-conversation" aria-label="Close conversation" title="Close conversation"><LucideIcon icon={X} name="x"/></button></div></header>
    <section class="ai-conversation__transcript" aria-label="Conversation transcript" aria-live="polite">{messages.length===0&&<div class="ai-conversation__empty"><LucideIcon icon={MessageSquare} name="message-square"/><strong>Start a conversation</strong><p>Ask {tool} about this project or send it a task.</p></div>}{messages.map(message=><article class={`ai-conversation__message ai-conversation__message--${message.role}`} data-message-id={message.id} data-status={message.status}><strong>{message.role==='user'?'You':tool}</strong>{message.content?<MarkdownPreview source={message.content}/>:<p aria-label="Awaiting response"> </p>}{message.usage&&<UsageLine usage={message.usage}/>}</article>)}{activity.length>0&&<section class="ai-conversation__activity" aria-label="AI-generated activity summaries; may contain errors"><header><span><LucideIcon icon={Activity} name="activity"/><strong>Activity</strong></span><small><LucideIcon icon={Sparkles} name="sparkles"/> AI-generated · may contain errors</small></header><ol>{activity.map(item=><li data-activity-id={item.id} data-importance={item.importance}><span class="ai-conversation__activity-label"><LucideIcon icon={Sparkles} name="sparkles"/>AI · {item.tool}</span><span>{item.summary}</span></li>)}</ol></section>}{permissions.map(item=><div data-permission-key={item.key}><PermissionRequestCard item={item} presentation="list"/></div>)}{busy&&progress&&<p class="ai-conversation__progress" role="status"><LucideIcon icon={Bot} name="bot"/>{progress}</p>}{error&&<p class="ai-conversation__error" role="alert">{error}</p>}</section>
    <form slot="footer" class="ai-conversation__composer" data-action="send-conversation-turn"><textarea name="conversation-draft" aria-label={`Message ${tool}`} placeholder={`Message ${tool}…`} rows={3} disabled={busy}>{draft}</textarea><button type="submit" disabled={busy||!draft.trim()} aria-label={`Send message to ${tool}`} title={busy?`${tool} is still working`:`Send message to ${tool}`}><LucideIcon icon={Send} name="send"/></button></form>
  </wa-dialog>;
}
