import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import './global-search-overlay.css';

import type {Filter} from 'lucide';
import {Archive,ArrowRight,Clock3,FolderSearch2,MessageSquareMore,Search,Star,TriangleAlert,X} from 'lucide';

import {type SearchFilter,searchFilters,type SearchScope,searchScopeChoices} from '../advanced-search';
import type {TicketRow} from '../api';
import {LucideIcon} from './lucide-icon';
import {MenuItem} from './menu-item';
import {Select} from './select';

const filterIcons:Record<SearchFilter,{icon:typeof Filter;name:string}>={
  'status:backlog':{icon:Clock3,name:'clock-3'},'status:archive':{icon:Archive,name:'archive'},'status:deleted':{icon:X,name:'x'},
  'up-next':{icon:Star,name:'star'},'needs-review':{icon:MessageSquareMore,name:'message-square-more'},'blocked':{icon:TriangleAlert,name:'triangle-alert'},
};
export function SearchQueryInput({value,loading=false}:{value:string;loading?:boolean}){return <wa-input class="global-search__input" name="global-search-query" label="Search every ticket" placeholder="Search tickets, notes, tags, or ticket numbers" value={value} autofocus><span slot="start"><LucideIcon icon={Search} name="search"/></span>{loading&&<span slot="end" class="global-search__loading" role="status" aria-label="Searching"/>}</wa-input>}
export function SearchScopePicker({value}:{value:SearchScope}){return <Select className="global-search__scope" name="global-search-scope" ariaLabel="Search scope" value={value} choices={searchScopeChoices}/>}
export function FilterChip({filter}:{filter:SearchFilter}){const label=searchFilters.find(item=>item.id===filter)?.label??filter;return <span class="filter-chip" data-component="filter-chip"><span>{label}</span><button type="button" data-action="remove-search-filter" data-filter={filter} aria-label={`Remove ${label} filter`}><LucideIcon icon={X} name="x"/></button></span>}
export function ActiveFilterBar({filters}:{filters:readonly SearchFilter[]}){return <div class="active-filter-bar" data-component="active-filter-bar" aria-label="Active search filters">{filters.map(filter=><FilterChip filter={filter}/>)}{filters.length>1&&<button type="button" class="active-filter-bar__clear" data-action="clear-search-filters">Clear all</button>}</div>}
export function SearchSuggestionList({active}:{active:readonly SearchFilter[]}){const available=searchFilters.filter(item=>!active.includes(item.id));if(!available.length)return null;return <section class="search-suggestions" data-component="search-suggestion-list" aria-label="Suggested filters"><span class="search-suggestions__label">Refine</span><div>{available.map(item=>{const icon=filterIcons[item.id];return <button type="button" data-action="add-search-filter" data-filter={item.id}><LucideIcon icon={icon.icon} name={icon.name}/>{item.label}</button>})}</div></section>}
export interface SearchResult extends TicketRow{matchLabel:string;providerLabel:string}
export function SearchResultRow({ticket}:{ticket:SearchResult}){return <MenuItem className="search-result-row" action="select-search-result" itemId={ticket.qualified_id} icon={<span class="search-result-row__status" data-status={ticket.status}/>} label={<><strong>{ticket.slug}</strong><span>{ticket.title}</span></>} trailing={<span><em>{ticket.matchLabel}</em><small>{ticket.providerLabel}</small></span>} multiline accessibleLabel={`${ticket.slug}: ${ticket.title}. Matched ${ticket.matchLabel}. Source ${ticket.providerLabel}`}/>}
export function SavedViewAction(){return <wa-button appearance="plain" size="small" data-action="save-search-as-view"><LucideIcon icon={ArrowRight} name="arrow-right"/> Save as view</wa-button>}
export function GlobalSearchOverlay({open,query,scope,filters,results,loading=false,embedded=false}:{open:boolean;query:string;scope:SearchScope;filters:readonly SearchFilter[];results:readonly SearchResult[];loading?:boolean;embedded?:boolean}){if(!open)return null;return <div class="global-search-backdrop" data-embedded={embedded?'true':undefined} data-action="close-global-search" data-component="global-search-overlay"><section class="global-search" role="dialog" aria-modal={embedded?undefined:'true'} aria-label="Search all tickets" data-search-surface="true"><header><LucideIcon icon={FolderSearch2} name="folder-search-2"/><div><h2>Search tickets</h2><p>Search every connected source without changing your current view.</p></div><wa-button appearance="plain" data-action="close-global-search" aria-label="Close search"><LucideIcon icon={X} name="x"/></wa-button></header><div class="global-search__controls"><SearchQueryInput value={query} loading={loading}/><SearchScopePicker value={scope}/></div><ActiveFilterBar filters={filters}/><SearchSuggestionList active={filters}/><div class="global-search__results" aria-live="polite">{query.trim()?(results.length?results.map(ticket=><SearchResultRow ticket={ticket}/>):!loading&&<p class="global-search__empty">No matching tickets.</p>):<p class="global-search__empty">Start typing to search titles, details, notes, tags, and ticket references.</p>}</div><footer><span>{results.length} result{results.length===1?'':'s'}</span><SavedViewAction/></footer></section></div>}
