import { describe, expect, it } from 'vitest';

import { FixedAspectTerminalCard, TerminalDashboard, TerminalDashboardControls, type TerminalDashboardGroup } from './terminal-dashboard';

const groups:TerminalDashboardGroup[]=[{projectId:'one',projectName:'Project One',sessions:[{id:'term-1',projectId:'one',projectName:'Project One',title:'Codex',alive:true,busy:true,cwd:'/work/one',progress:42,scrollback:'Working\nRunning tests'}]}];

describe('TerminalDashboard',()=>{
  it('renders every dashboard terminal as a fixed 80x24 scaled non-interactive viewport with terminal state and zoom controls',()=>{const markup=String(TerminalDashboard({groups,width:1200,height:700,fitAcross:4,fitHigh:2}));expect(markup).toContain('data-basis="across"');expect(markup).toContain('data-fit="4"');expect(markup).toContain('Project One');expect(markup).toContain('Running tests');expect(markup).toContain('42%');expect(markup).toContain('data-component="terminal-viewport"');expect(markup).toContain('data-display-mode="scaled-preview"');expect(markup).toContain('data-grid-policy="dashboard-80x24"');expect(markup).toContain('aria-hidden="true"');expect(markup).toContain('data-action="preview-terminal"');expect(markup).toContain('data-action="zoom-terminal-grid"');for(const action of ['magnify-terminal','dedicate-terminal'])expect(markup).not.toContain(`data-action="${action}"`)});
  it('makes the footer identity actionable, explains terminal state, and omits the snapshot working directory',()=>{const markup=String(TerminalDashboard({groups,width:1200,height:700,fitAcross:4,fitHigh:2}));expect(markup).toContain('aria-label="Open Codex in Project One"');expect(markup).toContain('aria-label="Busy" title="Busy"');expect(markup).not.toContain('/work/one')});
  it('uses one fixed-aspect card component for preview and magnified modes',()=>{const session=groups[0].sessions[0],preview=String(FixedAspectTerminalCard({session})),magnified=String(FixedAspectTerminalCard({session,mode:'magnified'}));for(const markup of [preview,magnified]){expect(markup).toContain('terminal-tile__viewport-frame');expect(markup).toContain('data-grid-policy="dashboard-80x24"');expect(markup).toContain('data-geometry-ready="false"');expect(markup).toContain('data-action="open-terminal-context-menu"');expect(markup).toContain('data-lucide="ellipsis"')}expect(preview).toContain('data-fixed-aspect-terminal-card="preview"');expect(preview).toContain('data-display-mode="scaled-preview"');expect(magnified).toContain('data-fixed-aspect-terminal-card="magnified"');expect(magnified).toContain('data-display-mode="interactive"')});
  it('keeps the smallest tile keyboard-focusable and makes only its fixed-grid magnified copy interactive',()=>{const compact=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3}));expect(compact).toContain('data-basis="high"');expect(compact).toContain('data-fit="3"');expect(compact).toContain('data-preview-only="true"');expect(compact).toContain('data-display-mode="scaled-preview"');const magnified=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3,magnifiedKey:'one:term-1'}));expect(magnified).toContain('role="dialog"');expect(magnified).toContain('data-display-mode="interactive"');expect(magnified.match(/data-grid-policy="dashboard-80x24"/g)).toHaveLength(2);expect(magnified.match(/data-component="terminal-viewport"/g)).toHaveLength(2);expect(magnified).toContain('data-action="open-terminal-project"');expect(magnified).toContain('Open Codex in project terminal drawer');expect(magnified).not.toContain('Restore terminal grid')});
  it('uses the standard context-menu items for both right-click and the footer action',()=>{const markup=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3,contextMenu:{key:'one:term-1',x:20,y:30}}));expect(markup).toContain('data-action="open-terminal-context-menu"');expect(markup).toContain('data-component="terminal-context-menu"');expect(markup.match(/<wa-dropdown-item/g)).toHaveLength(2);expect(markup).toContain('data-action="open-terminal-project"');expect(markup).toContain('data-action="hide-dashboard-terminal"')});
  it('uses a compact label select for visibility groups and omits global layout grouping',()=>{const visibilityGroups=[{id:'default',name:'Default',hiddenKeys:[]},{id:'focus',name:'Focus',hiddenKeys:['one:term-1']}],markup=String(TerminalDashboardControls({hiddenCount:2,visibilityGroups,activeVisibilityGroupId:'focus'}));expect(markup).toContain('data-action="open-terminal-visibility"');expect(markup).toContain('>2</span>');expect(markup).toContain('name="terminal-visibility-group"');expect(markup).toContain('class="select__custom-selected"><span>Focus</span>');expect(markup).toContain('<wa-option value="focus"');expect(markup).not.toContain('name="terminal-grouping"')});
  it('uses width-based wrapping after drawer fit one',()=>{const markup=String(TerminalDashboard({groups,width:876,height:296,fitAcross:2,fitHigh:2,layoutMode:'drawer'}));expect(markup).toContain('data-layout-mode="drawer"');expect(markup).toContain('--terminal-tile-width:432px');expect(markup).toContain('--terminal-tile-height:313px')});
});
