import { describe,expect,it } from 'vitest';

import { TerminalDrawer } from './terminal-drawer';

const sessions=[{id:'one',projectId:'project',projectName:'Project',title:'Terminal 1',alive:true,busy:true,scrollback:'one'},{id:'two',projectId:'project',projectName:'Project',title:'Terminal 2',alive:true,busy:false,scrollback:'two'}];
const render=(selectedId:string='grid')=>String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:320,fitAcross:2,fitHigh:2,selectedId}));
describe('TerminalDrawer',()=>{
  it('renders shared, closeable terminal tabs with trailing state before the create action',()=>{const markup=render();expect(markup).toContain('data-mode="grid"');expect(markup).toContain('data-maximized="false"');expect(markup).toContain('aria-label="Terminal grid"');expect(markup).toContain('terminal-drawer__tabs');expect(markup).toMatch(/terminal-drawer__tabs[\s\S]*Terminal 2[\s\S]*terminal-drawer__create/);expect(markup).toContain('data-component="terminal-tab"');expect(markup).toContain('class="app-tab');expect(markup).toContain('data-action="close-terminal-tab"');expect(markup.indexOf('Terminal 1')).toBeLessThan(markup.indexOf('aria-label="Busy"'));for(const action of ['select-drawer-terminal','create-project-terminal','toggle-terminal-drawer','toggle-terminal-drawer-maximize'])expect(markup).toContain(`data-action="${action}"`)});
  it('describes the rail double-click state',()=>{const markup=String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:700,fitAcross:2,fitHigh:2,selectedId:'grid',maximized:true}));expect(markup).toContain('data-maximized="true"');expect(markup).toContain('Double-click to restore terminal drawer')});
  it('selects one undecorated full-content terminal without grid chrome or zoom',()=>{const markup=render('one');expect(markup).toContain('data-mode="dedicated"');expect(markup).toContain('data-component="terminal-session"');expect(markup.match(/data-terminal-id="one"/g)?.length).toBeGreaterThanOrEqual(2);expect(markup.match(/data-component="terminal-viewport"/g)).toHaveLength(1);expect(markup).not.toContain('data-component="terminal-tile"');expect(markup).not.toContain('Terminal tile zoom')});
  it('offers recovery for project-scoped hidden terminals',()=>{expect(String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:320,fitAcross:2,fitHigh:2,selectedId:'grid',hiddenKeys:['project:one']}))).toContain('Show 1 hidden project terminal')});
});
