import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe,expect,it } from 'vitest';

import {AIConversation} from './ai-conversation';
import { TerminalDrawer } from './terminal-drawer';

const sessions=[{id:'one',projectId:'project',projectName:'Project',title:'Terminal 1',alive:true,busy:true,scrollback:'one'},{id:'two',projectId:'project',projectName:'Project',title:'Terminal 2',alive:true,busy:false,scrollback:'two'}];
const render=(selectedId:string='grid')=>String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:320,fitAcross:2,fitHigh:2,selectedId}));
describe('TerminalDrawer',()=>{
  it('keeps the grid tab fixed while terminal tabs overflow',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8');expect(css).toMatch(/\.terminal-drawer__views > \[role="tab"\] \{ flex: none; \}/)});
  it('keeps the wrapped create action on the shared transparent pill button surface',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8'),base=css.match(/\.terminal-drawer__rail > button, \.terminal-drawer__views > button, \.terminal-drawer__create, \.terminal-drawer__actions > button \{([^}]+)\}/)?.[1]??'';expect(base).toContain('height: 2rem');expect(base).toContain('border-radius: var(--wa-border-radius-pill)');expect(base).toContain('background: transparent');expect(css).toContain('.terminal-drawer__create:hover');expect(css).toContain('.terminal-drawer__create:focus-visible')});
  it('reserves a complete gutter for focus rings and selected-tab shadows inside the horizontal scroller',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8'),rule=css.match(/\.terminal-drawer__tabs \{([^}]+)\}/)?.[1]??'';expect(rule).toContain('overflow-x: auto');expect(rule).toContain('padding: var(--wa-space-2xs)');expect(rule).toContain('margin: calc(var(--wa-space-2xs) * -1)')});
  it('sizes terminal names from their content instead of reserving icon-width name space',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8'),rule=css.match(/\.terminal-drawer__rail \.terminal-tab__name \{([^}]+)\}/)?.[1]??'';expect(rule).toContain('max-width: 9rem');expect(rule).not.toContain('min-width')});
  it('renders shared, draggable and keyboard-focusable terminal tabs before the create action',()=>{const markup=render();expect(markup).toContain('data-mode="grid"');expect(markup).toContain('data-maximized="false"');expect(markup).toContain('aria-label="Terminal grid"');expect(markup).toContain('terminal-drawer__tabs');expect(markup).toMatch(/terminal-drawer__tabs[\s\S]*Terminal 2[\s\S]*terminal-drawer__create/);expect(markup).toContain('data-component="terminal-tab"');expect(markup).toContain('data-tab-kind="terminal"');expect(markup).toContain('draggable="true"');expect(markup).toContain('tabindex="0"');expect(markup).toContain('class="app-tab');expect(markup).toContain('data-action="close-terminal-tab"');expect(markup.indexOf('Terminal 1')).toBeLessThan(markup.indexOf('aria-label="Busy"'));for(const action of ['select-drawer-item','toggle-terminal-create-menu','toggle-terminal-drawer','toggle-terminal-drawer-maximize'])expect(markup).toContain(`data-action="${action}"`)});
  it('opens a direct action menu without a redundant heading or false submenu disclosures',()=>{const content=AIConversation({open:true,presentation:'embedded',tool:'Codex',messages:[],draft:'',busy:false,interruptible:false}),chat=String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,chatTabs:[{id:'chat:one',name:'Codex chat',tool:'Codex',content}],width:900,height:320,fitAcross:2,fitHigh:2,selectedId:'chat:one',createMenuOpen:true}));expect(chat).toContain('data-mode="ai-chat"');expect(chat).toContain('data-component="ai-chat-tab"');expect(chat).toContain('data-action="close-ai-chat-tab"');expect(chat).toContain('data-presentation="embedded"');for(const item of ['Default shell','AI shell','AI chat'])expect(chat).toContain(item);expect(chat).toContain('role="menu"');expect(chat).not.toContain('data-component="menu-header"');expect(chat).not.toContain('data-lucide="chevron-right"');expect(chat.match(/data-component="menu-item"/g)).toHaveLength(3)});
  it('renders a remembered mixed-kind order with matching reorder shortcuts',()=>{const content=AIConversation({open:true,presentation:'embedded',tool:'Codex',messages:[],draft:'',busy:false,interruptible:false}),markup=String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,chatTabs:[{id:'chat:one',name:'Codex chat',tool:'Codex',content}],tabOrder:['two','chat:one','one'],width:900,height:320,fitAcross:2,fitHigh:2,selectedId:'grid'}));expect(markup.indexOf('Terminal 2')).toBeLessThan(markup.indexOf('Codex chat'));expect(markup.indexOf('Codex chat')).toBeLessThan(markup.indexOf('Terminal 1'));expect(markup.match(/aria-keyshortcuts="Delete Backspace Alt\+Shift\+ArrowLeft Alt\+Shift\+ArrowRight"/g)).toHaveLength(3)});
  it('reserves the shared trailing tab slot whether or not a terminal has state',()=>{const markup=render();expect(markup.match(/terminal-tab__trailing/g)).toHaveLength(2);expect(markup).toMatch(/Terminal 1<\/span><span class="app-tab__trailing terminal-tab__trailing"><i aria-label="Busy"/);expect(markup).toMatch(/Terminal 2<\/span><span class="app-tab__trailing terminal-tab__trailing"><\/span>/)});
  it('describes the rail double-click state',()=>{const markup=String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:700,fitAcross:2,fitHigh:2,selectedId:'grid',maximized:true}));expect(markup).toContain('data-maximized="true"');expect(markup).toContain('Double-click to restore terminal drawer')});
  it('selects one undecorated full-content terminal without grid chrome or zoom',()=>{const markup=render('one');expect(markup).toContain('data-mode="dedicated"');expect(markup).toContain('data-component="terminal-session"');expect(markup.match(/data-terminal-id="one"/g)?.length).toBeGreaterThanOrEqual(2);expect(markup.match(/data-component="terminal-viewport"/g)).toHaveLength(1);expect(markup).not.toContain('data-component="terminal-tile"');expect(markup).not.toContain('Terminal tile zoom')});
  it('keeps project-drawer visibility local and offers no grouping controls',()=>{const markup=render();expect(markup).not.toContain('aria-label="Manage terminal visibility"');expect(markup).not.toContain('name="terminal-visibility-group"');expect(markup).not.toContain('data-visibility-scope')});
  it('uses available width for drawer grid levels above fit one',()=>{const markup=render();expect(markup).toContain('--terminal-tile-width:432px');expect(markup).toContain('--terminal-tile-height:312px')});
  it('uses one horizontal row at fit one and row-major wrapping above it',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-dashboard.css'),'utf8');expect(css).toMatch(/data-basis="high"\] \{[^}]*grid-template-columns: repeat\(auto-fill/);expect(css).toMatch(/data-basis="high"\]\[data-fit="1"\] \{[^}]*grid-auto-flow: column/)});
});
