import { describe, expect, it } from 'vitest';

import { TerminalDashboard, TerminalDashboardControls, type TerminalDashboardGroup } from './terminal-dashboard';

const groups:TerminalDashboardGroup[]=[{projectId:'one',projectName:'Project One',sessions:[{id:'term-1',projectId:'one',projectName:'Project One',title:'Codex',alive:true,busy:true,cwd:'/work/one',progress:42,scrollback:'Working\nRunning tests'}]}];

describe('TerminalDashboard',()=>{
  it('renders every dashboard terminal as a scaled non-interactive viewport with terminal state and zoom controls',()=>{const markup=String(TerminalDashboard({groups,width:1200,height:700,fitAcross:4,fitHigh:2}));expect(markup).toContain('data-basis="across"');expect(markup).toContain('data-fit="4"');expect(markup).toContain('Project One');expect(markup).toContain('Running tests');expect(markup).toContain('42%');expect(markup).toContain('data-component="terminal-viewport"');expect(markup).toContain('data-display-mode="scaled-preview"');expect(markup).toContain('aria-hidden="true"');expect(markup).toContain('data-action="preview-terminal"');expect(markup).toContain('data-action="zoom-terminal-grid"');for(const action of ['magnify-terminal','dedicate-terminal'])expect(markup).not.toContain(`data-action="${action}"`)});
  it('keeps the smallest tile keyboard-focusable and makes only its magnified copy interactive',()=>{const compact=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3}));expect(compact).toContain('data-basis="high"');expect(compact).toContain('data-fit="3"');expect(compact).toContain('data-preview-only="true"');expect(compact).toContain('data-display-mode="scaled-preview"');const magnified=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3,magnifiedKey:'one:term-1'}));expect(magnified).toContain('role="dialog"');expect(magnified).toContain('data-display-mode="interactive"');expect(magnified.match(/data-component="terminal-viewport"/g)).toHaveLength(2);expect(magnified).not.toContain('Restore terminal grid')});
  it('uses shared menu items for right-click Open and Hide actions',()=>{const markup=String(TerminalDashboard({groups,width:900,height:600,fitAcross:7,fitHigh:3,contextMenu:{key:'one:term-1',x:20,y:30}}));expect(markup).toContain('data-component="terminal-context-menu"');expect(markup.match(/data-component="menu-item"/g)).toHaveLength(2);expect(markup).toContain('data-action="open-terminal-project"');expect(markup).toContain('data-action="hide-dashboard-terminal"')});
  it('reuses bordered toolbar button and a viewport-safe Select for global visibility and grouping controls',()=>{const markup=String(TerminalDashboardControls({grouping:'project',hiddenCount:2}));expect(markup).toContain('<button');expect(markup).toContain('data-action="show-hidden-terminals"');expect(markup).toContain('>2</span>');expect(markup.match(/data-appearance="contained"/g)).toHaveLength(2);expect(markup).toContain('data-component="select"');expect(markup).toContain('select--fit-menu');expect(markup).toContain('name="terminal-grouping"');expect(markup).toContain('aria-label="Group terminals: Project"');expect(markup).toContain('<wa-option value="project"');expect(markup).toContain('<wa-option value="flow"')});
});
