import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe,expect,it } from 'vitest';

import { TerminalDrawer } from './terminal-drawer';

const sessions=[{id:'one',projectId:'project',projectName:'Project',title:'Terminal 1',alive:true,busy:true,scrollback:'one'},{id:'two',projectId:'project',projectName:'Project',title:'Terminal 2',alive:true,busy:false,scrollback:'two'}];
const render=(selectedId:string='grid')=>String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:320,fitAcross:2,fitHigh:2,selectedId}));
describe('TerminalDrawer',()=>{
  it('keeps the grid tab fixed while terminal tabs overflow',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8');expect(css).toMatch(/\.terminal-drawer__views > \[role="tab"\] \{ flex: none; \}/)});
  it('reserves a block-axis gutter for selected-tab shadows inside the horizontal scroller',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8'),rule=css.match(/\.terminal-drawer__tabs \{([^}]+)\}/)?.[1]??'';expect(rule).toContain('overflow-x: auto');expect(rule).toContain('padding-block: var(--wa-space-2xs)');expect(rule).toContain('margin-block: calc(var(--wa-space-2xs) * -1)')});
  it('sizes terminal names from their content instead of reserving icon-width name space',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-drawer.css'),'utf8'),rule=css.match(/\.terminal-drawer__rail \.terminal-tab__name \{([^}]+)\}/)?.[1]??'';expect(rule).toContain('max-width: 9rem');expect(rule).not.toContain('min-width')});
  it('renders shared, closeable terminal tabs with trailing state before the create action',()=>{const markup=render();expect(markup).toContain('data-mode="grid"');expect(markup).toContain('data-maximized="false"');expect(markup).toContain('aria-label="Terminal grid"');expect(markup).toContain('terminal-drawer__tabs');expect(markup).toMatch(/terminal-drawer__tabs[\s\S]*Terminal 2[\s\S]*terminal-drawer__create/);expect(markup).toContain('data-component="terminal-tab"');expect(markup).toContain('class="app-tab');expect(markup).toContain('data-action="close-terminal-tab"');expect(markup.indexOf('Terminal 1')).toBeLessThan(markup.indexOf('aria-label="Busy"'));for(const action of ['select-drawer-terminal','create-project-terminal','toggle-terminal-drawer','toggle-terminal-drawer-maximize'])expect(markup).toContain(`data-action="${action}"`)});
  it('reserves the shared trailing tab slot whether or not a terminal has state',()=>{const markup=render();expect(markup.match(/terminal-tab__trailing/g)).toHaveLength(2);expect(markup).toMatch(/Terminal 1<\/span><span class="app-tab__trailing terminal-tab__trailing"><i aria-label="Busy"/);expect(markup).toMatch(/Terminal 2<\/span><span class="app-tab__trailing terminal-tab__trailing"><\/span>/)});
  it('describes the rail double-click state',()=>{const markup=String(TerminalDrawer({projectId:'project',projectName:'Project',sessions,width:900,height:700,fitAcross:2,fitHigh:2,selectedId:'grid',maximized:true}));expect(markup).toContain('data-maximized="true"');expect(markup).toContain('Double-click to restore terminal drawer')});
  it('selects one undecorated full-content terminal without grid chrome or zoom',()=>{const markup=render('one');expect(markup).toContain('data-mode="dedicated"');expect(markup).toContain('data-component="terminal-session"');expect(markup.match(/data-terminal-id="one"/g)?.length).toBeGreaterThanOrEqual(2);expect(markup.match(/data-component="terminal-viewport"/g)).toHaveLength(1);expect(markup).not.toContain('data-component="terminal-tile"');expect(markup).not.toContain('Terminal tile zoom')});
  it('keeps project-drawer visibility local and offers no grouping controls',()=>{const markup=render();expect(markup).not.toContain('aria-label="Manage terminal visibility"');expect(markup).not.toContain('name="terminal-visibility-group"');expect(markup).not.toContain('data-visibility-scope')});
  it('uses available width for drawer grid levels above fit one',()=>{const markup=render();expect(markup).toContain('--terminal-tile-width:432px');expect(markup).toContain('--terminal-tile-height:313px')});
  it('uses one horizontal row at fit one and row-major wrapping above it',()=>{const css=readFileSync(resolve(import.meta.dirname,'terminal-dashboard.css'),'utf8');expect(css).toMatch(/data-basis="high"\] \{[^}]*grid-template-columns: repeat\(auto-fill/);expect(css).toMatch(/data-basis="high"\]\[data-fit="1"\] \{[^}]*grid-auto-flow: column/)});
});
